- go.mod
- pkg/controller/kfdef/const.go
- pkg/controller/kfdef/kfdef_controller.go
This PR rebases our master to kfctl master, @crobby @LaVLaS PTAL
I think if we select "Rebase and merge" when merging, it will give us clean sync with upstream
> Rebase upstream master

- deploy/olm-catalog/opendatahub/0.6.1/kfdef.apps.kubeflow.org.crd.yaml
- deploy/olm-catalog/opendatahub/0.6.1/opendatahub-operator.v0.6.1.clusterserviceversion.yaml
- deploy/olm-catalog/opendatahub/opendatahub-operator.package.yaml
Adding the CSV for the 0.6.1 release. For the example kfdef, I used the odh-manifest [kfctl_openshift.yaml](https://github.com/opendatahub-io/odh-manifests/blob/master/kfdef/kfctl_openshift.yaml)
> Add CSV for 0.6.1

- deploy/olm-catalog/opendatahub/0.7.0/kfdef.apps.kubeflow.org.crd.yaml
- deploy/olm-catalog/opendatahub/0.7.0/opendatahub-operator.v0.7.0.clusterserviceversion.yaml
to test oc apply crd and rbac( role, rolebinding, serviceaccount, copy from csv) in ocp operators namespace
> Add release CSV 0.7.0

- .thoth.yaml
> Add lavlas to thoth maintainers

- deploy/olm-catalog/opendatahub/0.9.0/kfdef.apps.kubeflow.org.crd.yaml
- deploy/olm-catalog/opendatahub/0.9.0/opendatahub-operator.v0.9.0.clusterserviceversion.yaml
- deploy/olm-catalog/opendatahub/opendatahub-operator.package.yaml
CSV release for odh 0.9.0
Closes ! #73
> ODH 0.9.0 Release

- version.py
Rebase the version string with latest release
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
> Rebase the version string with latest release

- pkg/controller/kfdef/const.go
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>
> Fix imagestream watch

- version.py
Updating version to sync sesheta bot pipeline execution with actual release version
> Manually update version.py to 1.0.8

- pkg/controller/kfdef/kfdef_controller.go
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>
> Update ODH operator to reconcile updated objects

- deploy/olm-catalog/opendatahub/1.0.10/manifests/opendatahub-operator.v1.0.10.clusterserviceversion.yaml
- deploy/olm-catalog/opendatahub/1.0.10/metadata/annotations.yaml
- deploy/olm-catalog/opendatahub/ci.yaml
> Update the OLM files to bring them inline with community-operator changes

- CHANGELOG.md
- version.py
> Update for CHANGELOG for v1.1.0 release

- Dockerfile.bundle
- deploy/olm-catalog/opendatahub/1.1.2/manifests/kfdef.apps.kubeflow.org.crd.yaml
- deploy/olm-catalog/opendatahub/1.1.2/manifests/opendatahub-operator.v1.1.2.clusterserviceversion.yaml
- deploy/olm-catalog/opendatahub/1.1.2/metadata/annotations.yaml
- deploy/olm-catalog/opendatahub/ci.yaml
Add OLM bundle for the v1.1.2 release of the operator
> Add odh v1.1.2 OLM bundle

- CHANGELOG.md
- Dockerfile.bundle
- deploy/olm-catalog/opendatahub/1.2.0/manifests/kfdef.apps.kubeflow.org.crd.yaml
- deploy/olm-catalog/opendatahub/1.2.0/manifests/opendatahub-operator.v1.2.0.clusterserviceversion.yaml
- deploy/olm-catalog/opendatahub/1.2.0/metadata/annotations.yaml
- deploy/olm-catalog/opendatahub/ci.yaml
Add release files for the ODH v1.2.0 build 
> ODH Operator release v1.2.0

- deploy/olm-catalog/opendatahub/1.3.0/manifests/opendatahub-operator.v1.3.0.clusterserviceversion.yaml
Update the example kfdef that is automatically filled in when creating a new kfdef to utilize the authentication overlay for odh-dashboard.
Manually modified csv on running cluster to validate default change
> Default the example kfdef to have odh-dashboard to use the authentication overlay

- deploy/olm-catalog/opendatahub/1.4.2/manifests/kfdef.apps.kubeflow.org.crd.yaml
- deploy/olm-catalog/opendatahub/1.4.2/manifests/odhapplications.dashboard.opendatahub.io.crd.yaml
- deploy/olm-catalog/opendatahub/1.4.2/manifests/odhdashboardconfigs.opendatahub.io.crd.yaml
- deploy/olm-catalog/opendatahub/1.4.2/manifests/odhdocuments.dashboard.opendatahub.io.crd.yaml
- deploy/olm-catalog/opendatahub/1.4.2/manifests/odhquickstarts.console.openshift.io.crd.yaml
- deploy/olm-catalog/opendatahub/1.4.2/manifests/opendatahub-operator.v1.4.2.clusterserviceversion.yaml
- deploy/olm-catalog/opendatahub/1.4.2/metadata/annotations.yaml
Add the release files for ODH v1.4.2
> Add release files for ODH 1.4.2

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
> Update Operator ImagPullPolicy to 'Always'

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
we did not specify value for this container, by default/if not specify, it uses IfNotPresent
> Add imagepullpolicy for kube-rbac-proxy

- controllers/dscinitialization/dscinitialization_controller.go
During test, I have two instance of dscinitialzation created "default" and "dscinitialization-sample"
manager container in opendatahub-operator-controller-manager-* pod keep crashloop but info if misleading:
`Observed a panic: &errors.errorString{s:"not an App Engine context"} (not an App Engine context)`
first have two instances, then build image and deploy
>make image && make deploy -e IMG=quay.io/wenzhou/opendatahub-operator:dev-0.0.3
```
....
2023-07-03T17:34:44Z	INFO	Starting Controller	{"controller": "dscinitialization", "controllerGroup": "dscinitialization.opendatahub.io", "controllerKind": "DSCInitialization"}
2023-07-03T17:34:44Z	ERROR	dscinitialization	Wrong name	{"object": "dscinitialization-sample", "error": "Only single DSCInitialization instance can be created. Mismatch …
```
> Update logger for dscinitialzation start time

- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- controllers/dscinitialization/dscinitialization_controller.go
- go.mod
- go.sum
- pkg/deploy/setup.go
Fixes #263 
When https://github.com/openshift/release/pull/40726 is merged, can deploy operator bundle in cluster using
```
make deploy-bundle -e IMG=quay.io/opendatahub-operator:pr-264
```
> Determine install environment for operator

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- controllers/dscinitialization/dscinitialization_controller.go
> Fix rebase issues

- docs/Dev-Preview.md
> Update: correct channel name

- controllers/dscinitialization/monitoring.go
- get alert receiver's email from operator namepsace addon-managed-odh-parameters object
- replace both alert sender and receiver's email in manifests template 
Ref: https://github.com/opendatahub-io/opendatahub-operator/issues/252
>  Add SMTP sender and receiver email secrets

- main.go
> Add OauthClient resource to scheme

- Makefile
- apis/dscinitialization/v1alpha1/dscinitialization_types.go
- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
- config/manager/kustomization.yaml
- config/rbac/role.yaml
- controllers/dscinitialization/monitoring.go
- docs/Dev-Preview.md
> Update Operator Dev preview to v0.0.2

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/samples/dscinitialization_v1alpha1_dscinitialization.yaml
type of applicationNamespace has been changed from string array to string, sample need to update.
otherwise when user try to create their own, will have error from `Configure via:  Form view` have to fix it from  `Yaml view`
> Fix sample from string array to string

- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/samples/datasciencecluster_v1alpha1_datasciencecluster.yaml
- use profile none
- do not enable any component which might cause confusing when customer want o create instance manually
Ref: https://github.com/opendatahub-io/opendatahub-operator/issues/296
> Update sample config

- controllers/dscinitialization/utils.go
> Add odh-common-config Configmap

- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/monitoring.go
- main.go
Adding logging and raising events for error scenarios.
> Improving logging and eventing. #254

- Dockerfiles/Dockerfile
- Makefile
- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- docs/Dev-Preview.md
> Create new Dev preview version v0.0.3

- Makefile
- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> Create new Dev preview version v0.0.4

- components/modelmeshserving/modelmeshserving.go
> Add Modelmesh monitoring

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/default/kustomization.yaml
- config/manifests/kustomization.yaml
- config/prometheus/kustomization.yaml
- config/rbac/kustomization.yaml
- config/samples/datasciencecluster_v1alpha1_datasciencecluster.yaml
- config/samples/dscinitialization_v1alpha1_dscinitialization.yaml
- config/samples/kustomization.yaml
- config/scorecard/kustomization.yaml
- namespace to "opendatahub-system"
- sample name from "XXXX-sample" to "default" as per "feedback" doc
- remove "profile" in sample and add "kserve" and "codeflare"
- update last "patchesStrategicMerge" to "patches" ;  "vars" to "replacements"
> Update sample for new operator, default applicationNamespace and deprecated kustomize field

- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/utils.go
- docs/Dev-Preview.md
> Prepare for Dev Preview v0.0.5

- pkg/deploy/deploy.go
> Do not allow components to own applications Namespace

- controllers/dscinitialization/dscinitialization_controller.go
Adding refresh and retry logic in the DSCInitialization reconciliation loop to resolve errors and crashloop. #331
Manually tested on the cluster.
> Adding refresh and retry logic in the DSCInitialization reconciliation loop #331

- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
> Dev Preview release v0.0.6

- Makefile
- README.md
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- components/component.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/distributedworkloads/distributedworkloads.go
- components/kserve/kserve.go
- components/modelmeshserving/modelmeshserving.go
- components/workbenches/workbenches.go
- config/manager/kustomization.yaml
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/monitoring.go
- go.mod
- pkg/deploy/deploy.go
- pkg/plugins/addLabelsplugin.go
- tests/e2e/controller_setup_test.go
- tests/e2e/dsc_creation_test.go
- tests/e2e/dsc_deletion_test.go
- tests/e2e/helper_test.go
- tests/e2e/odh_manager_test.go
1. Testing steps:  https://github.com/opendatahub-io/opendatahub-operator/blob/3d53fece9b394fdb934145792795342ef3d3efb5/README.md#run-e2e-tests
2. Test Log:
```
make e2e-test
=== RUN   TestOdhOperator
=== RUN   TestOdhOperator/validate_operator_pod
=== RUN   TestOdhOperator/validate_operator_pod/Validate_ODH_Operator_pod
=== RUN   TestOdhOperator/validate_operator_pod/Validate_CRDs_owned_by_the_operator
=== RUN   TestOdhOperator/create
=== RUN   TestOdhOperator/create/e2e-test
=== RUN   TestOdhOperator/create/e2e-test/Creation_of_DataScienceCluster_instance
=== RUN   TestOdhOperator/create/e2e-test/Validate_deployed_applications
=== RUN   TestOdhOperator/create/e2e-test/Validate_Ownerrefrences_are_added
=== RUN   TestOdhOperator/create/e2e-test/Validate_Controller_Reverts_Updates
=== RUN …
```
> Add e2e test for operator

- docs/Dev-Preview.md
to fix https://github.com/opendatahub-io/opendatahub-operator/issues/335
> Doc: remove $ from copy section

- apis/datasciencecluster/v1alpha1/datasciencecluster_types.go
- apis/dscinitialization/v1alpha1/dscinitialization_types.go
- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- components/component.go
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Update: description of each field in spec from YAML view
before : 
install quay.io/wenzhou/opendatahub-operator-catalog:v0.0.74
after:
> Update description when create/config dsci and dsc

- Dockerfiles/Dockerfile
- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Fixes #311 
Release Bundle for ODH release 1.8
Channel : `fast`
Operator Version: v2.0.0
Manifest Version :  v1.8
**Note**: CSV image will be replaced in OperatorHub PR
1. E2e test job
2. Manifests will be tested once we have 1.8 version
> ODH Release bundle for v2.0.0

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Updates the deployment manifest for the ODH 1.8 release
Local deployment to verify functionality
No errors when deploying the test catalog
> Update for ODH 1.8 Release

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- bundle/manifests/opendatahub.io_odhdashboardconfigs.yaml
- config/crd/bases/odhdashboardconfigs.opendatahub.io_odhdashboardconfigs.yaml
- config/samples/opendatahub_v1alpha1_odhdashboardconfigs.yaml
ref: https://github.com/red-hat-data-services/odh-deployer/pull/368
change has been applied to rhods-operator repo
> Cherry-pick fix from odh-deployer

- components/component.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/distributedworkloads/distributedworkloads.go
- components/kserve/kserve.go
- components/modelmeshserving/modelmeshserving.go
- components/workbenches/workbenches.go
- pkg/deploy/deploy.go
Fixes #293 
1. Deploy test catalogsource
```
quay.io/vhire/opendatahub-operator-catalog:v2.0.1
```
2. Enable datascience pipelines component
3. Verify Datascience pipelines operator pod defines env variables added in the CSV file.
> Add support for image params for disconnected

- controllers/dscinitialization/utils.go
we do not create monitoring namespace but only application namespace
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/341
quay.io/wenzhou/opendatahub-operator-catalog:v0.0.64
> Add creation for monitoring namespace when it is not the same as applications'

- components/dashboard/dashboard.go
We do not need to add common apps explicitly, since they will be added as part of [overlays](https://github.com/red-hat-data-services/odh-manifests/blob/master/odh-dashboard/overlays/apps-onprem/kustomization.yaml#L7).
> Fix isv deployments

- components/dashboard/dashboard.go
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/monitoring.go
- controllers/dscinitialization/utils.go
- main.go
- pkg/common/common.go
- pkg/deploy/deploy.go
Fixes #250 
Add Dashboard specific config  before deploying the dashboard manifests
- Add dashboardconfig CR if doesn't exist
- Add admins user group if doesn't exist
> Add ODHDashboardconfig in dasboard component

- go.mod
- go.sum
- pkg/deploy/deploy.go
- pkg/plugins/addLabelsplugin.go
> Fix shared resources error

- components/modelmeshserving/modelmeshserving.go
seems this was done in downstream but not in upstream
https://github.com/red-hat-data-services/rhods-operator/pull/7
> [Cherry-pick]: Deploy modelmesh in monitoring namespace

- components/codeflare/codeflare.go
- components/ray/ray.go
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/384
ref: https://github.com/opendatahub-io/odh-manifests/pull/899
> Add ImageParams for kuberay and codeflare

- components/dashboard/dashboard.go
- pkg/plugins/addLabelsplugin.go
> Add Authentication overlay for dashboard

- components/dashboard/dashboard.go
> Allow multiple component names for Dashboard

- main.go
> DSCInit force update instances

- bundle/manifests/dashboard.opendatahub.io_odhapplications.yaml
- config/crd/bases/odhapplications.dashboard.opendatahub.io_odhapplications.yaml
> Revert changes to dashboard CRD

- pkg/plugins/namespacePlugin.go
> Expand namespace plugin to add MutatingWebhookConfiguration

- controllers/datasciencecluster/datasciencecluster_controller.go
Uncommenting Ray component after fix to the ray manifests. fixes #369
Tested manually in the cluster using the new ray manifest after the following fix:
https://github.com/opendatahub-io/distributed-workloads/commit/a65afe868c062d58fb910a8883fc423ee940889e
> Uncommenting Ray component after fix to the ray manifests. fixes #369

- components/dashboard/dashboard.go
- pkg/common/common.go
> Add support for anaconda resources

- components/dashboard/dashboard.go
- controllers/dscinitialization/dscinitialization_controller.go
- pkg/common/common.go
- pkg/deploy/deploy.go
> Update fixes for managed platform

- components/kserve/kserve.go
- pkg/plugins/namespacePlugin.go
> Update kserve configs

- components/kserve/kserve.go
Fixes #448 
Added `odh-model-controller` as a `dependentComponent` to `Kserve`. 
Deploys `odh-model-controller` if `Kserve` deploys successfully. 
- Tested on OSD 4.12
- Intended to be tested with [this PR to odh-manifests](https://github.com/opendatahub-io/odh-manifests/pull/912)
- Note: the odh-manifests PR is from the branch `odh-model-controller` but the testing branch for this PR in `odh-manifests` is `op2test`. This is because the testing branch deploys a custom odh-model-controller image that is not built in official sources yet. 
- deploy the operator using 
`make deploy -e IMG=quay.io/vedantm/opendatahub-operator:latest -e OPERATOR_NAMESPACE=opendatahub-operator-system` 
- Use the following DSCInit CR 
```
spec:
applicationsNamespace: opendatahub
manifestsUri: …
```
> add odh-model-controller with kserve

- components/workbenches/workbenches.go
- controllers/dscinitialization/dscinitialization_controller.go
> Move creation of notebooks namespace to workbenches

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/samples/dscinitialization_v1alpha1_dscinitialization.yaml
- to not confuse users who wants to manually create DSCI instance
> Fix: sample to use namespace opendatahub than opendatahub-system

- OWNERS
Remove Chris from the OWNERS file
> Removed cfchase from OWNERS

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/datasciencecluster_controller.go
see updates from https://github.com/opendatahub-io/odh-manifests/pull/918/files
> Add more permission for modelmesh

- components/codeflare/codeflare.go
- components/dashboard/dashboard.go
- components/kserve/kserve.go
- components/modelmeshserving/modelmeshserving.go
- components/ray/ray.go
- components/workbenches/workbenches.go
> Add pre config only when component is enabled

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Dev Catalog: quay.io/vhire/opendatahub-operator-catalog:v1.9.0
> ODH Release 1.9 for operator v1.9.0

- config/rbac/role.yaml
- controllers/datasciencecluster/datasciencecluster_controller.go
Otherwise operator constantly emits errors about those cluster roles missing
> fix(rbac): adds list role for configmaps and namespaces

- .github/ISSUE_TEMPLATE/bug_reportv2.md
- .github/issue_label_bot.yaml
- CONTRIBUTING.md
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/407
For the new issue template to work, need admin create new label "v1" "v2" first.
> Add contribution guidelines and new bug report for v2

- apis/datasciencecluster/v1/datasciencecluster_types.go
- apis/datasciencecluster/v1/groupversion_info.go
- apis/dscinitialization/v1/dscinitialization_types.go
- apis/dscinitialization/v1/groupversion_info.go
- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- components/codeflare/codeflare.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/modelmeshserving/modelmeshserving.go
- components/ray/ray.go
- components/workbenches/workbenches.go
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/secretgenerator/secretgenerator_controller.go
- controllers/status/status.go
- pkg/common/common.go
- pkg/deploy/deploy.go
- update for godoc
local run:
> godoc -http=:8080
> Docs: update godocs for synopsis and add function comments

- .github/workflows/sync_dashboard_crds.yaml
part of cherry-pick https://github.com/opendatahub-io/opendatahub-operator/pull/473 for v1.x operator
> [Cherry-pick]: Update GH action to filter out words when sync from dashboard CRD from v1.x

- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
- main.go
> Cleanup v1alpha1 of DSIC

- components/workbenches/workbenches.go
- controllers/dscinitialization/dscinitialization_controller.go
> Add path for managed version of Workbenches

- components/codeflare/codeflare.go
- components/dashboard/dashboard.go
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
> Fix issues introduced in dashboard and code flare

- components/README.md
- components/codeflare/codeflare.go
- components/component.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/modelmeshserving/modelmeshserving.go
- components/ray/ray.go
- components/workbenches/workbenches.go
- controllers/datasciencecluster/datasciencecluster_controller.go
This PR aims to simplify `Reconcile` functions used across components by removing unneeded parameters.
> chore: simplifies reconcile functions

- controllers/dscinitialization/utils.go
ref https://github.com/opendatahub-io/opendatahub-operator/issues/423
local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.9.423
> Update: networkpolicy for ODH created namespace

- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
> Update: change apigroup for codeflare and dsp

- get_all_manifests.sh
update dashboard default branch according to Andrew's comments in ADR
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/424
> Update dashboard default branch

- get_all_manifests.sh
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/424
related to https://github.com/opendatahub-io/opendatahub-operator/pull/544
for v1 we still need trusty manifests in operator image 
https://github.com/opendatahub-io/odh-manifests/blob/5e14d58bea5337f1c7b1a8ae48a1375ce2dc3105/kfdef/odh-core.yaml#L58
and update dashboard branch after Andrew's comments in ADR
> Trustyai manifests and dashboard branch

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
(cherry picked from commit 56d5cff5e9ccf7f4cf398b4a6a0205dcac05a83f)
> [odh-2.2.0] Add acceleratorprofiles from dashboard as new CRD

- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- get_all_manifests.sh
> ODH Release 1.10 for operator v2.2.0

- bundle/manifests/dashboard.opendatahub.io_acceleratorprofiles.yaml
- bundle/manifests/dashboard.opendatahub.io_odhapplications.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- bundle/manifests/opendatahub.io_odhdashboardconfigs.yaml
- config/crd/dashboard-crds/acceleratorprofiles.opendatahub.io.crd.yaml
- config/crd/dashboard-crds/odhdashboardconfigs.opendatahub.io.crd.yaml
- config/crd/kustomization.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
- get_all_manifests.sh
> ODH Release 1.10 for operator v1.10.0

- controllers/dscinitialization/monitoring.go
> Update common monitoring config

- Makefile
- README.md
- config/crd/external/operators.coreos.com_clusterserviceversions.yaml
- controllers/dscinitialization/dscinitialization_test.go
- controllers/dscinitialization/suite_test.go
- controllers/test/envtest_setup.go
Adding unit tests for the dsci initialization controller which solves the issue: #256 . 
For testing the PR
- cd into the `controllers/dscinitialization`
- run `ginkgo -v`
- to generate coverage-report run: `ginkgo -coverprofile=coverage.out & go tool cover -html=coverage.out`
> Add feature/functional tests in DSCInitialization

- Makefile
- README.md
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/crd/external/operators.coreos.com_clusterserviceversions.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
- controllers/dscinitialization/dscinitialization_test.go
- controllers/dscinitialization/monitoring.go
- controllers/dscinitialization/suite_test.go
- controllers/test/envtest_setup.go
cherry-pick commits have been merged into main to incubation.
after this, we should set incubation as default branch in this repo.
> [cherry-pick]: sync from main

- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
It seems we missed updating those together with linter fixes PR.
> fix(crds): updates docs after godoc fixes

- controllers/dscinitialization/dscinitialization_test.go
https://github.com/opendatahub-io/opendatahub-operator/pull/590#issuecomment-1745413169
> Enable test case after networkpolicy is added

- components/dashboard/dashboard.go
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
This PR extracts certain config/deployment work need for Dashboard to their own funcs for better readability.
`make test` + some manual testing as part of service-mesh work. Hoping for CI job to cover e2e here :)
> chore: organizes code in dashboard component

- .github/workflows/auto_add_issues.yaml
> Auto Add Issues to Tracking boards

- components/codeflare/codeflare.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/modelmeshserving/modelmeshserving.go
- components/ray/ray.go
- components/workbenches/workbenches.go
- add check on the replace image on the component level overwrite
> Add check on components devFlags to overwrite applyimageparams

- .github/workflows/auto_add_issues.yaml
> Fix autoadd issues workflow

- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
was spot in the midstream after copy from ODH, fix https://github.com/opendatahub-io/opendatahub-operator/pull/596
> fix(bundle): trustyai is missing in bundle and syntax error in manifests

- Makefile
- README.md
fix from https://github.com/opendatahub-io/opendatahub-operator/pull/564
> fix(make): test is renamed to unit-test

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
- get_all_manifests.sh
z-stream release for updating Notebooks manifests
Release tracker - https://github.com/opendatahub-io/opendatahub-community/issues/122
> ODH Release 1.10.1

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
- pkg/deploy/setup.go
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/357
> Use catalogsource to identify managed Platform

- Makefile
as discussed in the daily meeting, keep "test" and add "unit-test" as dependent target
> Add: test target depend on unit-test

- components/codeflare/codeflare.go
- get_all_manifests.sh
changes with new location of DW manifests:
- cf: https://github.com/opendatahub-io/codeflare-operator/pull/1
- cf: https://github.com/opendatahub-io/codeflare-operator/pull/8
part of : https://github.com/opendatahub-io/opendatahub-operator/issues/600
> update(cf): new path of manifests

- components/trustyai/trustyai.go
Current variable does not match downstream image substitutions
> Update TrustyAI Operator Variable

- pkg/upgrade/upgrade.go
ref: https://github.com/opendatahub-io/opendatahub-operator/pull/631#issuecomment-1778597523
local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.10.664
> add: check for if KfDef CRD already in the cluster

- controllers/datasciencecluster/datasciencecluster_controller.go
- user will be able to enable/disable component from Yaml view
> Update reconcile interval to half minute

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
- controllers/dscinitialization/utils.go
as part of https://github.com/red-hat-data-services/rhods-operator/pull/98
logic part will be added into https://github.com/opendatahub-io/opendatahub-operator/pull/618
> backport(2.4): add permission related to monitoring and missing label on namespaces

- README.md
- get_all_manifests.sh
> chore(script): removes unused vars

- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
- get_all_manifests.sh
This PR adds changes required for ODH 2.3 release
Test PR: https://github.com/opendatahub-io/opendatahub-operator/pull/685
> Add 2.3 ODH Release

- .github/workflows/unit-tests.yaml
> chore(gh): ensures unit-test action uses go.mod for Go version

- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
- get_all_manifests.sh
- keep same release tags from components
- DW still use branch since no tags ready, set commits in release note/blog
use https://github.com/opendatahub-io/opendatahub-operator/pull/697 for test, building images
> Release: ODH 2.4.0

- controllers/dscinitialization/utils.go
cherry-pick from https://github.com/opendatahub-io/opendatahub-operator/pull/700
> fix(namespace): for access dashboard

- components/modelmeshserving/modelmeshserving.go
- controllers/dscinitialization/utils.go
- get_all_manifests.sh
fix: https://github.com/opendatahub-io/opendatahub-operator/issues/670
only to remove the comments part, then we can sync to main and later to downstream for 2.5/1.36
> cleanup: modelmesh monitoring logic

- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
to make v1 for GA, update maturity from alpha to stable and set the starting version from 2.1 to 2.4
> release: uplift from alpha to stable and set 2.4 version

- pkg/feature/feature.go
> chore(log): accurate message

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- components/component.go
- config/rbac/role.yaml
- controllers/dscinitialization/monitoring.go
- controllers/dscinitialization/utils.go
- get_all_manifests.sh
- main.go
- downstream: remove legacy prometheus and blackbox for upgrade
- downstream: monitoring updates
ref:
https://github.com/red-hat-data-services/rhods-operator/pull/102
https://github.com/red-hat-data-services/rhods-operator/pull/107
https://github.com/red-hat-data-services/rhods-operator/pull/110
https://github.com/red-hat-data-services/rhods-operator/pull/111
> [backport]: monitoring fixes

- controllers/dscinitialization/monitoring.go
ref: https://github.com/red-hat-data-services/rhods-operator/pull/115
> [backport]: fix for monitoring

- pkg/feature/conditions.go
We don't have to see in logs that polling works.
> chore: removes log repetitions for conditions

- pkg/feature/templates/serverless/serving-install/knative-serving.tmpl
ref:  https://issues.redhat.com/browse/RHOAIENG-83
> update(knative): enable GPU node tolerations for kserve

- get_all_manifests.sh
Which is wiped out when script exits.
> chore: keeps repositories in the tmp dir

- components/component.go
- components/kserve/kserve.go
JIRA : https://issues.redhat.com/browse/RHOAIENG-98
backport from https://github.com/red-hat-data-services/rhods-operator/pull/145
this draft need to be rebased, some of the functions have been changed in downstream not in incubation yet.
> update(kserve): add monitoring logic

- components/kserve/kserve.go
- controllers/dscinitialization/servicemesh_setup.go
ref https://issues.redhat.com/browse/RHOAIENG-443
> feature: add support for unmanaged and remove for servicemesh and serverless

- OWNERS
Removing myself from the OWNERS file since I don't have recent knowledge of the v2.x code base
> Remove LaVLaS from the OWNERS file

- pkg/feature/builder.go
Refactors the code so that we can obtain interact with the cluster from partial builders instead of deferring it to the `Apply` phase.
> fix(builder): initializes rest config before invoking any partial builder

- tests/e2e/dsc_creation_test.go
ref: https://issues.redhat.com/browse/RHOAIENG-2219
> fix: fix e2e test error handling for RHOAIENG-2219

- go.mod
> revert go mod

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/samples/datasciencecluster_v1_datasciencecluster.yaml
- docs/DESIGN.md
- docs/Dev-Preview.md
- pkg/upgrade/upgrade.go
back pork https://github.com/red-hat-data-services/rhods-operator/pull/166 from downstream
jira:  https://issues.redhat.com/browse/RHOAIENG-2009
> [backport](trusty): set to GA

- components/codeflare/codeflare.go
Changed the variable name `odh-codeflare-operator-controller-image` to `codeflare-operator-controller-image`
Relates to: [PCF CFO #398](https://github.com/project-codeflare/codeflare-operator/pull/398)
> Changed variable name for cfo operator image

- components/codeflare/codeflare.go
- components/component.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/kserve/serverless_setup.go
- components/kueue/kueue.go
- components/modelmeshserving/modelmeshserving.go
- components/ray/ray.go
- components/workbenches/workbenches.go
- controllers/dscinitialization/servicemesh_setup.go
- controllers/secretgenerator/secretgenerator_controller.go
- pkg/deploy/deploy.go
- pkg/feature/builder.go
- pkg/upgrade/upgrade.go
- tests/envtestutil/cleaner.go
Spotted couple of typos so I thought I will just clean them up.
Though typos in comments indicate we have a bit copy-pastie in place :)
> chore: fixes typos in code and comments

- tests/envtestutil/name_gen.go
Instead of using our own random string generation, this PR relies on how k8s does it internally.
See https://github.com/kubernetes/apimachinery/blob/f14778da5523847e4c07346e3161a4b4f6c9186e/pkg/util/rand/rand.go#L98
> chore(test): simplifies name generations

- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
Missed as part of #839. I assumed it was part of the default target
> fix(crd): updates docs in crd

- components/kueue/kueue.go
ref: https://issues.redhat.com/browse/RHOAIENG-2498
internal conversation: https://redhat-internal.slack.com/archives/C05NXTEHLGY/p1707204182187849?thread_ts=1707200040.734719&cid=C05NXTEHLGY
need to sync to downstream and cherry-pick to 2.7 release branch
> fix(kueue): match var name from build system

- Makefile
- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
> Update manifests for odh 2.7

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
- get_all_manifests.sh
> Release: ODH 2.7

- .github/workflows/linter.yaml
https://github.com/opendatahub-io/opendatahub-operator/pull/864#discussion_r1489064260
> update(GH): enabled PR comments by linter bot

- controllers/dscinitialization/utils.go
ref: https://issues.redhat.com/browse/RHOAIENG-3116
live build:  quay.io/wenzhou/opendatahub-operator-catalog:v2.8.3116
> feat(nwp): add ingress from cluster-monitoring to applicationnamespace

- components/modelregistry/modelregistry.go
change for https://gitlab.cee.redhat.com/data-hub/rhods-cpaas-midstream/-/merge_requests/1661
> update(modelregistry): rename image name

- Makefile
- bundle/manifests/opendatahub-operator-webhook-service_v1_service.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
> ODH Release 2.8 Version Update

- get_all_manifests.sh
> Release ODH 2.8

- pkg/upgrade/upgrade.go
Reverts opendatahub-io/opendatahub-operator#822
> Revert "RHOAIENG-965: Fix ODH Upgrade after label updates"

- pkg/deploy/deploy.go
- pkg/deploy/setup.go
- pkg/upgrade/upgrade.go
- tests/e2e/dsc_cfmap_deletion_test.go
- cleanup commented out code
- rename function
- cleanup unnecessary sleep
ref: https://github.com/opendatahub-io/opendatahub-operator/pull/796
> chore: follow up review comments from previous PR

- components/dashboard/dashboard.go
to work with changes from https://github.com/opendatahub-io/odh-dashboard/pull/2563, we use the old way to apply odhdashboardconfig
ref: https://issues.redhat.com/browse/RHOAIENG-4159
backport from downstream 2.8 https://github.com/red-hat-data-services/rhods-operator/pull/210
> [backport](dashboard): to work with new struct from dashboard

- apis/datasciencecluster/v1/datasciencecluster_types.go
- controllers/datasciencecluster/datasciencecluster_controller.go
Factor out getAllComponents() and make it as a public DataScienceCluster method.
This allows to reuse it in the testing code.
There is no functionality change, so building and passing e2e tests is enough.
> DSC: make a method from getAllComponents

- pkg/trustedcabundle/trustedcabundle.go
ref: https://issues.redhat.com/browse/RHOAIENG-4233 
live build quay.io/wenzhou/opendatahub-operator-catalog:v2.9.4233-1
> fix(trustbundle): do not use namespace which is in termination status

- Makefile
We have missed a few tests because of that...
> fix(make): adds entire pkg/... to run tests

- Makefile
- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
> ODH Release 2.9: Version Update

- get_all_manifests.sh
- pkg/upgrade/upgrade.go
> ODH Release 2.9

- pkg/deploy/deploy.go
- pkg/upgrade/upgrade.go
backport: https://github.com/red-hat-data-services/rhods-operator/pull/224
ref:  https://issues.redhat.com/browse/RHOAIENG-3963
> fix(dashboard): do not set owner on CR

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/samples/datasciencecluster_v1_datasciencecluster.yaml
- pkg/upgrade/upgrade.go
- tests/e2e/helper_test.go
ref: https://issues.redhat.com/browse/RHOAIENG-4666
> feat(DW): prepare CF,ray,kueue for GA

- get_all_manifests.sh
odh-model-controller has a new incubating branch so this pr updates the branch name for nightly build.
> update branch of odh-model-controller for nightly build

- pkg/trustedcabundle/trustedcabundle.go
> Fix update on trustedcabundle

- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
> Release 2.10: Update version

- get_all_manifests.sh
(cherry picked from commit 2fb24a628907ceab3eced8e1645a932203b6b97a)
> ODH 2.10 Release

- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
> Release v2.10.1: version update

- controllers/datasciencecluster/datasciencecluster_controller.go
- DSCI creation should trigger watches() and reconcile DSC
could have the logic in the same `watchDataScienceClusterResources`()
but think it would be more clear to have one dedicated for DSCI case
before
- install operator
- create DSC CR(d not create DSCI CR)
- DSC CR phase is Error
- create DSCI CR
- nothing happened
- delete DSC CR
- re-create DSC CR
- start to reconcile Managed Components
now
- install operator
- create DSC CR (do not create DSCI)
- DSC CR got phase "Error" and no component should be deployed regardless ManagementStates
- Create DSCI CR
- DSC CR start to deploy Managed Component when all in ReconcileCompleted it gets Ready as phase
-
> fix(DSC): when DSC is in Error because of missing DSCI CR

- pkg/cluster/resources.go
Removes nested ifs in favor of error "type" checks.
> chore: simplifies CreateNamespace logic

- pkg/upgrade/upgrade.go
backport https://github.com/red-hat-data-services/rhods-operator/pull/246
ref :https://issues.redhat.com/browse/RHOAIENG-5514
> [backport] ray: Cleanup opendatahub Namespace

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
> Version update for odh 2.11

- main.go
hard to know what user is doing in the cluster if they are running for Managed cluster but no DSCI CR gets auto created. 
just a bit more info to help debug
thread: https://redhat-internal.slack.com/archives/C064Z5S84F3/p1713957713956549?thread_ts=1713950565.201169&cid=C064Z5S84F3
> chore: better debug info + a clear check on env variable DISABLE_DSC_CONFIG

- components/codeflare/codeflare.go
- main.go
- remove check on CFO name: it was different but now only use one name
- add operator namespace into configmapcontroller
> chore: remove CFO name check for downstream

- README.md
- components/component.go
- controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
- main.go
- pkg/common/common.go
- pkg/logger/logger.go
a dedicated package
- move ConfigLoggers()  from common to new logger package
- add new function to convert log-mode string to int for V().
- update README with more detail
> chore(logger): pass log-mode to each controller and move function to

- controllers/dscinitialization/feature_resources.go
> chore(docs): fix comments

- Dockerfiles/Dockerfile
ref: https://issues.redhat.com/browse/RHOAIENG-6814
> feat(fips): enable GO_ENABLED in build

- pkg/deploy/deploy.go
https://github.com/red-hat-data-services/rhods-operator/pull/261
ref:   https://issues.redhat.com/browse/RHOAIENG-6989
see original PR for test
see original PR for test
> [backport]: modelserving skip reconcile on deployment resources

- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Update version for ODH release.
> Update version to v2.12.0

- pkg/feature/builder.go
As the first step of improving Feature DSL this PR brings godoc explaining purpose of each method in the builder chain.
It's only `godoc` changes + shuffling methods around, not sure have something to test here.
> chore: adds godoc to Feature builder

- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
> Update version to v2.12.1

- pkg/cluster/const.go
This is a followup to https://github.com/opendatahub-io/opendatahub-operator/pull/981
> Fix CSV name for RHOAI

- tests/e2e/dsc_deletion_test.go
Use the same logic as for creation to speed up a bit.
> tests: e2e: run components deletion as separate parallel tests

- get_all_manifests.sh
* ModelMesh new incubation branch is now `release-v0.12.0-rc0`
* KServe new incubation branch is now `release-v0.12.1`.
Running the modified script manually and ensuring it downloads the manifests correctly.
> chore: Update model serving incubation branches (manifests)

- Dockerfiles/bundle.Dockerfile
- Makefile
- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
> Update version 2.13

- pkg/feature/servicemesh/conditions.go
local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.10.61
> fix: missing label "opendatahub.io/generated-namespace" on auth namespace

- OWNERS
- OWNERS_ALIASES
This PR updates the owners-aliases list in the repository with the Github ID's of new members in the team
> Update Owners-aliases list

- .github/PULL_REQUEST_TEMPLATE.md
This PR updates the PR template in this repository with some pre-requisites and checks.
JIRA: https://issues.redhat.com/browse/RHOAIENG-5426
> RHOAIENG-5426: Updated pull request template with prerequisites

- pkg/cluster/cluster_config.go
- pkg/cluster/const.go
Jira: https://issues.redhat.com/browse/RHOAIENG-8497
- tune managed/selfmanaged user facing name
- cluster: rename isXManaged to detectX
> cluster: platform name cleanup

- pkg/deploy/deploy.go
- pkg/plugins/addLabelsplugin.go
- pkg/plugins/namespacePlugin.go
The actual use with resMap is inlined and moved to the caller.
This way we can construct plugins on demand and use them as building blocks instead.
> chore: funcs to create kustomize plugins

- .github/PULL_REQUEST_TEMPLATE.md
- hides "thank you message" in the comment
- combines two checklists into one
- removed ":" from the headers to make them consistent
N/A
N/A
N/A
> chore: improves PR template

- pkg/cluster/cluster_operations_int_test.go
- pkg/cluster/cluster_operations_suite_int_test.go
- pkg/cluster/meta.go
- pkg/cluster/resources.go
Adds new setter functions for manipulating MetaObject.
> [!NOTE]
> It is stacked PR coming from the ongoing authz work.
> feat(meta): adds InNamespace and WithAnnotation setter funcs

- .gitignore
seems some IDE would auto checkin files or maybe a "git add ." does so, but `config/manager/kustomization.yaml `is not intended to be store in git repo
> chore: exclude file which auto-gen by "make" checkin

- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
https://github.com/opendatahub-io/opendatahub-community/issues/153
> Update version to 2.14.0

- OWNERS
- OWNERS_ALIASES
**wait till lburgazzoli get into org before merge it**
> chore: update owner list

- pkg/cluster/const.go
This PR amends the `release.name` according to https://docs.redhat.com/en/documentation/red_hat_openshift_ai/2024, see https://issues.redhat.com/browse/RHOAIENG-9326
I've deployed the operator in my OpenShift instance, however since it is not a managed nor a a product version, I was unable to actually test the change beside ensuring the operator does not fail.
> Update release.name from DSC and DSCI

- tests/e2e/dsc_creation_test.go
> test: fix wrong test case for the cert type

- pkg/feature/manifest.go
- pkg/feature/types.go
`ReplaceChar` is not used anywhere in the templates, so there is no point in keeping it around.
Most likely spillover from infamous #605.
Just by running `make` - it's dead code not used anywhere.
> chore(feature): removes unused tmpl func

- pkg/deploy/deploy.go
ref: https://github.com/red-hat-data-services/rhods-operator/pull/277/commits/59f8092bc9e1ba75ada0a8194dcb25fb0e7509ed
> backport: fix of annotation on kserve

- pkg/feature/README.md
Accidentally commited while trying to improve mermaid `note` in "class diagram".
> docs: removes not working styling

- pkg/feature/raw_resources.go
`raw_resources.go` originally came from kfdef plugin version, where the code was based on [`k8utils.go`](https://github.com/opendatahub-io/opendatahub-operator/blob/700b23aa37fc88f3284eb595f7a838e6fafd59f0/pkg/utils/k8utils.go#L90) attributed to Bitnami.
Since then code has been entirely rewritten, so this license header is not relevant anymore. This commit removes it.
> chore: removes obsolete attribution

- controllers/datasciencecluster/datasciencecluster_controller.go
Just a little nits found during working on something else.
> chore: fixes typos

- pkg/cluster/cluster_config.go
- pkg/cluster/resources.go
- pkg/trustedcabundle/trustedcabundle.go
- add support for pagination for List CSV and NS
- move function into cluster package
ref: https://issues.redhat.com/browse/RHOAIENG-8483
> feat: add chunksize for List operation with pagination

- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
> Update version to 2.15

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
To ensure your [OpenShift compatibility statements](https://docs.openshift.com/container-platform/4.16/operators/operator_sdk/osdk-working-bundle-images.html#osdk-control-compat_osdk-working-bundle-images) match your Kubernetes compatibility statements ([.spec.minKubeVersion](http://.spec.minkubeversion/)) in your Operator's metadata
Map between OCP version vs Vanilla k8s version
https://access.redhat.com/solutions/4870701
|OpenShift Version|	Kubernetes Version|
| -------- | ------- |
|4.16|	1.29|
| 4.15	|1.28|
|4.14|	1.27|
|4.13|	1.26|
|4.12	|1.25|
> chore: update min k8s version to match min ocp version: 1.25 for 4.12

- pkg/deploy/deploy.go
- pkg/plugins/removerplugin.go
- tests/e2e/dsc_creation_test.go
- use AllowList instead of WhiteList
https://issues.redhat.com/browse/RHOAIENG-7297
> chore: rename variable/function name

- .github/scripts/wait-for-checks.sh
Increase timeout for the wait-for-checks.sh script.
Increase timeout for the wait-for-checks.sh script as it takes some time for gh to spin up the checks/prow jobs.
> (chore): Increase timeout for the wait-for-checks.sh script

- .github/workflows/pre-release.yaml
Commenting the 'push version tag to quay.io' step in gh action because this will need verification from DevOps if we have enough rights to push to quay-odh repo.
Commenting the 'push version tag to quay.io' step in gh action because this will need verification from DevOps if we have enough rights to push to quay-odh repo.
> (chore): Comment the 'push version tag to quay.io' step in gh action

- Makefile
Signed-off-by: Luca Burgazzoli <lburgazzoli@gmail.com>
> set devel log mode when running the operator locally

- pkg/deploy/envParams.go
Use traditional UNIX pattern of writing to a temporary file and
renaming it to the original one instead of modifying inplace.
Rename operation is atomic.
It also fixes previous code for handling unclosed files on the
filesystem (it used defer to close them on exit of the function).
Signed-off-by: Yauheni Kaliuta <ykaliuta@redhat.com>
> deploy: ApplyParams: rewrite with tempfile

- .golangci.yml
- controllers/dscinitialization/suite_test.go
- main.go
> chore: update alias across code base and set in golint

- Makefile
follow up: https://github.com/opendatahub-io/opendatahub-operator/pull/1201#discussion_r1727172888
> test: add operator namespace variable for unit-test

- components/modelregistry/modelregistry.go
- tests/e2e/dsc_creation_test.go
Add default cert for model registry in a secret named default-modelregistry-cert in the control plane namespace
Fixes RHOAIENG-9909
Added e2e tests to verify that the secret was created
> feat: add default cert for model registry, fixes RHOAIENG-9909

- README.md
- docs/DESIGN.md
- docs/troubleshooting.md
- docs/upgrade-testing.md
- update path for "manifests"
- add new troubleshooting knowledge
- update default component lists
> docs: update old docs

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/samples/datasciencecluster_v1_datasciencecluster.yaml
- pkg/upgrade/upgrade.go
- KFTO has been out in ODH for a while but default still Removed
- ModelReg need to prepare as Managed in ODH for downstream inclusion
> feat: set ModelReg and KFTO default to Managed in ODH

- tests/e2e/cfmap_deletion_test.go
- tests/e2e/controller_test.go
- tests/e2e/creation_test.go
- tests/e2e/deletion_test.go
- tests/e2e/helper_test.go
- tests/e2e/odh_manager_test.go
- rename files
- add check on FTer CRD
- use label from labels.ODHAppPrefix
- update misleading log message
- re-order test cases
- rename DSC CR from e2e-test to e2e-test-dsc
> test: update e2e testcases

- tests/e2e/helper_test.go
- we have capability of having modelserving and kserve both managed
- this will cover the same we have shared labels
> tests: enabled modelserving as Managed

- components/trustyai/trustyai.go
- trustyai has introduced overlays for odh and rhoai
- we can switch to use these than base
https://issues.redhat.com/browse/RHOAIENG-12277
> feat: enable trustyai to use different manifests path

- OWNERS_ALIASES
Add StevenTobin to owners file.
> add StevenTobin to owners

- bundle/manifests/opendatahub-operator-webhook-service_v1_service.yaml
- config/webhook/kustomizeconfig.yaml
- config/webhook/service.yaml
- rename serving certificates secret
- remove MutatingWebhookConfiguration references from kustomization
- remove autogenerated misleading labels
> Webhook config cleanup

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
- fix DW, should not using -
- add ModelReg and Trustyai
> chore: update release keywords

- pkg/cluster/cert.go
Passing name and namespace is redundant, as it is always the same as newSecret passed to this func as well.
This change simplifies the function signature and uses `client.ObjectKeyFromObject` utility function to fetch existing secret instance from the cluster.
In addition,  error variables have been renamed to avoid shadowing.
> chore: simplifies generateCertSecret func

- pkg/cluster/cert.go
- no need to add ingresscontroller into runtime again
- it has been handled in main.go https://github.com/opendatahub-io/opendatahub-operator/blob/fde5d697de4304941347a4f24d287d60b3f2a52c/main.go#L101
> chore: cleanup code

- tests/e2e/helper_test.go
- till we can have KFTO image moved away from docker.io, keep this component to Removed
- hit too many times in e2e with" rate limits"
> test: disable KFTO in e2e

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
- trustyai is not needed, has been tested in downstream
- crd has been covered by group apiextensions.k8s.io
- we do not need addons.managed.openshift.io for checking managed offerings
local build: quay.io/wenzhou/opendatahub-operator-bundle:v2.18.918
- create dsci and dsc
- enable dashboard and trusty,  can login dashboard, and no error in operator pod log
> chore: cleanup unnecessary permisison

- OWNERS_ALIASES
Fixed name for me in the owners file
> Fixed typo for jackdelahunt owner

- apis/dscinitialization/v1/dscinitialization_types.go
- bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
- docs/api-overview.md
similar to https://github.com/opendatahub-io/opendatahub-operator/pull/1261 but this is on DSCI
> update: add validation on application and monitoring namespace in DSCI

- components/codeflare/codeflare.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/kueue/kueue.go
- components/modelmeshserving/modelmeshserving.go
- components/modelregistry/modelregistry.go
- components/ray/ray.go
- components/trainingoperator/trainingoperator.go
- components/trustyai/trustyai.go
- components/workbenches/workbenches.go
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/utils.go
- main.go
- pkg/cluster/cluster_config.go
- pkg/cluster/const.go
- pkg/upgrade/uninstallation.go
- pkg/upgrade/upgrade.go
cherrypick from https://github.com/opendatahub-io/opendatahub-operator/pull/1277
https://issues.redhat.com/browse/RHOAIENG-9642
> update: rename variables rhods to rhoai

- .github/workflows/linter.yaml
- Makefile
- controllers/dscinitialization/suite_test.go
- controllers/webhook/webhook_suite_test.go
- pkg/logger/logger.go
- **chore(linter): update golangci-lint to v1.61.0**
- **chore(linter): fix findings**
> update golangci-lint to v1.61.0

- pkg/controller/types/types.go
-------
I haven't used this yet, but I _think_ it's more correct this way?
> chore: Join path if NOT empty string

- components/modelmeshserving/modelmeshserving.go
- this only apply for map `dependentImageParamMap` with odh-model-controller
- no need to set it in the default `imageParamMap`, just a  waste
> chore: remove duplicated image in modelmesh

- controllers/components/dashboard/dashboard_controller.go
- controllers/components/modelregistry/modelregistry_controller.go
- controllers/components/ray/ray_controller.go
- pkg/controller/reconciler/component_reconciler.go
- pkg/controller/reconciler/component_reconciler_support.go
> Remove generics for ComponentReconciler and ComponentReconcilerBuilder

- components/kserve/kserve.go
- config/rbac/role_binding.yaml
- docs/api-overview.md
- tests/e2e/odh_manager_test.go
small chore to test if auto-sync is working now
> chore: cleanup

- .github/workflows/linter.yaml
- .github/workflows/unit-tests.yaml
- .gitignore
- bundle/manifests/rhods-operator.clusterserviceversion.yaml
- components/kserve/kserve.go
- config/rbac/role_binding.yaml
- controllers/dscinitialization/suite_test.go
- controllers/webhook/webhook_suite_test.go
- tests/e2e/odh_manager_test.go
```
git merge --no-edit origin/main
Auto-merging config/manager/kustomization.yaml
CONFLICT (rename involved in collision): rename of config/manager/kustomization.yaml -> config/manager/kustomization.yaml.in has content conflicts AND collides with another path; this may result in nested conflict markers.
Merge made by the 'ort' strategy.
.github/renovate.json                                 |  27 +++++++++++++++++++++++++++
.github/workflows/bundle-sync.yml                     |  66 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.github/workflows/operator-insta-merge.yaml           | 104 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.github/workflows/operator-processor.yaml             | 153 …
```
> fix: auto-sync with conflict

- controllers/components/dashboard/dashboard_controller.go
- controllers/components/dashboard/dashboard_controller_actions.go
- controllers/components/dashboard/dashboard_support.go
- pkg/cluster/gvk/gvk.go
- pkg/cluster/resources.go
- pkg/controller/actions/security/actions.go
- pkg/controller/actions/security/actions_test.go
- pkg/utils/test/fakeclient/fakeclient.go
> Add a reusable update-pod-security-action

- pkg/controller/actions/deploy/action_deploy.go
> Fix deployment cache action

- pkg/cluster/cluster_config.go
wrongly introduced from https://github.com/opendatahub-io/opendatahub-operator/pull/1313/files#diff-3bd42200a1af1b71af4626a7e6092cbaccf8a382fef07fa34119595c7b09f2f4
https://issues.redhat.com/browse/RHOAIENG-15616
> fix: wrong name of variable and func lead to always return self-managed

- controllers/components/trustyai/trustyai_controller.go
> Enable deployment cache on the TrustyAI component

- OWNERS_ALIASES
> update: owners

- .github/workflows/unit-tests.yaml
This update is needed for Codecov to upload the missing BASE report and compare it.
Currently, we face this error in unit-tests workflow.
```
error - 2024-11-18 12:54:19,831 -- Report creating failed: {"message":"Token required because branch is protected"}
==> Running command '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov do-upload'
/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov do-upload --git-service github
info - 2024-11-18 12:54:20,560 -- ci service found: github-actions
warning - 2024-11-18 12:54:20,568 -- No config file could be found. Ignoring config.
warning - 2024-11-18 12:54:20,569 -- xcrun is not installed or can't be found.
warning - 2024-11-18 12:54:20,574 -- No gcov data found.
warning - 2024-11-18 12:54:20,575 -- coverage.py is not …
```
> Updated codecov version to 4.6.0

- .github/workflows/unit-tests.yaml
> Backport changes on unit-tests.yaml to rhoai branch

- bundle/manifests/components.opendatahub.io_codeflares.yaml
related to https://github.com/opendatahub-io/opendatahub-operator/pull/1387
> fix: codeflare missing bundle

- OWNERS_ALIASES
Remove adelton from the platform owners list.
Not tested.
> Remove adelton from the platform owners list.

- controllers/components/dashboard/dashboard_controller_actions.go
- controllers/components/modelregistry/modelregistry_controller_actions.go
- controllers/components/workbenches/workbenches_controller_actions.go
- pkg/controller/types/types.go
- pkg/controller/types/types_test.go
- pkg/resources/resources.go
> Add reusable functions to add/remove/update ReconciliationRequest.Resources

- README.md
The intention in the examples is to override make variables which is done with setting the variable in the command line, while -e switch does not get argument and changes make to a mode when environment takes precedence over makefile settings[1][2]
Short examples:
```
% cat Makefile
VAR = var
DEFVAR ?= defvar
all:
@echo "VAR $(VAR), origin $(origin VAR)"
@echo "DEFVAR $(DEFVAR), origin $(origin DEFVAR)"
% make
VAR var, origin file
DEFVAR defvar, origin file
% make VAR=cmd DEFVAR=cmd
VAR cmd, origin command line
DEFVAR cmd, origin command line
% VAR=env DEFVAR=env make
VAR var, origin file
DEFVAR env, origin environment
% VAR=env DEFVAR=env make -e
VAR env, origin environment override
DEFVAR env, origin environment
% VAR=env DEFVAR=env make -e VAR=cmd DEFVAR=cmd
VAR cmd, origin command …
```
> doc: remove -e from make invocation examples

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/components/codeflare/codeflare_controller.go
- controllers/components/dashboard/dashboard_controller.go
- controllers/components/datasciencepipelines/datasciencepipelines.go
- controllers/components/datasciencepipelines/datasciencepipelines_controller.go
- controllers/components/kserve/kserve_controller.go
- controllers/components/kueue/kueue_controller.go
- controllers/components/modelregistry/modelregistry_controller.go
- controllers/components/ray/ray_controller.go
- controllers/components/trainingoperator/trainingoperator_controller.go
- controllers/components/trustyai/trustyai_controller.go
- controllers/components/workbenches/workbenches_controller.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/datasciencecluster/kubebuilder_rbac.go
- pkg/controller/actions/deploy/action_deploy.go
- pkg/controller/actions/deploy/action_deploy_cache.go
- pkg/controller/actions/deploy/action_deploy_test.go
- pkg/controller/predicates/component/component.go
- pkg/metadata/labels/types.go
- pkg/resources/resources.go
- pkg/resources/resources_test.go
- tests/e2e/controller_test.go
- tests/e2e/dashboard_test.go
- tests/e2e/modelregistry_test.go
The CRDs are meant to be left in the cluster, so they are not tight to
components' lifecycle hence, CRDs requires some custom handling so the
metadata is not cluttered by useless component/platform annotations and
labels.
As a conseguence, the each component has to set-up a dedicated handler
and predicate in order to mape and filter out relevant CRDs events.
> Add custom CRD deployment logic

- main.go
cherry-pick change from https://github.com/opendatahub-io/opendatahub-operator/pull/1270/
we do not watch deployment in modelreg namespace, no need to cache in operator
> update: remove cache for deployment in modelreg namespace

- README.md
As noted in [this PR](https://github.com/opendatahub-io/opendatahub-operator/pull/844), the IMAGE_OWNER variable has been removed. This PR updates the README file to reflect that change accordingly.
> Removed IMAGE_OWNER from README.md.

- controllers/components/codeflare/codeflare.go
- controllers/components/codeflare/codeflare_controller_actions.go
- controllers/components/codeflare/codeflare_support.go
- controllers/components/datasciencepipelines/datasciencepipelines.go
- controllers/components/datasciencepipelines/datasciencepipelines_controller.go
- controllers/components/datasciencepipelines/datasciencepipelines_controller_actions.go
- controllers/components/datasciencepipelines/datasciencepipelines_support.go
- controllers/components/kserve/kserve.go
- controllers/components/kserve/kserve_controller.go
- controllers/components/kserve/kserve_support.go
- controllers/components/kueue/kueue.go
- controllers/components/kueue/kueue_controller_actions.go
- controllers/components/kueue/kueue_support.go
- controllers/components/modelcontroller/modelcontroller.go
- controllers/components/modelcontroller/modelcontroller_actions.go
- controllers/components/modelcontroller/modelcontroller_support.go
- controllers/components/modelmeshserving/modelmeshserving.go
- controllers/components/modelmeshserving/modelmeshserving_actions.go
- controllers/components/modelmeshserving/modelmeshserving_support.go
- controllers/components/ray/ray.go
- controllers/components/ray/ray_controller_actions.go
- controllers/components/ray/ray_support.go
- controllers/components/trainingoperator/trainingoperator.go
- controllers/components/trainingoperator/trainingoperator_controller_actions.go
- controllers/components/trainingoperator/trainingoperator_support.go
- controllers/components/trustyai/trustyai.go
- controllers/components/trustyai/trustyai_controller_actions.go
- controllers/components/trustyai/trustyai_support.go
- pkg/controller/types/types.go
- **Refactor ManifestInfo**
- **Fix codeflare**
- **Fix datasciencepipelines**
- **Fix kserve**
- **Fix kueue**
- **Fix modelcontroller**
- **Fix ray**
- **Fix trainingoperator**
- **Fix trustyai**
- **Fix modelmeshserving**
> Fix manifests paths across components

- pkg/upgrade/upgrade.go
I noticed my typo while digging through some logs.
We clean the validation result configmap, not the data one.
> chore: fixed typo in the logs

- controllers/components/kserve/kserve_controller_actions.go
- controllers/components/modelcontroller/modelcontroller_actions.go
- controllers/components/modelmeshserving/modelmeshserving_actions.go
> Use both current and legacy component name to filter out DevFlags

- .github/workflows/pre-release.yaml
- OWNERS_ALIASES
- README.md
https://github.com/opendatahub-io/opendatahub-operator/pull/1444
https://github.com/opendatahub-io/opendatahub-operator/pull/1459
https://github.com/opendatahub-io/opendatahub-operator/pull/1448
> [sync] chore changes from main branch

- main.go
sync PR https://github.com/opendatahub-io/opendatahub-operator/pull/1426
> [sync] update: remove cache for deployment in modelreg ns

- .golangci.yml
- Makefile
- controllers/datasciencecluster/datasciencecluster_controller.go
- pkg/controller/actions/deploy/action_deploy_merge_deployment.go
- pkg/controller/actions/render/template/action_render_templates.go
- pkg/controller/reconciler/reconciler_support.go
- pkg/deploy/deploy.go
- pkg/feature/servicemesh/conditions.go
- pkg/manifests/kustomize/kustomize_engine.go
- pkg/resources/resources.go
- pkg/services/gc/gc_support.go
- tests/e2e/controller_test.go
- tests/e2e/helper_test.go
- **Update golangci-lint to v1.63.4**
- **Update golangci-lint configuration to remove deprecated linters**
- **Fix linter findings**
> Update golangci-lint to v1.63.4

- pkg/controller/client/client.go
> Improve operator's client SSA error handling

- tests/e2e/creation_test.go
- tests/e2e/helper_test.go
This PR is intended to include e2e tests for the trusted CA bundle feature.
JIRA issue: https://issues.redhat.com/browse/RHOAIENG-3924
> tests: e2e test for trusted-ca-bundle

- controllers/services/auth/resources/admingroup-clusterrole.tmpl.yaml
- controllers/services/auth/resources/admingroup-role.tmpl.yaml
Add clusterroles/roles for admin users.
Note: this is a part of the admin permissions work.
JIRA: https://issues.redhat.com/browse/RHOAIENG-14235
> (feat): Add roles and cluster roles for admingroups

- pkg/utils/test/matchers/jq/jq_support_test.go
Improve unit tests for jq's toType and byteToType
- Refactor the toType test to handle more cases
- Add additional cases to toTypes test
- Add a specific test for byteToType
> Improve unit tests for jq's toType and byteToType

- controllers/services/auth/resources/admingroup-clusterrole.tmpl.yaml
Fix a typo in admin permissions cluster role.
> (fix): Typo in clusterrole for admin users

- controllers/components/kueue/kueue_controller.go
- tests/e2e/kueue_test.go
> Fix kueue watch event handler for CRDs

- controllers/components/kueue/kueue_controller.go
- tests/e2e/kueue_test.go
cherry pick from main 2cbb6277
> [rhoai] Fix kueue watch event handler for CRDs (#1529)

- controllers/status/status.go
> chore: remove unused structs and functions from controlelrs/status package

- main.go
https://issues.redhat.com/browse/RHOAIENG-18607
> fix: missing monitoring NS for NWP if user opt-in customized app NS

- main.go
(cherry picked from commit 63d4eaba75b1c4b9092b0a30b349e5e73e2e3d4a)
https://issues.redhat.com/browse/RHOAIENG-18607
> [sync]fix: missing monitoring NS for NWP if user opt customized app NS (#1558)

- main.go
- remove subs from client cache
- add smcp into exclude cache
(cherry picked from commit bc63cfdf1d120eb015ee53223b26fb86e0939cc2)
https://issues.redhat.com/browse/RHOAIENG-18425
> [sync]update: change previous workaround for subscription and add smcp in the list (#1557)

- Dockerfiles/Dockerfile
This will ensure the dockefile can be built using the docker build, this Dockerfile directly can be used in the Konflux environment to build the image multi-arch
> Build platform independent binary based on the target platform

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
`{"level":"error","ts":"2025-01-27T10:37:10Z","msg":"Reconciler error","controller":"workbenches","controllerGroup":"components.platform.opendatahub.io","controllerKind":"Workbenches","Workbenches":{"name":"default-workbenches"},"namespace":"","name":"default-workbenches","reconcileID":"94477b8b-2ba0-4557-a7d7-b77085bf27b6","error":"failed to remove owner references from object redhat-ods-applications/rstudio-server-rhel9 with gvk build.openshift.io/v1, Kind=BuildConfig: buildconfigs.build.openshift.io \"rstudio-server-rhel9\" is forbidden: User \"system:serviceaccount:redhat-ods-operator:redhat-ods-operator-controller-manager\" cannot update resource \"buildconfigs\" in API group \"build.openshift.io\" in the namespace \"redhat-ods-applications\"","stacktrace":"sigs.k8s.io/controller-runt …
> fix: for upgrade case we will need update permission on buildconfig to remove old DSC as ownerref

- README.md
- controllers/dscinitialization/utils.go
- docs/troubleshooting.md
- update README and troubleshooting
(cherry picked from commit a00aa618d69e3fabc62f204e046c67824698cec2)
> [sync]fix: add matchlabel on NWP for customized appliation (#1566)

- README.md
Point to correct file path for component integration hyperlink.
> (fix): point to correct path for component integration doc

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
- add update on all cases
`{"level":"error","ts":"2025-01-28T14:52:45Z","msg":"Failed to execute action","controller":"dashboard","controllerGroup":"components.platform.opendatahub.io","controllerKind":"Dashboard","Dashboard":{"name":"default-dashboard"},"namespace":"","name":"default-dashboard","reconcileID":"ac520c24-c0ea-4a95-bb48-fa7882c5ec10","action":"github.com/opendatahub-io/opendatahub-operator/v2/pkg/controller/actions/deploy.(*Action).run-fm","error":"failed to remove owner references from object redhat-ods-applications/create-jupyter-notebook with gvk console.openshift.io/v1, Kind=OdhQuickStart: odhquickstarts.console.openshift.io \"create-jupyter-notebook\" is forbidden: User \"system:serviceaccount:redhat-ods-operator:redhat-ods-operator-controller-manager\" cannot update …
> fix: missing update permission on dashboard object during upgrade from old version to new refactor

- bundle/manifests/rhods-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
- add update on all cases
(cherry picked from commit ba6df6595fa70342595c43ee202bacc11e8f87f0)
sync https://github.com/opendatahub-io/opendatahub-operator/pull/1576
https://issues.redhat.com/browse/RHOAIENG-18859
> [sync]fix: missing update permission on dashboard object

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
for the upgrade from pre-refactor to refactor
`"level":"error","ts":"2025-01-29T09:44:10Z","msg":"Reconciler error","controller":"kueue","controllerGroup":"components.platform.opendatahub.io","controllerKind":"Kueue","Kueue":{"name":"default-kueue"},"namespace":"","name":"default-kueue","reconcileID":"57e94f81-862c-4ffd-9566-d4459120f103","error":"failed to remove owner references from object redhat-ods-applications/kueue-prometheus-rules with gvk monitoring.coreos.com/v1, Kind=PrometheusRule: prometheusrules.monitoring.coreos.com \"kueue-prometheus-rules\" is forbidden: User \"system:serviceaccount:redhat-ods-operator:redhat-ods-operator-controller-manager\" cannot update resource \"prometheusrules\" in API group \"monitoring.coreos.com\" in the namespace …
> fix: missing permission to update prometheusrules

- bundle/manifests/rhods-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
(cherry picked from commit fd4c11ba57f6dde8de7827855d311a2f594d89f5)
sync https://github.com/opendatahub-io/opendatahub-operator/pull/1581 
https://issues.redhat.com/browse/RHOAIENG-18913
> [sync]fix: missing permission to update prometheusrules

- bundle/manifests/rhods-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
- cleanup duplicated one
(cherry picked from commit 64fefca0122ecea0f3cf1456d85aebfa0c744b94)
https://issues.redhat.com/browse/RHOAIENG-18859
> [sync]fix: more permission need for dashboard for consolelink

- tests/e2e/datasciencepipelines_test.go
> chore: fix  DataSciencePipelines e2e test suite

- .github/workflows/linter.yaml
- .github/workflows/unit-tests.yaml
> github: add branch into GHA for tests

- OWNERS_ALIASES
Remove Sara4994 from OWNER_ALIASES
This also prevents the openshift ci to auto request as reviewer.
> Remove Sara4994 from OWNER_ALIASES

- OWNERS_ALIASES
> update: platform team

- bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
> regen bundle

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
- without "" it does not work.....
> fix: hide internal API

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/samples/datasciencecluster_v1_datasciencecluster.yaml
ref https://issues.redhat.com/browse/RHOAIENG-16509
> fix: add missing new pipeline flag into default sample

- tests/e2e/kueue_test.go
- if the cluster is shaky, re-creation might happen before old CRD is gone
> test: stablize test why adding post check after deletion

- Dockerfiles/Dockerfile
> build: enable tag to force image build with fips at runtime

- Dockerfiles/Dockerfile
https://github.com/opendatahub-io/opendatahub-operator/pull/1549
https://github.com/opendatahub-io/opendatahub-operator/pull/1627
after this is merged, we need another one for the downstream konflux build.
> [sync]: mutli-arch  + FIPS support

- tests/e2e/controller_test.go
- tests/e2e/helper_test.go
> test: add config for gomega format and nim flag

- pkg/utils/test/testf/testf_assertions.go
- pkg/utils/test/testf/testf_witht_test.go
- tests/e2e/components_test.go
- tests/e2e/dashboard_test.go
- tests/e2e/datasciencepipelines_test.go
- tests/e2e/kueue_test.go
- tests/e2e/modelcontroller_test.go
- tests/e2e/modelregistry_test.go
- tests/e2e/trustyai_test.go
> feat(test): support for Succeed and MatchError in testf framework

- controllers/components/kserve/kserve_support.go
> chore(kserve): wrap error returned by FromUnstructured

- controllers/components/trustyai/trustyai_controller.go
- controllers/components/trustyai/trustyai_controller_actions.go
- controllers/status/status.go
- pkg/cluster/gvk/gvk.go
- tests/e2e/trustyai_test.go
https://github.com/opendatahub-io/opendatahub-operator/pull/1610
https://github.com/opendatahub-io/opendatahub-operator/pull/1620
https://issues.redhat.com/browse/RHOAIENG-19261
> [Sync]feat: add gate in TrustyAI if ISVC CRD is not in the cluster

- tests/e2e/controller_test.go
> e2e: fix wrong validation message

- .github/actions/update-release-version/action.yaml
- OWNERS_ALIASES
> Update owners list

- config/monitoring/prometheus/apps/prometheus-configs.yaml
The `__meta_kubernetes_pod_labelpresent_control_plane` label no longer seems to exist which is causing the RHOAI Metrics job to not gather any metrics since the `keep` action tells prometheus to drop anything that doesn't have that label with the value `true`.
With a label that actually exists on the operator pod metrics are correctly gathered.
[
](url)
> fix_label_in_RHOAI_Metrics_job

- pkg/controller/actions/gc/action_gc.go
- pkg/controller/actions/gc/action_gc_test.go
- use a `map[gvk]struct{}` for `O(1)` lookup
- avoid deleting resources not managed by the operator
> Improve GC action

- controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
- controllers/components/kserve/kserve_controller.go
- controllers/components/kserve/kserve_support.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/services/monitoring/monitoring_controller_actions.go
- pkg/cluster/operator.go
- pkg/cluster/resources.go
- pkg/cluster/resources_test.go
- pkg/controller/reconciler/reconciler.go
- pkg/upgrade/upgrade.go
- pkg/utils/test/fakeclient/fakeclient.go
> [sync] odh -> rhoai: predicates for Kserve dynamic watches

- controllers/components/modelregistry/modelregistry_controller.go
- controllers/components/modelregistry/modelregistry_controller_actions.go
- pkg/cluster/gvk/gvk.go
(cherry picked from commit 2ef7ad77c59770d034abd3049da3600807d82867)
> [rhoai] model-registry: remove custom handdling of the modelregistry-editor-role and modelregistry-viewer-role cluster roles

- docs/COMPONENT_INTEGRATION.md
Add a hyperlink to the codegen tools README.md in the COMPONENT_INTEGRATION.md. This provides a better context for users to access teh codegen's doc.
> (fix): Add a hyperlink to code-gen README.md

- pkg/utils/test/envt/envt.go
- pkg/utils/test/fakeclient/fakeclient.go
- pkg/utils/test/mocks/types.go
- pkg/utils/test/scheme/scheme.go
- pkg/utils/test/testf/testf.go
- helpers to setup envtest
- helpers to register common test schemes
- mock struct for ComponentHandler
> [!NOTE]
> Extracted from https://github.com/opendatahub-io/opendatahub-operator/pull/1688
> Improve test framework

- tests/e2e/kserve_test.go
JIRA: https://issues.redhat.com/browse/RHOAIENG-18045
Some of these tests will change when the code changes, and the hope is
that those test changes will give more clarity and confidence in the
code changes.
Automatically!
> RHOAIENG-18045: Add tests around FTs in Kserve

- config/monitoring/prometheus/apps/prometheus-configs.yaml
- controllers/dscinitialization/auth.go
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/services/auth/auth_controller.go
- controllers/services/auth/auth_controller_actions.go
- tests/e2e/authcontroller_test.go
Original PRs: [1651](https://github.com/opendatahub-io/opendatahub-operator/pull/165) & [1677](https://github.com/opendatahub-io/opendatahub-operator/pull/1667)
[RHOAIENG-19716](https://issues.redhat.com/browse/RHOAIENG-19716) & [RHOAIENG-19900](https://issues.redhat.com/browse/RHOAIENG-19900)
> [sync] Fix auth CR creation & RHOAI metrics 

- docs/COMPONENT_INTEGRATION.md
Feast operator is onboarded in the odh repo but missing an entry in the readme
> (chore): update currently integrated component list

- config/monitoring/prometheus/apps/prometheus-configs.yaml
- controllers/services/monitoring/monitoring.go
- controllers/services/monitoring/monitoring_controller_actions.go
- tests/prometheus_unit_tests/feast-operator-alerting.unit-tests.yaml
Added prometheus config for feast operator component
https://issues.redhat.com/browse/RHOAIENG-19909
> Added prometheus config for feast operator component

- controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
- go.mod
- pkg/cluster/cert.go
- pkg/controller/client/client.go
- pkg/feature/servicemesh/conditions.go
> chore(deps): remove dependency on github.com/pkg/errors and swith to go recommended error wrapping functions

- go.mod
- go.sum
- main.go
> chore(deps): remove dependency on addon-operator APIs as the related types are not used

- controllers/services/monitoring/monitoring.go
- go.mod
> chore(deps): remove dependency on gopkg.in/yaml.v2 and use gopkg.in/yaml.v3

- controllers/dscinitialization/resources/authorino/deployment.injection.patch.tmpl.yaml
- controllers/dscinitialization/servicemesh_setup.go
* update: add ossm sidecar as labels on authornio deployment
- update annotation to labels
---------
(cherry picked from commit 7eeb024605bef366084d20348dc583ea8371ddff)
https://issues.redhat.com/browse/RHOAIENG-18238
> [sync] update: change ossm sidecar as labels on authornio deployment (#1702)

- pkg/utils/test/envt/envt.go
- pkg/utils/test/fakeclient/fakeclient.go
- pkg/utils/test/mocks/types.go
- pkg/utils/test/scheme/scheme.go
- pkg/utils/test/testf/testf.go
- **Improve test framework (#1689)**
- **Add github.com/openshift/api/oauth/v1 to the default schema list**
> [rhoai] Improve test framework

- bundle/manifests/rhods-operator.clusterserviceversion.yaml
- config/manifests/bases/rhods-operator.clusterserviceversion.yaml
https://issues.redhat.com/browse/RHOAIENG-19100
> chore: hide feast from UI

- PROJECT
> [sync] chore: add FeastOperator to PROJECT file

- pkg/controller/actions/gc/action_gc_test.go
- pkg/services/gc/gc.go
> chore(gc): prevent redundant deletion of resources already marked for termination

- tests/e2e/codeflare_test.go
- tests/e2e/datasciencepipelines_test.go
- tests/e2e/kueue_test.go
- tests/e2e/modelregistry_test.go
- tests/e2e/ray_test.go
- tests/e2e/trainingoperator_test.go
- tests/e2e/trustyai_test.go
(cherry picked from commit 6e4594fcf3f814b2f860c910a4100c5c84d80f32)
> [rhoai] ensure components are turned off at the end of the related test suite

- controllers/datasciencecluster/datasciencecluster_controller_actions.go
https://issues.redhat.com/browse/RHOAIENG-21476
> fix: set DSC.status.release

- controllers/components/kserve/kserve_controller.go
- controllers/components/kserve/kserve_controller_actions.go
- controllers/components/kserve/kserve_controller_actions_test.go
- controllers/components/kserve/kserve_support.go
- pkg/cluster/gvk/gvk.go
- pkg/utils/test/scheme/scheme.go
https://issues.redhat.com/browse/RHOAIENG-21531
> DSC not showing all the negative MissingOperator conditions for kserve

- pkg/controller/reconciler/reconciler.go
- pkg/controller/reconciler/reconciler_finalizer_test.go
(cherry picked from commit d8ce37e465d21abd90d38ed727acf2321e91678d)
> [rhoai] added finalizer logic

- controllers/components/suite_test.go
- controllers/services/suite_test.go
- go.mod
- go.sum
[RHOAIENG-21258](https://issues.redhat.com/browse/RHOAIENG-21258)
This PR focuses on cleaning up the testing framework by fully transitioning from **Ginkgo v1** to **Ginkgo v2**.
Changes include:
- Removed all references to `github.com/onsi/ginkgo` (v1)
- Retained only `github.com/onsi/ginkgo/v2`
- Ran `go mod tidy` to clean up unused/obsolete modules
- Ensured all test files and suite setups were compatible with Ginkgo v2.
> chore: remove Ginkgo v1 and retain only Ginkgo v2

- CONTRIBUTING.md
Namely,
* fix sync process link
* put empty lines around lists
* remove trailing whitespace
* remove trailing colon in heading
* add newline to end-of-file
Found with markdownlint-cli2 locally
> chore: Fix markdown in CONTRIBUTING.md

- controllers/components/kserve/resources/servicemesh/kserve-inferencegraph-authorizationpolicy.tmpl.yaml
- controllers/components/kserve/resources/servicemesh/kserve-predictor-authorizationpolicy.tmpl.yaml
we have /healthz already but seems in some cases the path is on /health
i let you guys to decide if you want this to be included
> feat: add endpoint health into AuthorizationPolicy as well

- internal/controller/components/kserve/kserve_support.go
https://issues.redhat.com/browse/RHOAIENG-22090
> fix: missing wildcard for ingress domain

- api/components/v1alpha1/kserve_types.go
- bundle/manifests/components.platform.opendatahub.io_kserves.yaml
- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/crd/bases/components.platform.opendatahub.io_kserves.yaml
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- docs/api-overview.md
- internal/controller/components/kserve/kserve.go
- internal/controller/components/kserve/kserve_controller.go
- internal/controller/components/kserve/kserve_controller_actions.go
- internal/controller/components/kserve/kserve_support.go
- internal/controller/status/status.go
- change checsk on RemoveResources and Delete resource
- remove validation pattern in kserve since it is enum list
- cleanup some code in kserve
- combine two upgrade CM function into one
> update: kserve logic + small chores

- Makefile
- cmd/main.go
- docs/troubleshooting.md
Jira: [RHOAIENG-21400](https://issues.redhat.com/browse/RHOAIENG-21400)
This allows pprof to be easily used during development by using commands such as:
- `go tool pprof -http : http://localhost:6060/debug/pprof/heap`
- `go tool pprof -http : http://localhost:6060/debug/pprof/profile`
- `go tool pprof -http : http://localhost:6060/debug/pprof/block`
Note: you can also save a pprof file for use in other tools or offline analysis as follows:
```shell
curl -s "http://127.0.0.1:6060/debug/pprof/profile" > ./cpu-profile.out
```
It defaults to "", which effectively disables pprof, but I updated the `Makefile` so that `RUN_ARGS` sets it to http://127.0.0.1:6060 for convenience (`make run` and `make run-nowebhook` end up with pprof enabled).
See …
> chore: Add flag for pprof-bind-address

- OWNERS_ALIASES
> OWNERS_ALIASES: remove ykaliuta

- OWNERS_ALIASES
> chore: add new member, remove old members

- cmd/component-codegen/templates/component_handler.go.tmpl
- cmd/component-codegen/templates/component_support.go.tmpl
- cmd/component-codegen/templates/types.go.tmpl
- docs/COMPONENT_INTEGRATION.md
rh-pre-commit.version: 2.3.2
rh-pre-commit.check-secrets: ENABLED
With new changes to certain methods, imports etc. the cli tool needed updates to comply with the latest changes.
Run `make new-component COMPONENT=<ComponentName>`
> (fix): Change code generation templates

- pkg/cluster/resources.go
With commit ecdb2dc4, we introduced helper functions to retrieve
singleton objects like DataScienceCluster and DSCInitialization.
However, under certain yet-to-be-investigated circumstances, retrieving
DSCInitialization does not always work reliably. This commit aims to
reintroduce the ad-hoc logic for retrieving both DSC and DSCI to
address this issue.
Once the root cause will be determined, we should revert back this code
and use the shared singleton retreieval logic.
https://issues.redhat.com/browse/RHOAIENG-22919
> DSCI creation got stuck in operator reconciliation in selfmanaged clusters

- cmd/component-codegen/cmd/generator/generator.go
- cmd/component-codegen/cmd/generator/update_project_file.go
The cli codegen tool now adds an entry of new API in the PROJECT file.
run `make new-component COMPONENT=TestOperator`
> (feat): add logic to update PROJECT file

- internal/controller/components/dashboard/dashboard_controller_actions.go
- internal/controller/components/dashboard/dashboard_support.go
- internal/controller/components/datasciencepipelines/datasciencepipelines_support.go
- internal/controller/components/trustyai/trustyai_support.go
- pkg/cluster/cluster_config.go
- pkg/cluster/const.go
- tests/e2e/authcontroller_test.go
> [sync] update: remove Unknown constant from platform detection logic

- internal/controller/components/feastoperator/feastoperator.go
- internal/controller/components/feastoperator/feastoperator_controller_actions.go
- internal/controller/components/feastoperator/feastoperator_support.go
related to change https://github.com/feast-dev/feast/pull/5231
replace https://github.com/opendatahub-io/opendatahub-operator/pull/1822
ref: https://issues.redhat.com/browse/RHOAIENG-13568
> update: add support for overlays in Feast

- internal/controller/services/auth/resources/admingroup-clusterrole.tmpl.yaml
Added get, watch, and list to admin users so they can patch effectively, and get access to storage classes in the table.
https://issues.redhat.com/browse/RHOAIENG-22907
n/a
> Added get, list, and watch to storageclasses

- bundle/manifests/rhods-operator.clusterserviceversion.yaml
- config/manifests/bases/rhods-operator.clusterserviceversion.yaml
feast only show from UI, need update template
> update: add init config for feast to show as Removed

- cmd/main.go
- internal/controller/certconfigmapgenerator/certconfigmapgenerator_controller.go
- internal/controller/secretgenerator/secretgenerator_controller.go
- internal/controller/services/certconfigmapgenerator/certconfigmapgenerator_controller.go
- internal/controller/services/secretgenerator/secretgenerator_controller.go
- internal/controller/services/setup/setup_controller.go
- internal/controller/setupcontroller/setup_controller.go
* services: refactor CertConfigmapGeneratorReconciler to service handler
* services: refactor SecretGeneratorReconciler to service handler
* services: refactor SetupControllerReconciler to service handler
* lint
* Fix finding
(cherry picked from commit d602e9c538ac32fb8c36f6ff24f6a151dc565710)
> [rhoai] Refactor SetupController, SecretGenerator and CertConfigmapGenerator to service handler

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
> chore: typo fix

- OWNERS_ALIASES
-------
Remove owners that are no longer involved (I checked with George and
Edson, and they're fine with being removed, can be added back later if
needed).
This also adds @mlassak and @valdar so that they'll be included in the
random reviewer selection, and the bots should accept their approval.
> chore: Refresh owners list used for reviewer assignment

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/samples/datasciencecluster_v1_datasciencecluster.yaml
> Remove wrong configuration for the datasciencepipelines: component in DSC sample

- CONTRIBUTING.md
- docs/sync_code.md
This is a manual cherry-pick of https://github.com/opendatahub-io/opendatahub-operator/pull/1896.
> [sync][chore] Clarify sync process in contributing docs

- api/components/v1alpha1/kserve_types.go
- bundle/manifests/components.platform.opendatahub.io_kserves.yaml
- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- config/crd/bases/components.platform.opendatahub.io_kserves.yaml
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- docs/api-overview.md
- internal/controller/components/kserve/kserve.go
- internal/controller/components/kserve/kserve_controller.go
- internal/controller/components/kserve/kserve_controller_actions.go
- internal/controller/components/kserve/kserve_support.go
- internal/controller/status/status.go
This is a manual cherry-pick of https://github.com/opendatahub-io/opendatahub-operator/pull/1797.
> [sync][update] kserve logic + small chores

- internal/controller/dscinitialization/dscinitialization_controller.go
- internal/controller/dscinitialization/utils.go
- internal/controller/services/auth/auth.go
- internal/controller/services/auth/auth_controller.go
- internal/controller/services/auth/auth_controller_actions.go
- pkg/cluster/cluster_config.go
(cherry picked from commit de46f015061646b546e9670e6649866fc9604e2d)
> [sync] Refactored auth group creation out of the DSCI controller

- internal/controller/dscinitialization/dscinitialization_controller.go
- internal/controller/dscinitialization/utils.go
- pkg/cluster/gvk/gvk.go
- tests/e2e/creation_test.go
(cherry picked from commit 8a67079ce5cc89e790ab38a3bfebe64ce0d6a6b6)
> [sync] Use SSA for default NetworkPolicy creation

- internal/controller/dscinitialization/utils.go
* [backport]fix: need apply application NWP for self-managed cluster
- monitoring NWP can be only for managed cluster
- components might require certain ports e.g 9443 to be open
* Update internal/controller/dscinitialization/utils.go
---------
ref: https://issues.redhat.com/browse/RHOAIENG-26005
> [sync]fix: need apply application NWP for self-managed cluster (#1946) + some code difference

- bundle/manifests/rhods-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- tests/e2e/odh_manager_test.go
Manually cherry-pick from https://github.com/opendatahub-io/opendatahub-operator/pull/2066.
> [sync]: Set controller deployment replicas to 3 for webhook HA

- bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- bundle/manifests/rhods-operator.clusterserviceversion.yaml
- bundle/manifests/services.platform.opendatahub.io_monitorings.yaml
- config/samples/dscinitialization_v1_dscinitialization.yaml
- internal/controller/dscinitialization/dscinitialization_controller.go
- internal/controller/services/monitoring/monitoring_controller.go
- internal/controller/services/monitoring/monitoring_controller_actions.go
- internal/controller/services/monitoring/monitoring_controller_support.go
- pkg/upgrade/upgrade.go
- tests/e2e/monitoring_test.go
including PR:
#2155 #2164 #2147
> [Sync] monitoring from main branch to rhoai

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
without the PR
discussed https://redhat-internal.slack.com/archives/C08S0H9HANM/p1752669691717879
> update: hide HWProfile from Operator tab from UI

- bundle/manifests/rhods-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- internal/controller/datasciencecluster/kubebuilder_rbac.go
- pkg/cluster/gvk/gvk.go
* update: add rbac
- llmisvcconfig 
(cherry picked from commit 9505b263696f55b916a9a5166520cccbbfbfe81a)
sync https://github.com/opendatahub-io/opendatahub-operator/pull/2145
> [Sync] update: rbac for llm-d + uplift operator version

- pkg/rules/rules.go
- pkg/rules/rules_test.go
[RHOAIENG-31281](https://issues.redhat.com/browse/RHOAIENG-31281)
> Setting Kueue to unmanaged state throws an error and blocks DSC

- bundle/manifests/rhods-operator.clusterserviceversion.yaml
- internal/controller/datasciencecluster/kubebuilder_rbac.go
for change on rhoai branch
work with https://github.com/opendatahub-io/opendatahub-operator/pull/2297
ref: https://issues.redhat.com/browse/RHOAIENG-31327
> update: remove duplicated RBAC

- config/monitoring/base/rhods-servicemonitor.yaml
- internal/controller/services/monitoring/resources/collector-servicemonitors.tmpl.yaml
- internal/controller/services/monitoring/resources/opentelemetry-collector.tmpl.yaml
sync https://github.com/opendatahub-io/opendatahub-operator/pull/2285 to rhoai branch
> [sync] RHOAIENG-29721 | feat: Adding tls to otel colletor

- internal/webhook/inferenceservice/mutating.go
- internal/webhook/inferenceservice/mutating_test.go
- pkg/webhook/utils.go
sync https://github.com/opendatahub-io/opendatahub-operator/pull/2358 and https://github.com/opendatahub-io/opendatahub-operator/pull/2362
ref:  https://issues.redhat.com/browse/RHOAIENG-32828
> [sync]: feat: handle connection API deletion 

- tests/e2e/kserve_test.go
- tests/e2e/test_context_test.go
> Increase timeout for the deletion to avoid failures in HCP

- Makefile
- docs/api-overview.md
Cherry pick commit from https://github.com/opendatahub-io/opendatahub-operator/pull/2380
> [stable-2.x] Add support in makefile to darwin sed using gsed

- bundle/manifests/rhods-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- internal/controller/components/kueue/kueue_controller.go
- internal/controller/components/kueue/kueue_controller_actions.go
- internal/controller/components/kueue/kueue_controller_actions_test.go
- internal/controller/components/kueue/kueue_support.go
- internal/controller/datasciencecluster/kubebuilder_rbac.go
- pkg/cluster/gvk/gvk.go
- tests/e2e/kueue_test.go
cherry-pick of https://github.com/opendatahub-io/opendatahub-operator/pull/2375
Regenerate manifests and bundle to include nodes
> [stable-2.x] Add ClusterQueue resource aware configuration and generate ResourceFlavor

- bundle/manifests/rhods-operator.clusterserviceversion.yaml
- internal/controller/components/kserve/kserve_controller.go
- pkg/cluster/gvk/gvk.go
sync https://github.com/opendatahub-io/opendatahub-operator/pull/2348
- [] The developer has run the integration test pipeline and verified that it passed successfully
4. Submit/save these changes to the PR …
> [sync] feat: add llm-d related CRDs into watch [#2348]

- internal/controller/components/kserve/kserve_controller.go
- internal/controller/services/servicemesh/servicemesh_controller.go
- pkg/controller/actions/actions_support.go
Cherry pick of https://github.com/opendatahub-io/opendatahub-operator/pull/2483
> [stable-2.x] Remove duplicated crd check
