- kustomize/overlays/opendatahub/cluster_role_binding_patch.yaml
- kustomize/overlays/opendatahub/deployment_patch.yaml
- kustomize/overlays/opendatahub/kustomization.yaml
- kustomize/overlays/opendatahub/name_patch.yaml
- kustomize/overlays/opendatahub/params.yaml
This PR:
* Adds `Dockerfile.ubi` for UBI based operator image
* Make `Makefile` and `build-operator` more flexible to configure
* `DOCKERFILE` for Dockerfile name
* `IMAGE_BUILDER` to allow using `podman` to build the image
* Add Kustomize for deployment manifests to simply run
* `kustomize build deploy/` 
* This allows simple extensibility and configurability for the deployment manifests (e.g. Open Data Hub will be able to rename some of the resources to `opendatahub-operator` without actually forking the manifests)
Depending on if you have Docker or podman installed (default is `docker`)
```
export IMAGE_BUILDER=podman
```
Set the image and the dockerfile name
```
export OPERATOR_IMG=quay.io/${USER}/opendatahub-operator:0.6.0
export DOCKERFILE=Dockerfile.ubi
```
Build and push the …
> Add ODH overlay to KF operator kustomize

- deploy/olm-catalog/opendatahub/0.6.1/opendatahub-operator.v0.6.1.clusterserviceversion.yaml
The 0.6.1 CSV had a typo in the `replaces` property that did not point to a valid ODH CSV object. This issue was fixed in the official CSV release in  [community operators](https://github.com/operator-framework/community-operators/blob/master/community-operators/opendatahub-operator/0.6.1/opendatahub-operator.v0.6.1.clusterserviceversion.yaml#L361) but we need to add it back to our repo
> Fix "replaces" property in 0.6.1 CSV

- deploy/olm-catalog/opendatahub/0.8.0/kfdef.apps.kubeflow.org.crd.yaml
- deploy/olm-catalog/opendatahub/0.8.0/opendatahub-operator.v0.8.0.clusterserviceversion.yaml
- deploy/olm-catalog/opendatahub/opendatahub-operator.package.yaml
ODH release for 0.8 release. 
The only major update that I added to the description was the support for JupyterLab notebooks in JupyterHub
Closes #54
> Add ODH ClusterServiceVersion for 0.8.0 release

- .aicoe-ci.yaml
Allow aicoe-ci to assist with:
-  image build on tag release. 
-  build-check on each pull request.
Tested it on fork: 
Following configuration was used:
https://github.com/harshad16/opendatahub-operator/blob/master/.aicoe-ci.yaml
Built image based on the demo tag:
[quay.io/harshad16/opendatahub-operator:demo] (https://quay.io/harshad16/opendatahub-operator:demo)
configure aicoe-ci to support image build release.
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
> configure aicoe-ci to support image build release.

- .aicoe-ci.yaml
When we create a new release (e.g. `v0.9.0`) this change will ensure `latest` points to this latest release
> Add custom tag (latest) for new releases

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/major-release.md
- .github/ISSUE_TEMPLATE/minor-release.md
- .github/ISSUE_TEMPLATE/patch-release.md
- .github/ISSUE_TEMPLATE/redeliver_container_image.md
- .thoth.yaml
- version.py
enable thoth-bot kebechet to handle release changelogs
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
the kebechet bot requires a version file where it would keep the version track of the component, based on that it would update the next update. following file names are accepted:
```
setup.py
__init__.py
__about__.py
version.py
app.py
wsgi.py
```
which one should we include in the application?
the file content would be : 
```
__version__ = "X.Y.Z"
```
> enable thoth-bot kebechet to handle release changelogs

- version.py
Updating the patch release version in `version.py` after manually tagging `v1.0.5`
> Bump version to v1.0.5 for kebechet bot

- bundle/manifests/kfdef.apps.kubeflow.org.crd.yaml
- deploy/crds/kfdef.apps.kubeflow.org_kfdefs_crd.yaml
This commit updates apiextextensions.k8s.io api from v1beta1 to v1 as
the former is no longer supported on OpenShift versions 4.9+
Jira Issue: https://issues.redhat.com/browse/ODH-452
> Update crd for OpenShift 4.9

- pkg/kfconfig/types.go
Cherrypick fix from kubeflow/kfctl#326 to allow syncing when behind a proxy.
> Fix syncing cache behind HTTP proxy (kubeflow/kfctl#326)

- pkg/utils/k8utils.go
This commit makes use of `ServerSideApply` option provided by
kubectl package to perform server-side apply while deploying manifests.
This will fix issues that result in failed reconciliation when oversized
CRDs are deployed.
1. Deploy custom operator image using instructions given here : https://github.com/opendatahub-io/opendatahub-operator/blob/master/operator.md#build-instructions (My custom image: quay.io/vhire/kfctl:v1.2)
2. Test if following KfDefs are applied successfully:
- [ODH](https://github.com/opendatahub-io/odh-manifests/blob/master/kfdef/kfctl_openshift.yaml)
- [Notebook Controller](https://github.com/opendatahub-io/odh-manifests/blob/master/kfdef/kfctl_odh_notebook_controller.yaml)
- [Kubeflow Manifests](https://github.com/opendatahub-io/manifests/blob/v1.5-branch-openshif …
> Deploy applications using server-side apply

- go.mod
- go.sum
- pkg/apis/apps/addtoscheme_kfdef_v1.go
- pkg/controller/secretgenerator/secret.go
- pkg/controller/secretgenerator/secretgenerator_controller.go
Fixes #175 
Operator Image: quay.io/vhire/opendatahub-operator:testoauth
1. Create an example secret with required annotations and plain text
```
apiVersion: v1
kind: Secret
metadata:
name: example
annotations:
secret-generator.opendatahub.io/name: "password"
secret-generator.opendatahub.io/type: "random"
secret-generator.opendatahub.io/complexity: "16"
secret-generator.opendatahub.io/oauth-client-route: "example-route"
type: Opaque
```
2. Create a Route for an example service to be accessed by Oauth client
```
kind: Route
apiVersion: route.openshift.io/v1
metadata:
name: example-route
namespace: test
spec:
host: >-
example-route-test.apps.ci-ln-2gzkqh2-76ef8.origin-ci-int-aws.dev.rhcloud.com
to:
kind: Service
name: example
weight: 100
port:
targetPort: 9376
```
The seceret Controller …
> Update secret-controller to create OAuth client

- pkg/kfapp/kustomize/kustomize.go
- pkg/kfapp/kustomize/kustomize_test.go
Fixes #179 
1. Install Open Data Hub operator
2. Update CSV with following two changes:
- spec.image : quay.io/vhire/opendatahub-operator:env 
- Add following env variable under spec.env
```
name: MINIMAL_IMAGE
value: quay.io/thoth-station/s2i-minimal-py38-notebook:v0.3.0
``` 
3. Deploy following KfDef
```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
name: opendatahub
namespace: opendatahub
spec:
applications:
- kustomizeConfig:
repoRef:
name: manifests
path: odh-common
name: odh-common
- kustomizeConfig:
overlays:
- additional
parameters:
- name: minimal-image
value: $MINIMAL_IMAGE
repoRef:
name: manifests
path: jupyterhub/notebook-images
name: notebook-images
repos:
- name: manifests
uri: https://github.com/VaishnaviHire/odh-manifests/tarball/test_image_vars
```
> Read env variables from KfDef Parameters

- deploy/olm-catalog/opendatahub/1.4.1/manifests/kfdef.apps.kubeflow.org.crd.yaml
- deploy/olm-catalog/opendatahub/1.4.1/manifests/odhapplications.dashboard.opendatahub.io.crd.yaml
- deploy/olm-catalog/opendatahub/1.4.1/manifests/odhdashboardconfigs.opendatahub.io.crd.yaml
- deploy/olm-catalog/opendatahub/1.4.1/manifests/odhdocuments.dashboard.opendatahub.io.crd.yaml
- deploy/olm-catalog/opendatahub/1.4.1/manifests/odhquickstarts.console.openshift.io.crd.yaml
- deploy/olm-catalog/opendatahub/1.4.1/manifests/opendatahub-operator.v1.4.1.clusterserviceversion.yaml
- deploy/olm-catalog/opendatahub/1.4.1/metadata/annotations.yaml
Required for successful deployment of https://github.com/opendatahub-io/odh-manifests/pull/693
Closes #185 
Creates an odh v1.4.1 operator bundle and adds the ODH Dashboard CRDs to the list of owned CRDs for ODH
Create a catalogsource with this bundle and installed the operator
- ODH 1.4.1 operator can be deployed successfully from this bundle
- New CRDs are included in the OperatorHub tile for ODH
- User with appropriate permission can create customresources based on these tiles
> Add ODH Dashboard CRDs to owned CRDs in 1.4.1 CSV

- deploy/olm-catalog/opendatahub/1.4.1/manifests/opendatahub-operator.v1.4.1.clusterserviceversion.yaml
- deploy/olm-catalog/opendatahub/1.4.1/metadata/annotations.yaml
Update the example kfdef in the v1.4.1 CSV to use the new `notebook-images` manifest
Deployed using the new operator and the example kfdef in v1.4.1
New operator bundle deploys the CRDs and deploys as expected.
> Update alm-examples for 1.4.1 Release

- deploy/olm-catalog/opendatahub/1.4.1/manifests/odhdashboardconfigs.opendatahub.io.crd.yaml
- deploy/olm-catalog/opendatahub/1.4.1/manifests/opendatahub-operator.v1.4.1.clusterserviceversion.yaml
Fixes a typo in the `displayName` for the `ODHDocument` CRD in the v1.4.1 CSV
> Fix 1.4.1 CSV CRD displayname

- controllers/kfdef.apps.kubeflow.org/kfdef_controller.go
- pkg/kfapp/kustomize/kustomize.go
- pkg/utils/k8utils.go
Fixes #209 
Every resource added by the operator will have following ownerrefferences
```
ownerReferences:
- apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
name: odh-core
uid: <uid>
controller: true
blockOwnerDeletion: true
```
1. Deploy operator using `make deploy`
2. Create [odh-core](https://github.com/opendatahub-io/odh-manifests/blob/master/kfdef/odh-core.yaml) KfDef
3. Delete KfDef
**Note :** resources like Grafana and prometheus will not be deleted, since they are managed by respective operators
> Add ownerreferrences to manifest resources

- controllers/kfdef.apps.kubeflow.org/kfdef_controller.go
- pkg/kfapp/kustomize/kustomize.go
- tests/e2e/odh_controller_setup_test.go
- tests/e2e/odh_creation_test.go
This PR includes changes specific to e2e tests:
- Update resource creation timeout for CI environment
- Remove Kfdef Annotation tests as we moved to Ownerreferences
- Remove ownerreferences from Subscription resource (This is required for allowing operator installs for DSP tests)
Resolves:
- Test failures in openshift-ci
> Add fixes for operator and odh-manifests e2e tests 

- Makefile
Add the `${IMAGE_BUILDER}` variable to the `make catalog-build` target to resolve errors when `docker` is not installed on the system
run `make catalog-build` to generate a catalog image successfully
You can successfully run `make catalog-build` when only `podman` is installed
> Use {IMAGE_BUILDER} in Makefile for opm index cmd

- LICENSE
The opendatahub-operator project has always been licensed under Apache 2.0, but it was missing a license file.
> add the Apache 2.0 LICENSE file to the project

- Dockerfile
- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- controllers/dscinitialization/dscinitialization_controller.go
- Dockerfile add support to download odh-manifests tarball during build
- Makefile add target to download operator-sdk if not have it already
- rename target `docker-*` to `image-*` since default using `podman`
- go fmt for format
- update default image pullspec in CSV
build image locally
```
>docker run eceaa0bb36b94af36146c83513a4922309635b9f8b7e12abb41286aea82067a1 -- ls /opt/odh-manifests
LICENSE
Makefile
OWNERS
README.md
RELEASE.md
ceph
codeflare-stack
data-science-pipelines-operator
docs
grafana
....
```
> Update: Dockerfile and Makefile

- .github/workflows/sync_dashboard_crds.yaml
Update: GitHub Action for sync CRD from odh-dashboard
- only check out source code branch not all ref object
- make dashboard only export by label not "master" branch
- delete branch after PR is merged, so next run wont be problem
- update wording
- add signoff
Tested from my forked repo, 
set source repo to "zdtsw/github_1" (since my master is downstream from rhods repo) 
set label of dashboard to v2.11.0
Action run https://github.com/zdtsw/opendatahub-operator/actions/runs/5236279870
Created PR https://github.com/zdtsw/opendatahub-operator/pull/2
> Update: GitHub Action for sync CRD from odh-dashboard

- .gitignore
- Dockerfile
- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
- tests/e2e/helper.go
Resolves: #196 
This PR adds a function that adds a check whenever KFApply is called to check if there are any Repos specified, if not, it takes local manifests that are downloaded at build time.
1. Deployed operator specified in the PR on a cluster
2. Added the following KFDef:
```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
name: odh-core-testing
spec:
applications:
- kustomizeConfig:
repoRef:
name: manifests
path: odh-common
name: odh-common
- kustomizeConfig:
repoRef:
name: manifests
path: odh-dashboard
name: odh-dashboard
3. Verified that the operator took its local file and deployed the resources despite not having a repo specified.
4. Verify that if the Repos section *is* specified, no functionality is broken.
> Add local bundle for odh manifests

- Dockerfile
- Makefile
Updates the Makefile and Dockerfile to support build time configuration of the url for the odh-manifests to download and include in the odh-operator container image
Local deployment using
```
make docker-build -e IMG=<TEST IMAGE>
make deploy
make e2e-test -e IMG=<TEST IMAGE>
```
Operator image build successfully
odh-manifests test runs successfully. NOTE: Known issue that the pipelines test will fail due to error in ocp-pipelines operator subscription
> Updates for the ODH v1.7 release

- Makefile
- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
- config/manager/kustomization.yaml
- config/rbac/role.yaml
- config/rbac/role_binding.yaml
- controllers/dscinitialization/dscinitialization_controller.go
- dscinitialization role is missing in the role.yaml file which does not get populated into final CSV file.
- it was caused by missing an empty line in controller, so the controller-gen could not understand what need to be generated in role.yaml
- name of the role is changed from standard manager-role to controller-manager-role, this need to be updated in makefile
build new operator image dev-0.0.2 and bundle image v0.0.2
>operator-sdk run bundle quay.io/wenzhou/opendatahub-operator-bundle:v0.0.2
"manager" container can start in pod.
(it gets panic need another fix for that)
> Fix: mismatch role binding and missing clusterrole permission in CSV

- Dockerfile
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/monitoring.go
- pkg/deploy/setup.go
add better logging to show cluster type and if monitoring enabled by user
related to https://github.com/opendatahub-io/opendatahub-operator/issues/252
tested on ROSA cluster 
```
2023-07-04T14:48:02Z	INFO	Starting workers	{"controller": "dscinitialization", "controllerGroup": "dscinitialization.opendatahub.io", "controllerKind": "DSCInitialization", "worker count": 1}
2023-07-04T14:48:02Z	INFO	controllers.DSCInitialization	Reconciling DSCInitialization.	{"DSCInitialization": "", "Request.Name": "default"}
2023-07-04T14:48:02Z	INFO	controllers.DSCInitialization	Monitoring enabled, won't apply changes	{"cluster": "Self-Managed  Mode"}
```
> Add logging to show cluster type and if monitoring enabled by user

- apis/dscinitialization/v1alpha1/dscinitialization_types.go
- bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
- config/samples/console_v1_odhquickstarts.yaml
- config/samples/dashboard_v1_odhapplications.yaml
- config/samples/dashboard_v1_odhdocuments.yaml
- config/samples/datasciencecluster_v1alpha1_datasciencecluster.yaml
- config/samples/dscinitialization_v1alpha1_dscinitialization.yaml
- config/samples/kustomization.yaml
- config/samples/opendatahub_v1alpha1_odhdashboardconfigs.yaml
- set `.spec.monitoring.namespace` as omitempty/not required , because zero value of bool, meaning enabled by default false. unless user  update it to "true" is not needed any namespace to be monitored
- add spec for sample yamls for disabling warning when run "make bundle"
- add default value `false` for .`spec.monitoring.enabeld `
-  set .`spec.monitoring.namespace` with `opendatahub`
```
make deploy -e IMG=quay.io/wenzhou/opendatahub-operator:dev-0.0.4
make bundle-build bundle-push catalog-build catalog-push  -e BUNDLE_IMAGE=quay.io/wenzhou/opendatahub-operator:v0.0.4
operator-sdk run bundle quay.io/wenzhou/opendatahub-operator-bundle:v0.0.4
```
> Update dscinitiazation spec for monitoring

- Dockerfiles/Dockerfile
- Makefile
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/modelmeshserving/modelmeshserving.go
- components/workbenches/workbenches.go
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
- config/rbac/role.yaml
- controllers/dscinitialization/monitoring.go
- pkg/deploy/deploy.go
- reuse the same path as operator v1 set
- this will help when we build downstream RHODS to use the same image of odh-manifests
- change each component to use deploy.go `DefaultManifestPath` 
build local image
> docker run -it --entrypoint bash quay.io/wenzhou/opendatahub-operator:test-0.0.1
```
...
bash-4.4$ ls
ceph                             docs     model-mesh            notebook-images  odh-notebook-controller  ray
codeflare-stack                  grafana  modelmesh-monitoring  odh-common       openshift-pipelines      trustyai-service
data-science-pipelines-operator  kfdef    must-gather           odh-dashboard    prometheus
bash-4.4$ pwd
/opt/manifests
```
> Update to /opt/manifests from /opt/odh-manifests

- controllers/dscinitialization/utils.go
As a temp. workaround,  to get dashboard route working (and modelmesh monitoring route) , open all for now.
Ideally we should get all ports and define with is needed for which components. 
- ref https://github.com/opendatahub-io/odh-manifests/pull/882 
build test image, deploy to cluster, check networkpolicy content:
> Update networkpolicy to allow all traffic access applicationNamespace

- controllers/datasciencecluster/datasciencecluster_controller.go
- docs/Dev-Preview.md
Switching component's enabled property default value to false. Fixes #324
> Switching component's enabled property default value to false. Fixes #324

- components/component.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/distributedworkloads/distributedworkloads.go
- components/kserve/kserve.go
- components/modelmeshserving/modelmeshserving.go
- components/workbenches/workbenches.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/utils.go
Switching default value for component's enabled property to false 
Changing enabled from *bool to bool and simplifying/cleaning code
fixes #324
Manually tested in the cluster. The following input CR:
```yaml
apiVersion: datasciencecluster.opendatahub.io/v1alpha1
kind: DataScienceCluster
metadata:
name: default
spec:
components:
dashboard:
enabled: false
datasciencepipelines:
enabled: true
kserve:
enabled: true
```
Generates the following yaml after creation:
```yaml
apiVersion: datasciencecluster.opendatahub.io/v1alpha1
kind: DataScienceCluster
...
spec:
components:
dashboard:
enabled: false
datasciencepipelines:
enabled: true
kserve:
enabled: true
modelmeshserving:
enabled: false
workbenches:
enabled: false
...
```
> Switching default value for component's enabled property to false #324

- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/kustomization.yaml
- config/samples/datasciencecluster_v1alpha1_datasciencecluster.yaml
- docs/Dev-Preview.md
Not sure if it was mistakenly added but "kfdef" is in "owned" and "required" both section in CSV yaml
also samples are gone when create CR
> Add samples back and remove kfdef from "owned" in CSV

- apis/dscinitialization/v1alpha1/dscinitialization_types.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/status/status.go
Adding conditions for each installed component. 
Properly setting values for conditions during reconciliation.
Fixes #351 
Manually tested in the cluster
The following CR:
```yaml
apiVersion: datasciencecluster.opendatahub.io/v1alpha1
kind: DataScienceCluster
metadata:
name: default
spec:
components:
dashboard:
enabled: true
datasciencepipelines:
enabled: true
distributedWorkloads:
enabled: false
kserve:
enabled: true
modelmeshserving:
enabled: false
workbenches:
enabled: true
```
Results in the following conditions after reconciliation is complete:
> Improving conditions management. Fixes #351

- apis/dscinitialization/v1alpha1/dscinitialization_types.go
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- components/kserve/kserve.go
- components/modelmeshserving/modelmeshserving.go
- components/workbenches/workbenches.go
- config/crd/bases/kfdef.apps.kubeflow.org_kfdefs.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- main.go
- set rbac for "core" group not empty, more explict
- set Option for fileds are not required
- reorder Owns() to have depended resource high prio and add ServiceAccount and Service
- add recorder for dscinitialization to get events
build quay.io/wenzhou/opendatahub-operator-catalog:v2.0.1
> Update: rbac group, kubebuilder, Owns order and add  recorder

- components/dashboard/dashboard.go
need go with https://github.com/red-hat-data-services/odh-manifests/pull/414
> Add apply manifests for dashboard ISV

- components/dashboard/dashboard.go
from odh-deployer https://github.com/red-hat-data-services/odh-deployer/blob/main/deploy.sh#L341
Along with changes in https://github.com/red-hat-data-services/odh-manifests/pull/437/files
> Apply OVMS as part of dashboard manifests

- apis/datasciencecluster/v1alpha1/datasciencecluster_types.go
- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- controllers/datasciencecluster/datasciencecluster_controller.go
Just to fix version number overwritten by previous commit
also add description for codeflare/ray
> Fix: version number and add description

- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/status/status.go
Fixes #386 #379 
1. Deploy operator image from PR
2. Phase Ready with all components errors listed in Conditions
> Remove dependency of deployment manifests on other components

- components/kserve/kserve.go
fix: https://github.com/opendatahub-io/opendatahub-operator/issues/383
so we will only have these 4 images
the other 2 of explainer are currently still needed but later similar function will be replaced by new images in trustyai.
therefore we no need these 2 images, and only refer them for the coming couple of releases.
already in https://github.com/red-hat-data-services/odh-manifests/pull/434/files params.env has  variables set
> Add Kserve ImageParams Map

- controllers/datasciencecluster/datasciencecluster_controller.go
Fixes #324 . Showing all components in YAML CR, even if disabled.
Manually tested in the cluster
> Fixes #324 . Showing all components in YAML CR, even if disabled.

- components/dashboard/dashboard.go
from test:
wrong link:
https://rhods-dashboard-redhat-ods-applicationsapps.ods-qe-01.rhods.ccitredhat.com/
should be:
https://rhods-dashboard-redhat-ods-applications.apps.ods-qe-01.rhods.ccitredhat.com/
Ref: https://github.com/opendatahub-io/opendatahub-operator/issues/261
> Fix: wrong consolelink url missing "."

- apis/datasciencecluster/v1alpha1/datasciencecluster_types.go
- apis/dscinitialization/v1alpha1/dscinitialization_types.go
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/secretgenerator/secretgenerator_controller.go
- logger for secretegenerator is not needed(cherry-pick this from downstream)
- context is not needed in dsc, not needed
- put order in api fileds, so internal one manifestsuri will be in lower order than monitoring, otherwise sort by alphabet 
local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.8.8
enabled several components
Pod created and working, 
For secretgenerator 
it prints logs ( since it is a cluster, it did reconcile at first then after dashboard-oauth-client-generated created all went well)
> Add order in marker to reorder CSV + remove context which is not in use + remove logger for secretgen

- controllers/dscinitialization/monitoring.go
From testing :
```
Changing this setting from the dashboard "cluster settings" page appears to work fine, but in the backend I see no changes to the odh-segment-key configmap.
configmap/secret from segment is now stored in the monitoring namespace instead of the applications namespace.
```
> Update: segment-io CM namespace from monitoring to application's

- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- main.go
Fixes #436 
1. Deploy following dev catalogsource
```
quay.io/vhire/opendatahub-operator-catalog:v2.0.32 
```
2. Subscribe to operator using following subscription
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
name: opendatahub-operator
namespace: openshift-operators
spec:
channel: fast
name: opendatahub-operator
source: opendatahub-dev-catalog
sourceNamespace: openshift-marketplace
config:
env:
- name: "DISABLE_DSC_CONFIG"
```
3. Verify no namespaces are created
4. Verify when `DataScienceCluster` CR is created, it goes into Error phase
----
**To Enable Components**
5. Create `DSCInitialization` CR
```
apiVersion: dscinitialization.opendatahub.io/v1alpha1
kind: DSCInitialization
metadata:
name: default
spec:
monitoring:
enabled: false
namespace: 'opendatahub' …
```
> Add support for custom subscription config

- components/codeflare/codeflare.go
- pkg/deploy/deploy.go
Before applying CodeFlare manifests, check for the codeflare-operator subscription, and raise a meaningful error if not.
Fixes #379
Manually tested in the cluster. In case the codeflare operator is not installed, the following error message is raised:
```
CodeFlare operator not found in namespace openshift-operators. Please install it before enabling the codeflare component
```
> Before applying CodeFlare manifests, check for the codeflare-operator

- components/dashboard/dashboard.go
PathISVSM PathODHDashboardConfig PathOVMS these are only applicable for downstream
fix enable dashboard error from missing manifests
local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.8.22-1
> Fix: move deploy manifests only for non-ODH to block

- Makefile
- tests/e2e/controller_setup_test.go
- tests/e2e/dsc_creation_test.go
- tests/e2e/dsc_deletion_test.go
- tests/e2e/helper_test.go
- tests/e2e/odh_manager_test.go
- run check component test in parallel, other test case still in sequence
- add longer timeout due to new components(keep it here even updated testing in parallel)
- add Ray in the testing
- logs for error message
- enable test on "deletion"
took 761s (>10m)
after change to run in parallel took 300s
> Update e2e test: timeout + ray + logging

- bundle/manifests/opendatahub-operator-manager-config_v1_configmap.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/manager/controller_manager_config.yaml
Update metrics host IP.
we do not specify it in old operator
from https://v0-19-x.sdk.operatorframework.io/docs/golang/legacy/monitoring/prometheus/ default is 0.0.0.0
this is part of the downstream PR https://github.com/red-hat-data-services/rhods-operator/pull/33
this will not automatically ships metrics, till: we apply promethusrules in manifests which are not available yet.
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/444
> Update metrics host IP

- components/codeflare/codeflare.go
- particially revert PR389
- CF does not need image to be used in manifests
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/384
> Revert: do not set imageParamMap for CF

- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Removing DSC version v1alpha1 from the CSV as it is being replaced by v1 without backward support.
> Removing DSC version v1alpha1 from the CSV

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- controllers/dscinitialization/monitoring.go
reopen this PR, even monitoring not applicable for downstream also the path in odh-manifests might be different, still useful to have logic in
ref downstream: https://github.com/red-hat-data-services/rhods-operator/pull/16
> Fix wrong monitoring and add logger

- components/dashboard/dashboard.go
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/466
for v2, we can get this out first. then update 
https://github.com/red-hat-data-services/odh-manifests/blob/master/odh-dashboard/consolelink/consolelink.yaml
then we will fix odh-deployer for v1 in another [PR](https://github.com/red-hat-data-services/odh-deployer/pull/379)
> Add support for consolelink section title for different cluster type

- README.md
- components/dashboard/dashboard.go
- components/workbenches/workbenches.go
- pkg/deploy/setup.go
- when dev/test mode, done by olm (make deploy) without CSV, platform return ""
- explicitly set if self-managed or managed than not odh
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/482
local image: push quay.io/wenzhou/opendatahub-operator:dev-2.8.999-1
manually update dashbord from enabled true to false and back to true in e2e-test DSC instance, pod created then removed and created again.
> Fix: explictly check platform is selfmanaged or managed

- apis/dscinitialization/v1/groupversion_info.go
introduced in https://github.com/opendatahub-io/opendatahub-operator/pull/488
it does not harm for current code base, since we do not have change in API, but it does generate one extra wrong `config/crd/bases/datasciencecluster.opendatahub.io_dscinitializations.yaml` locally when run `"make manifests"`
> Fix typo in groupname

- README.md
- components/README.md
- components/codeflare/codeflare.go
- components/component.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/modelmeshserving/modelmeshserving.go
- components/ray/ray.go
- components/workbenches/workbenches.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- pkg/deploy/deploy.go
- when manifestsUri is set in DSCSI spec, use image from it is setting
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/460
- also some fix for the enabled in workbench to not applyimageparams
local build quay.io/wenzhou/opendatahub-operator-catalog:v2.8.23-460
test on ray component, steps
- current `odh-mainfests ray `from `master` branch is set to use `quay.io/opendatahub/kuberay-operator:v0.5.0`
- add in CSV with a different tag 0.3.0
```
env:
- name: RELATED_IMAGE_ODH_KUBERAY_OPERATOR_CONTROLLER_IMAGE
value: "quay.io/opendatahub/kuberay-operator:v0.3.0"
```
- install operator and see pod is up with env set to v0.3.0 (from env RELATED_IMAGE_ODH_KUBERAY_OPERATOR_CONTROLLER_IMAGE)
-  login to terminal can check params.env
- use test branch …
> Add support for manifestUri to overwrite params.env images

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/monitoring.go
- controllers/dscinitialization/utils.go
- controllers/secretgenerator/secretgenerator_controller.go
- replace `context.TODO()` with `context.Context`
- replace` types.NamespacedName{Name: req.Name}` with `req.NamespacedName`
- explicit set rolebinding, configmap and networkpolicy type when create them
local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.8.21-0
rolebinding, configmap and networkpolicy are created
enable dashboard and workbench, can access
> Update: refactory

- CONTRIBUTING.md
Just a short document on what to install on a linux box to compile, test and deploy the operator.
> Adding docs on setting up a linux dev environment

- components/codeflare/codeflare.go
- components/dashboard/dashboard.go
- components/workbenches/workbenches.go
ref: https://issues.redhat.com/browse/RHODS-11706
**local ODH build image:** quay.io/wenzhou/opendatahub-operator-catalog:v2.9.5-11706
a bit difficult to test this, because i need a rhods subscription to test non-ODH case.
maybe easier to use this l**ocal rhods build image:**  quay.io/wenzhou/opendatahub-operator-catalog:v2.9.5-11706-2
> Fix: downstream codeflare has a different operator name than upstream

- README.md
- docs/DESIGN.md
- docs/Dev-Preview.md
- docs/troubleshooting.md
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/502
> Docs: add new troublshooting page + fix markdown format

- Makefile
to prevent `make image` that not pulling down new manifests
> Add: use --no-cache to prevent not pulling down to new layer

- components/workbenches/workbenches.go
related to https://github.com/opendatahub-io/opendatahub-operator/pull/521
when run e2e locally got error 
`error during resmap resources: must build at directory: not a valid directory: evalsymlink failure on '/opt/manifests/jupyterhub/notebook-images/overlays/additional/default' : lstat /opt/manifests/jupyterhub: no such file or directory]"}
`
> Fix: in e2e or dev test should not apply addon manifests

- components/workbenches/workbenches.go
when test downstream, got error: 
`2023-09-08T13:19:56Z	ERROR	controllers.DataScienceCluster	failed to reconcile workbenches on DataScienceCluster	{"instance.Name": "default", "error": "error during resmap resources: must build at directory: not a valid directory: evalsymlink failure on '/opt/manifests/notebook-images/overlays/additional/default' : lstat /opt/manifests/notebook-images: no such file or directory"}`
> Fix: downstream workbranch to get imageparams

- components/codeflare/codeflare.go
- components/kserve/kserve.go
- controllers/datasciencecluster/datasciencecluster_controller.go
[cherry-pick] from https://github.com/red-hat-data-services/rhods-operator/pull/51
- kserve only use images from quay.io, remove variables, ref https://github.com/opendatahub-io/opendatahub-operator/issues/503
- add comments to be more clear
- fix wrong path of reconcile manifests after params.env is updated cherry-pick from https://github.com/red-hat-data-services/rhods-operator/pull/51
> Fix and Cleanup: applyimageparams on kserve

- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- components/codeflare/codeflare.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/ray/ray.go
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
- main.go
- pkg/deploy/deploy.go
- tests/e2e/dsc_creation_test.go
- tests/e2e/helper_test.go
- similar to what we are doing for codeflare, add check on Kserve
- for code consistency, set to use "cli" instead of "client" in components, since some are calling `client.ObjectKey{}`
- create new function to check operatorCondition which is auto created once operator is installed and removed when operator is uninstalled.
- enabled e2e kserve component
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/434
**update with new commit:**
new test image: quay.io/wenzhou/opendatahub-operator-catalog:v2.9.5-497-4
install ODH operator, but no pipeline operator
operator reconcile with error
then install pipeline operator 
all done
**old test on first commit, can ignore below:**
test with: quay.io/wenzhou/opendatahub-operator:dev-2.8.31-1
test with no operators installed but …
> Add check on dependent operators on KServe 

- components/dashboard/dashboard.go
when in https://github.com/red-hat-data-services/odh-manifests/pull/446 the structure is changed, thus for ODH it does not matter for a missing params.env file but downstream need it to be swapped with midstream built image.
before this the file was located in the `Path` 
ref: https://issues.redhat.com/browse/RHODS-11814
https://github.com/red-hat-data-services/odh-manifests/blob/master/odh-dashboard/overlays/rhods/params.env
> Update path for downstream dashboard image to use

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/519
some of the permissions from https://github.com/red-hat-data-services/odh-manifests/blob/master/data-science-pipelines-operator/rbac/role.yaml is not there.
in v2, only when enable DSP they will be added, but if we want v2 works as v1, we need eg. get be there.
local build **quay.io/wenzhou/opendatahub-operator-catalog:v2.9.519**
> Fix: missing permission is needed when DSP is disabled, to keep same behavior as for v1

- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/utils.go
we do not have odh-admins group created automatically, and this has an error in dashboard
local test:quay.io/wenzhou/opendatahub-operator-catalog:v2.1.666
**before:**
**AFter**
**![Screenshot from 2023-09-14 14-21-33](https://github.com/opendatahub-io/opendatahub-operator/assets/915053/4a011452-70a1-4784-aef3-d83436478cd5)**
> Fix: missing odh-admins group

- Dockerfiles/Dockerfile
- Makefile
- README.md
- components/kserve/kserve.go
- get_all_manifests.sh
- leave notebook, modelmesh, monitoring as-is from odh-manifests
- the old implmenetation is to get all from odh-manifests, the new one is to only get above listed from odh-manifests, the rest are defined as a list in makefile.
- another difference is the kserve.  the old implementation gets its manifests from odh-manifests which is the "outcome" of kustomize build, the new implementation is to copy over from kserve git repo (which are the source of the odh-manifests part) so no need "base" in the path
- move fetch logic into `get_all_aminfests.sh`
- instruction  of how to fetch manifests has been added into README
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/424 
**UPDATES:**
new local build image: from 14th Sep  quay.io/wenzhou/opendatahub-operator-catalog:v2.9.424 …
> Update Dockerfile to pull manifests from different component repo

- components/codeflare/codeflare.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/modelmeshserving/modelmeshserving.go
- components/ray/ray.go
- components/workbenches/workbenches.go
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/monitoring.go
- pkg/deploy/deploy.go
- pkg/plugins/addLabelsplugin.go
- pkg/plugins/namespacePlugin.go
Hopefully last round before Service Mesh component :)
- cleans up deployment `func`s - reducing parameters
- unifies `func`s having the client passed to always be the first parameter
- uses `filepath.Join` instead of string concatenation when constructing manifests paths
`make test` and manual testing of `quay.io/maistra-dev/opendatahub-operator:dev-service-mesh` image
> chore: simplifies deployment funcs

- controllers/dscinitialization/utils.go
- revert it , need more namespace for PSI cluster
revert https://github.com/opendatahub-io/opendatahub-operator/pull/527
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/423
> Revert change for networkpolicy

- components/codeflare/codeflare.go
revert changes for https://github.com/opendatahub-io/opendatahub-operator/issues/510
tl;dr:  handling done in CF operator, wont require action from ODH operator
detail https://github.com/opendatahub-io/opendatahub-operator/pull/511/files
> Revert: change to delete CF resource is not required

- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- components/codeflare/codeflare.go
- components/workbenches/workbenches.go
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- get_all_manifests.sh
- pkg/deploy/deploy.go
ref to change in NBC: https://github.com/opendatahub-io/kubeflow/pull/173
related to https://github.com/opendatahub-io/opendatahub-operator/issues/424
- since we cannot and should not get the whole kubeflow source repo into our final image, so the "component/base" is actually split to two parts and copied into image as  "odh-notebook-controller" and "notebook-controller"
- which means, in the old "odh-manifests" way, we can keep using "odh-notebook-controller" but the new way need extra path to be handled in operator workbench components
- this PR also cleaned up some calls to ApplyImageParams(). for workbench ApplyImageParams() is only used in downstream and only for 2 controller images
> Update: nbc manifests transit from odh-manifests to kubeflow repo

- Dockerfile
- Makefile
- README.md
- get_all_manifests.sh
ref:  https://github.com/opendatahub-io/opendatahub-operator/issues/424
- wont create file `MANIFEST_VERSION` to store odh-manifests ref version
- wont have `tests/data/test-data.tar.gz` in final image
- simple dockerfile, to only support pull down from component git repo, not support local odh-manifests 
- only copy dashboard + dsp + workbench, the rest are from odh-manifests, including  promethus + odh-common + modelmesh
> Update v1 operator to use component repo for manifests not odh-manifests

- components/kserve/kserve.go
ref:  https://issues.redhat.com/browse/RHODS-12074
the original fix made in ODH https://github.com/opendatahub-io/opendatahub-operator/pull/504 was removed after code rebase , so it did not end into OHD main, and not sync down to RHODS main
> Fix: wrong image for odh-model-controller when enable kserve

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
see conversation: https://redhat-internal.slack.com/archives/C05NXTEHLGY/p1695810959718189?thread_ts=1695113073.646639&cid=C05NXTEHLGY
this will not directly solve the problem seen on odh-nightly, but we will need it once the docker build is fixed to use CRD from odh-dashboard incubation branch
> Add acceleratorprofiles from dashboard as new CRD

- Makefile
- config/crd/external/route.openshift.io_routes.yaml
- config/crd/external/user.openshift.io_groups.yaml
- config/crd/external/user.openshift.io_identities.yaml
- config/crd/external/user.openshift.io_useridentitymappings.yaml
- config/crd/external/user.openshift.io_users.yaml
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/dscinitialization_test.go
- controllers/dscinitialization/suite_test.go
- controllers/dscinitialization/utils.go
After latest merges EvnTest tests stopped working. This PR addresses the problems by:
- adds download of needed CRDs to `config/crd/external` when running `make manifests` target
- adds missing scheme installation in the test setup
- passes ns when creating UserGroup resource
- marks one test as Pending due to NetworkPolicies being disabled right now
`make test`
> fix: adds missing CRDs for k8s EnvTest

- controllers/dscinitialization/utils.go
ref  https://github.com/opendatahub-io/opendatahub-operator/issues/423
local build : 
http://quay.io/wenzhou/opendatahub-operator-catalog:v2.10.423-10
> Feature: add networkpolicy in dsci

- Makefile
> fix(make): removes duplicated e2e flag declaration

- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
- controllers/datasciencecluster/datasciencecluster_controller.go
In this PR, I would like to propose a streamlined approach to component reconciliation by leveraging Go's `reflect` package. This eliminates the necessity for manual reconciliation whenever a new component is introduced. As a result, we achieve consistent handling regardless of the number of components.
- smoke tested using [dashboard+workbenches DSC](https://gist.github.com/bartoszmajsak/89d71235e64c0c78bb65685ba95ae572). Custom controller image: `quay.io/maistra-dev/opendatahub-operator:dev-reflect`
> feat: uses reflect to reconcile defined components

- components/codeflare/codeflare.go
- components/component.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/modelmeshserving/modelmeshserving.go
- components/ray/ray.go
- components/trustyai/trustyai.go
- components/workbenches/workbenches.go
- pkg/deploy/deploy.go
ref: https://github.com/opendatahub-io/kuberay/pull/3/files#diff-acaa2de02231c3fc528b55d6d109904b65a42e2387eef38fa18bc12ba2dc279e
- only enable ray and codeflare. these are the two components use "namespace" in params.env for now.
- move `applyImageParam` into ReconcileComponent() to pass down` dsci.ApplicationNamespace`
-  rename  `ApplyImageParams()` to `ApplyParams()`
-  move SetImageParamsMap to component
related: https://github.com/opendatahub-io/opendatahub-operator/issues/600 
local build: quay.io/wenzhou/opendatahub-operator:dev-2.10.600-0
> feat(ray): pass down applicationNamespace to ray and codeflare in manifests

- controllers/datasciencecluster/datasciencecluster_controller.go
In the DSC reconciliation, the TrustyAI component is being reconciled after all sub-components are already reconciled.
Remove redundant TrustyAI reconciliation.
Tested locally with DSC creation with `trustyai` component.
> Remove redundant TrustyAI reconciliation

- apis/datasciencecluster/v1/datasciencecluster_types.go
- apis/dscinitialization/v1/dscinitialization_types.go
- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
dsc for DataScienceCluster
dsci for DataScienceClusterInitialization
fix:  https://github.com/opendatahub-io/opendatahub-operator/issues/642
local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.10.642
after install operator, check:
```
oc api-resources | grep opendatahub
odhapplications                                                              dashboard.opendatahub.io/v1                   true         OdhApplication
odhdocuments                                                                 dashboard.opendatahub.io/v1                   true         OdhDocument
datascienceclusters                   dsc                                    datasciencecluster.opendatahub.io/v1          false        DataScienceCluster
dscinitializations                    dsci …
```
> add(api): shortname for CRD

- components/ray/ray.go
- get_all_manifests.sh
- changes with new location of DW manifests:
- ray : https://github.com/opendatahub-io/kuberay/pull/3
part of : https://github.com/opendatahub-io/opendatahub-operator/issues/600
local build quay.io/wenzhou/opendatahub-operator-catalog:v2.10.600-99
> update(ray): new path to manifests

- components/kserve/kserve.go
- components/modelmeshserving/modelmeshserving.go
- get_all_manifests.sh
- Added model-mesh and odh-model-controller manifests to `get_all_manifests.sh` 
- added logic to allow kserve and model-mesh to share a singular odh-model-controller deployment 
The testing for this PR is to be done along with the testing for [this](https://github.com/opendatahub-io/odh-model-controller/pull/92) and [this](https://github.com/opendatahub-io/modelmesh-serving/pull/221) PR since they target the same set of overall changes. 
The ODH operator image has been built with the following changes : 
- odh-model-controller manifests are pre built from https://github.com/opendatahub-io/odh-model-controller/tree/remove_kserve_flag which has equivalent changes to this repo, except that it deploys the image `quay.io/vedantm/odh-model-controller:remove-kserve-flag` which contains the …
> add manifests for odh-model-controller and model-mesh

- components/README.md
- components/component.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- **Based on:** PRs #301 and #605.
- Provides a default no-op `Cleanup` method for each component.
- Utilizes `controllerutil` methods for finalizer management.
- Optimizes the DSCI controller: Now uses the `List` operation directly, mirroring the DSC controller's behavior and eliminating the previous `Get` then `List` approach.
In prow we trust.
> feat: adds finalizers to DSC and DSCI

- components/codeflare/codeflare.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- main.go
- pkg/deploy/deploy.go
- pkg/upgrade/upgrade.go
- tests/e2e/dsc_creation_test.go
- tests/e2e/dsc_deletion_test.go
This PR introduces following changes: 
- Updated tests to use `app.opendatahub.io` label instead of `app.kubernetes.io/part-of` label to get component deployments.  The reason we moved to our custom labels instead of `app.kubernetes.io/part-of`, is most manifests use this label as part of deployments and cannot be used to differentiate between odh and non-odh resources.
- Codeflare manifests have changed their default path, which was not updated in the codeflare component in operator. This resulted codeflare deployment failures
- Move creation of default DSC out of reconcile. As part of upgrade logic, we introduced creation of default DSC in reconcile function. This caused recreation of DSC instance after it was removed. Moved the default dsc creation out of reconcile. Also for ODH …
> Debug and fix e2e tests in CI

- controllers/dscinitialization/dscinitialization_test.go
Implements wait with timeout for DSCI to be actually deleted from the cluster as part of the test cleanup.
Otherwise, we might end up with DSCI not deleted yet when another test starts. This leads to failing/flaky tests - see https://github.com/opendatahub-io/opendatahub-operator/actions/runs/6655639303/job/18086337958?pr=605 for example
> fix: ensures cluster-wide resources are removed during test cleanup

- components/kserve/kserve.go
- get_all_manifests.sh
- kserve has moved from odh-manifests to kserve repo in OHD
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/579#issuecomment-1773319113
- cleanup download manifests parts
> update(kserve): manifests path from in-repo

- components/modelmeshserving/modelmeshserving.go
https://redhat-internal.slack.com/archives/C05NXTEHLGY/p1698757907709679?thread_ts=1698263859.245689&cid=C05NXTEHLGY
no need in ODH any more
think to just comment out first
and will removed the logic totally when downstream is in 2.5
so we do not get confused why sync code
unless we figure out where to get the modelmesh monitoring manifests from ODH, we cannot have the logic in modelmesh it will cause operator reconcile
> disable: modelmesh-monitoring

- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/645
**update**
new image quay.io/wenzhou/opendatahub-operator-catalog:v2.11.645-99
start up
**old**
test when created 2nd
DSCI instance "rhods-setup2"
build image:
quay.io/wenzhou/opendatahub-operator-catalog:v2.10.645-2
> remove: req.namespace is not used for DSC and DSCI

- .github/workflows/linter.yaml
`go.mod` ensures we use go1.19, so linter should have the same. 
We can simply read it from this file :)
> chore(gh): configures linter to reference go.mod for Go version

- components/workbenches/workbenches.go
relate to https://github.com/red-hat-data-services/kubeflow/pull/29
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/579
**this is backport from downstream logic and only add for downstream logic  which is already in place**
cherrypick kubeflow pr 29
local build:  quay.io/wenzhou/opendatahub-operator:dev-2.10.579-29
check params.env
> backport(workbench): support images in two path for downstream

- Dockerfiles/bundle.Dockerfile
- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- aligns make target to use the same commands as other tools
- reverts accidental changes in bundle metadata
See https://github.com/opendatahub-io/opendatahub-operator/pull/668#issuecomment-1787416762
Fixes #694
`make bundle`
> fix(make): ensures projects version of operator-sdk is used

- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/status/status.go
Report error in status if more than one DataScienceCluster installed
V2
- update `phase` to `phaseError` as well
- add reporting for DSCInitialization
- Installed 2 DSCs in the same namespace with different name
- Checked `oc describe datasciencecluster.datasciencecluster.opendatahub.io/<NAME>` for both clusters
Both clusters report like 
```
Status:
Conditions:
Last Heartbeat Time:   2023-11-01T08:33:42Z
Last Transition Time:  2023-11-01T08:32:20Z
Message:               only one instance of DataScienceCluster object is allowed. Update existing instance on namespace  and name ykaliuta.dsc2
Reason:                DuplicateDataScienceCluster
Status:                False
Type:                  ReconcileComplete
Last Heartbeat Time:   2023-11-01T08:33:42Z
Last Transition Time: …
```
> Report error in status if more than one DataScienceCluster installed

- controllers/dscinitialization/dscinitialization_controller.go
> chore: fixes typos in func names

- pkg/deploy/deploy.go
-  we covered the case when set component from Managed to Remvoe to not remove CRD (e.g notebook)
-  this is to cover the case when delete DSC CR , so if we do not set it when created at first then it wont get deleted when DSC CR is gone
fix https://github.com/opendatahub-io/opendatahub-operator/issues/723
live build: quay.io/wenzhou/opendatahub-operator-catalog:v2.11.723
first enable workbench and dashboard  then create workbench from dashboard
then delete DSC CR
eventually DSC CR gone, only workbench pods in cluster
> fix(crd): do not set ownerreference on CRD

- components/codeflare/codeflare.go
- components/component.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/modelmeshserving/modelmeshserving.go
- components/ray/ray.go
- components/trustyai/trustyai.go
- components/workbenches/workbenches.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/secretgenerator/secretgenerator_controller.go
- main.go
- pkg/upgrade/upgrade.go
> Recreate stale OauthClient resource

- pkg/feature/templates/servicemesh/base/smcp.tmpl
This disables automatic OpenShift routes creation.
Smoke testing: turning on Service Mesh and KServe with Serverless. Then, checking that no rejected routes are created in `istio-system` namespace.
> fix(ossm): disables service mesh routes generation

- apis/datasciencecluster/v1/datasciencecluster_types.go
- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- config/samples/featuretracker_v1_features.yaml
After a discussion with @anishasthana, it was discovered that the description of the CodeFlare component in the manifests is not up-to-date. The current description indicates that the CodeFlare Operator should be installed in advance, but in reality, it will be installed on the fly.
This PR updates the description
> Update codeflare component description

- components/kserve/kserve.go
- pkg/feature/feature.go
- pkg/feature/initializer.go
create new func `checkDepedentOps` in kserve
with mutlierr, we can be more clear with dependent operator(s) are not installed in one error message.
live build:
test when servicemesh operator is installed but serverless is not.
> fix(kserve): check on multiple depends operators if all pre-installed

- components/codeflare/codeflare.go
- components/kserve/kserve.go
creds to: @bartoszmajsak
follow up conversation from https://github.com/opendatahub-io/opendatahub-operator/pull/744/files#diff-52960d562b25c15c5b2e2531c0fcfe9b990715a0b9897e4fa9126d3832020add
> update: rewrite func to check operator

- config/manager/kustomization.yaml
- controllers/datasciencecluster/datasciencecluster_controller.go
- pkg/upgrade/upgrade.go
- tests/e2e/controller_setup_test.go
- tests/e2e/dsc_cfmap_deletion_test.go
- tests/e2e/dsc_deletion_test.go
The code responsible for cleaning up resources on cfg map presence was failing early due to operations on nil object leading to panic and restart of the pod making an impression that cleanup takes forever.
Related to #747
- create DSCI and DSC
- create config map in operator namespace as follows:
```
oc create configmap delete-self-managed-odh -n $OPERATOR_NS
oc label configmap/delete-self-managed-odh api.openshift.com/addon-managed-odh-delete=true -n $OPERATOR_NS
```
- delete DSC
- see ns (and other resources) being removed
> fix(cleanup): cleans up dependant resources

- pkg/feature/builder.go
By using client/config.GetConfig() we first check KUBECONFIG to only then fall back to a chain of alternatives including in-cluster config. This allows us to run ctrl binary locally and connect to cluster from outside - extra points for easier debugging :)
> fix(features): makes rest config loader more flexible

- pkg/feature/templates/servicemesh/base/smcp.tmpl
This should allow Service Mesh to run on any OpenShift flavor.
Fixes opendatahub-io/kserve#138
Manually, depoying Service Mesh with the operator.
> chore(mesh): Use third party service account tokens

- controllers/dscinitialization/utils.go
> chore: change log info for monitoring patch namespace

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
- this is causing MWC CR from kserve did not get cleanedup when kserve is Removed
- during debug the issue saw the error is also on Secret, therefore add "get" on it as well
ref https://issues.redhat.com/browse/RHOAIENG-908
live build: quay.io/wenzhou/opendatahub-operator-catalog:v2.5.788-1
after enable kserve and workbenches see Ownerreference is added
> fix(rbac): missing get verbs on MWC and Secret

- controllers/dscinitialization/dscinitialization_controller.go
fix: https://github.com/opendatahub-io/opendatahub-operator/issues/755
** newest test**
live build :  quay.io/wenzhou/opendatahub-operator:dev-2.5.755-2
**new test**
live build :  quay.io/wenzhou/opendatahub-operator:dev-2.5.666
- install operator
- get default DSCI CR "default-dsci" automatically
- manually create anothe DSCI CR "default-dsci2"
- check operator pod log
- check both DSCI CRs Message:
- 
**old test**
test on PR change:
- auto create `default-dsci `DSCI CR
- manual create `default` DSCI CR
- check any of the CR 
from operator pod
but no panic nor crashloop
> fix(nilpointer): when more than one DSCI CR in cluster

- controllers/dscinitialization/utils.go
- use a more generic label than bind to namespace name
they both point to the same namespace openshift-ingress
> chore: change label name for networkpolicy

- README.md
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
- controllers/datasciencecluster/datasciencecluster_controller.go
- tests/e2e/controller_setup_test.go
- tests/e2e/dsc_creation_test.go
- tests/e2e/helper_test.go
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/765
keep the same logic in the operator, only add env variable into CSV and set to true by default.
**new**
live build:  quay.io/wenzhou/opendatahub-operator-catalog:v2.6.766-3
**old**
live build:  quay.io/wenzhou/opendatahub-operator-catalog:v2.6.765
- after install operator, no DSC nor DSCI CR created
- then manually create DSC CR
- check DSC CR event, pod log
> update(dsci): do not create default DSCI CR if it is running in  ODH

- pkg/feature/builder.go
- pkg/feature/feature.go
- tests/integration/features/serverless_feature_test.go
This change removes tracker creation from the `Load()` phase in the builder, aligning with the principle that the builder's role is to set up features for execution. The creation of the associated tracker is more appropriately handled as the first step of the Feature's Apply phase.
It required small changes in the tests.
K8s testenv tests + manual happy path.
> chore: shifts FeatureTracker creation to Feature's Apply phase

- pkg/feature/conditions.go
When the Wait function is called to wait for e.g. the expected outcome of another operator, the operator might take longer then the initial interval time of 2s to create a pod. In this scenario the Wait function would get 0 Pods returned from the API Server to check the state of and assume all is done.
Ensure we at least get a pod count higher then 0 before we return successful. This gives the other operator our 5min deadline to create and start the pod(s).
Manually.
Verify that the Wait for ServiceMesh/Serverless pods take more then 2s (assuming it takes the Operator more then 2s to create the pod)
> fix: ensures Wait function waits for pods to appear in a given namespace

- controllers/dscinitialization/servicemesh_setup.go
- pkg/feature/builder.go
- pkg/feature/conditions.go
- pkg/feature/feature.go
- pkg/feature/initializer.go
- pkg/feature/manifest.go
- pkg/feature/raw_resources.go
- pkg/feature/servicemesh/conditions.go
- tests/integration/features/servicemesh_feature_test.go
If a Service Mesh Control Plane is not created, applying a network policy patch does not make sense. We could have fail earlier and report the actual problem instead of 
```
ERROR features error patching resource {"gvr": "http://maistra.io/v2, Resource=servicemeshcontrolplanes\n", 
"patch": "&{Object:map[apiVersion:maistra.io/v2 kind:ServiceMeshControlPlane metadata:map[name:basic namespace:istio-system] spec:map[security:map[manageNetworkPolicy:false]]]}\n", 
"json": "[...]\n", "error": "the server could not find the requested resource", "feature": "mesh-control-plane-no-default-network-policies"}
```
With this improvement, the error message is a bit more helpful:
```
ERROR features Failed to find the pre-requisite Service Mesh Control Plane CRD, please ensure Service Mesh Operator is …
```
> fix(service-mesh): ensures SMCP is available before patching network policy

- pkg/cluster/operations.go
- tests/e2e/controller_setup_test.go
- tests/e2e/dsc_cfmap_deletion_test.go
Based on https://github.com/opendatahub-io/opendatahub-operator/pull/805#discussion_r1454202693 
@VaishnaviHire @zdtsw Not sure what we want to do with `errors.WithStack`. Do we need it? Is it useful?
> chore: swaps errors.Wrap to fmt.Errorf

- controllers/dscinitialization/servicemesh_setup.go
- pkg/feature/templates/servicemesh/base/control-plane-disable-networkpolicies.patch.tmpl
- tests/integration/features/servicemesh_feature_test.go
Until we fix Serverless Operator we can't just disable those. Reverting #798 
Related issue: https://issues.redhat.com/browse/SRVKS-1189
> fix(service-mesh): reverts disabling network policy management

- components/kserve/serverless_setup.go
- pkg/feature/serverless/conditions.go
- pkg/feature/templates/serverless/serving-install/knative-serving.tmpl
- pkg/feature/templates/serverless/serving-net-istio-secret-filtering.patch.tmpl
This prevents KNative's net-istio pods from being OOMKilled in environments with a large number of Secrets.
This would patch a Managed installation. Custom installations would be left untouched.
Fixes: https://issues.redhat.com/browse/RHOAIENG-1467
* Do a build of the operator and deploy it:
```sh
make image-build IMG=$YOUR_CONTAINER_REPO
make deploy IMG=$YOUR_CONTAINER_REPO
```
* Create the default DSCI
```sh
oc apply -f config/samples/dscinitialization_v1_dscinitialization.yaml
```
* Create a KServe DSC
```yaml
apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
name: kserve-dsc
spec:
components:
dashboard:
managementState: Removed
datasciencepipelines:
managementState: Removed
codeflare:
managementState: Removed
ray:
managementState: Removed
kserve: …
```
> fix(serverless): Patch to enable Secret filtering in KNative Serving

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
This PR updates the TrustyAI API to make it consistent with the changes in: 
- https://github.com/trustyai-explainability/trustyai-service-operator/pull/169
- https://github.com/trustyai-explainability/trustyai-service-operator/issues/168
The TrustyAI `apiGroup` changed from `trustyai.opendatahub.io.trustyai.opendatahub.io/v1alpha1` to `trustyai.opendatahub.io/v1alpha1`.
This change is effective starting (and including) the releases:
- https://github.com/trustyai-explainability/trustyai-service-operator/releases/tag/v1.15.1
- https://github.com/trustyai-explainability/trustyai-explainability/releases/tag/v0.10.1
The image references in ODH should be also updated when merging this PR.
> update(trusty): Change TrustyAI `apiGroup`

- components/component.go
- components/trustyai/trustyai.go
- controllers/dscinitialization/monitoring.go
part of:
https://github.com/red-hat-data-services/rhods-operator/pull/161
https://github.com/red-hat-data-services/rhods-operator/pull/173
> [backport]trustyai: monitoring

- pkg/upgrade/upgrade.go
Jira Issue: https://issues.redhat.com/browse/RHOAIENG-965 
1. Create custom catalog source with image `quay.io/opendatahub/opendatahub-operator-catalog:v2.4.0
2. Update catalogsource to quay.io/vhire/opendatahub-operator-catalog:v2.7.0 to trigger upgrade
3.  Deployments are deleted and recreated
> RHOAIENG-965: Fix ODH Upgrade after label updates

- components/trustyai/trustyai.go
- this will be able to test live build if set devFlags on the Trustyai with downstream RHOAI build
- currently problem is the logic is missing on trustyai but applied to other components already
ref: https://github.com/opendatahub-io/opendatahub-operator/pull/659
> fix(devFlags): missing overwrite for the devFlag on component level

- Makefile
It's a bit tedeous to supply IMG for barely every make call so make it contstructed by Makefile itself based on the current user.
The default image name will be quay.io/$(USER)/opendatahub-operator:latest if USER environment variable is not empty.
It's still possible to amend the generation with variables:
```
IMAGE_OWNER - as before, uses value as quay.io space.
IMG_TAG - use the tag instead of `latest`. The variable name is
chosen because of IMG variable.
IMG - as before, use the complete image name
```
In the assignments '?=' replaced/used by '=' to not mess up with the environment by accident since the names are pretty generic (it's always possible to use `make -e` for those who wants).
It should not make problems with CI since it uses the names directly [1] using our csv [2]. To push …
> Makefile: generate default image name based on current user

- Makefile
- rename default target `all` to `default`. Sounds more appropriate since there are a lot of other jobs left.
- depend `default` from `lint` and `unit-test`
It looks like more appropriate default for developers.
Related: #696
> Makefile: run linter and unit tests from default target

- pkg/feature/manifest.go
`walkErr` is propagated as part of a recursive call when traversing a directory tree.
This adds a guard check and does not proceed if the error happens in the call chain.
Without this, the controller will `panic` in case of the wrong path defined for a manifest.
> fix(manifests): return walkErr immediately

- pkg/feature/feature.go
`client.Get()` will never return an error of `IsAlreadyExists` if the resource exists, it would rather return the object.
`IsAlreadyExists` error is only relevant with `client.Create`
Attempt to update any of the source data for a ConfigMap that uses the feature framework.
> fix: checks value instead of err when updating configmap

- Makefile
This is based on the assumption that calling the `make` default target ensures the repo is always in the desired state.
This includes:
- all generated artifacts are up-to-date with the code they are derived from
- code passes defined linter checks
- a subset of tests (fast tests) is passing
- no compilation errors
> fix(make): ensures manifests are generated as part of default target

- get_all_manifests.sh
The `release-0.11.1` branch is the new fallback branch for serving components. This is updating the fallback branch.
This helps on generating developer builds using the latest revision of model serving components.
Running the `get_all_manifests.sh` script and observing the manifests can be fetched correctly.
Also, invoking `make image-build` to check that the container image is built without issues.
> Bump Serving components to v0.11.1

- main.go
- pkg/upgrade/upgrade.go
Solves: https://issues.redhat.com/browse/RHOAIENG-2479 
This PR introduces logic to ensure the deprecated monitoring stack is deleted during operator upgrades in the managed environment 
Tested by doing a kustomize build to apply the deprecated monitoring stack (This is because a fresh install no longer installs the stack) 
- `git clone git@github.com:red-hat-data-services/odh-manifests.git` 
- `cd odh-manifests/modelmesh-monitoring/base`
- ` kustomize build --load-restrictor LoadRestrictionsNone . > temp.yaml` 
- `oc new-project redhat-ods-monitoring`
- `oc apply -f temp.yaml -n redhat-ods-monitoring` 
Built operator using 
- `docker build -f Dockerfiles/Dockerfile -t quay.io/vedantm/opendatahub-operator:monitoring_cleanup .` 
- `make deploy -e …
> add logic to ensure deprecated model monitoring stack is deleted

- controllers/dscinitialization/dscinitialization_controller.go
- we do not need to have this call for every reconcile
- the function does patching namespace on downstream logic everytime
- it is called in https://github.com/opendatahub-io/opendatahub-operator/pull/855/files#diff-c8a3eeefd24ebf5243ac88045140742b59124671a5ec221c43d2f9046dd3988dR199-R205 already
> update: remove duplicated createOdhNamespace call in DSCI

- pkg/feature/feature.go
- pkg/feature/feature_tracker_handler.go
- pkg/feature/types.go
This PR moves the location of each Feature's FeatureTracker into the base of the Feature struct, rather than storing it inside of Feature.Spec. This makes more sense than storing it inside of the spec, and makes future changes to how feature.Spec is implemented easier. 
Ensured that FeatureTracker related unit tests still work as expected and deployed the operator in CRC,
img: `quay.io/cgarriso/opendatahub-operator:dev-move-feature-tracker-location`
deploying a DSCI with `serviceMesh.managementState: Managed` and checking that the expected FeatureTrackers were still created and also deleted upon DSCI deletion.
> chore: move featuretracker out of feature.spec

- Makefile
- PROJECT
- bundle/manifests/opendatahub-operator-webhook-service_v1_service.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/default/kustomization.yaml
- config/default/manager_webhook_patch.yaml
- config/webhook/kustomization.yaml
- config/webhook/kustomizeconfig.yaml
- config/webhook/manifests.yaml
- config/webhook/service.yaml
- controllers/webhook/webhook.go
- controllers/webhook/webhook_suite_test.go
- main.go
- tests/e2e/controller_setup_test.go
- tests/e2e/dsc_creation_test.go
- tests/e2e/helper_test.go
Implement webhook which blocks creation of DataScienceCluster and DSCInitialization if one already exists.
- deploy operator
- create DataScienceCluster
- create another one.
Should get ```Error from server (Only one instance of DataScienceCluster object is allowed): error when creating "odh.yaml": admission webhook "operator.opendatahub.io" denied the request: Only one instance of DataScienceCluster object is allowed``` (odh.yaml is the file used for `oc create`). The same when creating/applying manifest with the different name.
> DSC, DSCI: add validating webhook

- components/kserve/kserve.go
- tests/e2e/dsc_creation_test.go
- tests/e2e/helper_test.go
https://issues.redhat.com/browse/RHOAIENG-2951
1. Install operator using catalogsource quay.io/vhire/opendatahub-operator-catalog:v2.7.0
2. Create default DSCI
3. Create DSC with following spec
```
kserve:
serving:
ingressGateway:
certificate:
type: SelfSigned
managementState: Unmanaged
name: knative-serving
```
> Fix Kserve Unmanaged Installation

- pkg/upgrade/upgrade.go
follow up changes in https://github.com/red-hat-data-services/rhods-operator/pull/188
**do not merge till we know PR 188 does not break regression**
Get confirm in Self-Managed, without this servicemonitor, everything is working and no more error in "ingest" https://issues.redhat.com/browse/RHOAIENG-859 
**still wait for confirm on managed cluster**
confirmed in https://issues.redhat.com/browse/RHOAIENG-859, by not having this Servicemonitor, nothing is breaking, we can proceed with this PR
> update: add cleanup for rhods-monitor-federation2

- OWNERS
- OWNERS_ALIASES
To expedite PR reviews and testing, added appropriate component owners to the repo.
> Update Owners and Owners-aliases

- pkg/feature/feature.go
Small fix for error noticed when playing around.
Due to size of the change, just checked the code compiles and runs.
> fix(feature): use correct error variable name

- components/dashboard/dashboard.go
- logic change to consolidate with downstream
ref: https://issues.redhat.com/browse/RHOAIENG-2993
need to go with ~~https://github.com/opendatahub-io/odh-dashboard/pull/2507~~  https://github.com/opendatahub-io/odh-dashboard/pull/2519
build with changes from "dgutride:odh-dashboard:dgutride/migrate-manifests" branch
**update**
latest live-build quay.io/wenzhou/opendatahub-operator-catalog:v2.8.2993-10
build with     ["odh-dashboard"]="lucferbux:odh-dashboard:rhoaieng-943:manifests:dashboard"
for downstream
odh live build quay.io/wenzhou/opendatahub-operator-catalog:v2.8.2993-0
rhoai live build:  quay.io/wenzhou/rhoai-operator-catalog:v2.8.2993-0
> feat(dashboard): use new manifests structure from ODH

- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- components/kserve/kserve.go
- components/kserve/kserve_config_handler.go
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
- docs/Dev-Preview.md
This change is to support Raw Deployments for Kserve. JIRA: https://issues.redhat.com/browse/RHOAIENG-3132 
This PR adds a field `DefaultDeploymentMode` to the Kserve spec in the DSC. The default value is `Serverless`, which introduces no changes in behavior. However, if the `DefaultDeploymentMode` is set to `RawDeployment`, the operator updates the configmap `inferenceservice-config` in the applications NS. The updates are as follows : 
- deploy["defaultDeploymentMode"] is set to match the value passed to the DSC since they both use the same enum
- ingress["disableIngressCreation "] is set to `true`  if the deployment mode is `RawDeployments`, otherwise it is `false` 
Changes tested against dev cluster by building and deploying `quay.io/vedantm/opendatahub-operator:rawdeployment` …
> allow setting default deployment mode for Kserve in DSC

- pkg/feature/templates/servicemesh/authorino/mesh-authz-ext-provider.patch.tmpl
- pkg/feature/templates/servicemesh/kserve/z-fix-jira-4192/kserve-predictor-authorizationpolicy.patch.tmpl
There are two misconfigurations being fixed:
* In the SMCP, the service hostname of Authorino was coded with `-authorization` suffix, but the right suffix is `-authorino-authorization`.
* In the `kserve-predictor` AuthorizationPolicy, the hardcoded `opendatahub-odh-auth-provider` provider name was used, but it should have been the template `{{ .AppNamespace }}-auth-provider`.
In `pkg/feature/feature.go` the patch manifests (i.e. the ones containing `.patch` in the filename) are always applied. Thus, the first bullet is solved by fixing the patch file that adds the `extensionProvider` to the SMCP.
For the second bullet, the faulty AuthorizationPolicy is created with a regular manifest template which is only applied if the resource does not exist. Thus, a patch manifest is added to properly …
> fix(authz): Fix broken external auth configuration

- components/README.md
- components/codeflare/codeflare.go
- components/component.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/kueue/kueue.go
- components/modelmeshserving/modelmeshserving.go
- components/modelregistry/modelregistry.go
- components/ray/ray.go
- components/trustyai/trustyai.go
- components/workbenches/workbenches.go
This is a simple pass-return method and does not seem to be used by any of the components with some customizations in place.
So I propose to remove it entirely from the codebase.
> chore: removes SetImageParamsMap from ComponentInterface

- apis/features/v1/features_types.go
- pkg/feature/feature.go
- sets Progressing condition to `False` at the end of Apply
- removes obsolete now `ProcessTemplates` phase
> fix: cleans up conditions of FeatureTracker

- components/README.md
- components/codeflare/codeflare.go
- components/component.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/kueue/kueue.go
- components/modelmeshserving/modelmeshserving.go
- components/modelregistry/modelregistry.go
- components/ray/ray.go
- components/trustyai/trustyai.go
- components/workbenches/workbenches.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- main.go
- pkg/monitoring/monitoring.go
- pkg/upgrade/upgrade.go
As we are already using `client.Client` interface we do not have to instantiate other typed clients to e.g. list resources using their own
funcs. Generic `client.Client` is sufficient for these needs.
Additionally this change adds ctx propogation for these calls.
> chore: remove the need of passing rest config

- components/dashboard/dashboard.go
ref: https://issues.redhat.com/browse/RHOAIENG-3760 
**NEW**  
new live build after rebase quay.io/wenzhou/opendatahub-operator-catalog:v2.9.884-2
`this build is using main branch from ODH odh-dashboard, since the old incubation is not updated so the consolelink.yaml not even exist there`
on ODH
**OLD**
live-build:  quay.io/wenzhou/opendatahub-operator-catalog:v2.9.884-1
> feat(dashboard): add consolelink for ODH

- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- controllers/dscinitialization/utils.go
- controllers/secretgenerator/secretgenerator_controller.go
- pkg/deploy/setup.go
- pkg/trustedcabundle/trustedcabundle.go
Instead of 
```
if apierrs.IsNotFound(err) {
return nil
}
return err
```
we can use
```
return client.IgnoreNotFound(err)
```
> chore: simpliflies handling of k8s not-found errors

- pkg/feature/servicemesh/resources.go
Add more global lookup configurations to the auth_refs CM.
`AUTH_PROVIDER` refers to the Provider name used in SMCP to configure ExtAuth. Used in e.g. AuthorizationPolicy objects. 
`AUTHORINO_LABEL` refers to the labelselector used by the Authorino service. Used in AuthConfig objects.
Manually
> feat: add additional auth_refs for global config

- components/kserve/kserve_config_handler.go
- components/kserve/servicemesh_setup.go
- pkg/feature/handler.go
- tests/integration/features/serverless_feature_test.go
There is currently no need to pass the entire Component struct, so keeping API smaller makes sense.
> chore(feature): passes component name instead of whole struct

- pkg/feature/feature.go
- pkg/feature/manifest.go
- pkg/feature/manifest_test.go
`RawManifest` describes better the purpose of the type, as it is a simple text file without any additional processing behavior.
> chore: renames base manifest type

- components/kserve/servicemesh_setup.go
- pkg/feature/templates/servicemesh/kserve/grpc-envoyfilter-temp-fix.tmpl
By adding this envoy filter, users can add a `protocol: grpconly` label to the manifests in order to prevent non-grpc traffic to reach grpc servers.
This workaround prevents certain grpc servers from stopping responding under certain conditions.
For more context, see https://issues.redhat.com/browse/RHOAIENG-165
> manifests: add grpconly label to apply global EnvoyFilter

- controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- pkg/trustedcabundle/trustedcabundle.go
update comments
- use ShouldInjectTrustedBundle than HasCABundleAnnotationDisabled in the call => even it is limited to application namespace, user might set to any reserved one in their DSCI CR
- change error in RemoveCABundleConfigMapInAllNamespaces
> chore: trustcabundle

- pkg/upgrade/upgrade.go
On upgrade, odhApplications do not get cleaned up and the operator pod throws following error
```
failed to find CR: %!w(*meta.NoKindMatchError=&{{dashboard.opendatahub.io odhapplications} [v1]})
```
Will include this in odh-2.9 release branch
> Fix cleanup of ODHApplications

- pkg/feature/manifest.go
- pkg/feature/manifest_test.go
The templates used in Feature SDK are not intended (at least right now) to provide conditional rendering like in Helm. Thus we should fail fast if the Feature's underlying map does not provide the key referred to in a template. 
This is achieved by passing the parsing option (missingkey=error) to built-in Golang templating.
> [!NOTE]
> This works out of the box with `struct`s but we should also fail when dealing with `map`s.
> feat(tmpl): fails when key does not exist

- .github/workflows/check-file-updates.yaml
- Makefile
- docs/api-overview.md
- add "diff" in the failed GH action to help understand problem
in https://github.com/elastic/crd-ref-docs/releases/tag/v0.0.11 it has the bug fix for a wrong rending content.
this is causing the current runs failing, 
+ add debug to help know if it is a false error:
from current incubation:
from my PR code:
failed GH action run with debug info:
want to revert "enum" part in the PR which indicates PR has change should be commited
> fix(gen): upgrades to crd-ref-doc generator to latest version

- Makefile
When juggling between branches golangci linter cache can have leftovers from the code that does not exist in the other branch.
This can lead to errors while running `make lint` as linter tries to check cached sources first.
This change cleans linter cache as part of clean target to ensure consistency.
Here's an example of invalid cache state leading to error:
```
WARN [runner] Can't process result by autogenerated_exclude processor: can't filter issue result.Issue{FromLinter:"ireturn", Text:"Entry returns interface (github.com/opendatahub-io/opendatahub-operator/v2/pkg/feature.DataProvider)", Severity:"", SourceLines:[]string(nil), Replacement:(*result.Replacement)(nil), Pkg:(*packages.Package)(0xc001343e00), LineRange:(*result.Range)(nil), …
```
> fix(make): cleans linter cache on clean

- .gitignore
- .golangci.yml
- Makefile
This update incorporates the `gci` tool into the `make fmt` command, aiming to improve the formatting of Go files and ensure that imports adhere to our established conventions.
Unfortunately, due to how `.golangci.yml` is defined, we are not able to just use `--disable-all --enable=gci` flags. This yields an error as we use `enable-all` and `disable` in the config file for linter.
To address this, the `golangci-lint` configuration is dynamically adjusted using the `yq` tool, which is now included in our toolchain.
This process creates a temporary configuration file specifically for `golangci-lint` execution, ensuring `gci`'s integration without altering the primary linting setup.
Furthermore, the generated temporary file is added to the `CLEANFILES` list, ensuring its removal when calling …
> feat(build): adds gci to go fmt target

- config/manifests/kustomization.yaml
Fix description patch
While running `make bundle` command, it automatically updates the csv in `bundle/manifests`. Because of the `name` the patch did not apply and it got replaced to `This will be replaced by Kustomize`. This PR fixes that issue.
Run `make bundle` command and see that the description does not change.
> (fix): Description patch during make bundle

- Makefile
* Go back to using `IMG ?=` rather than forcing the value with `IMG =`. This makes it easier to override the value of `IMG` for development, and also aligns it to how `BUNDLE_IMG` is assigned.
* Add `prepare` as dependency of the `undeploy` target. This is just for convenience, although when looking at the other targets, `prepare` may simply be a missing dependency in `undeploy`.
Using the Makefile :-)
> chore: Small Makefile fixes

- Makefile
GH unit-test failing with error:
```
mkdir -p /home/runner/work/opendatahub-operator/opendatahub-operator/bin
test -s /home/runner/work/opendatahub-operator/opendatahub-operator/bin/setup-envtest || GOBIN=/home/runner/work/opendatahub-operator/opendatahub-operator/bin go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
go: downloading sigs.k8s.io/controller-runtime/tools/setup-envtest v0.0.0-2024032210[5](https://github.com/opendatahub-io/opendatahub-operator/actions/runs/8390354373/job/22978408816?pr=933#step:4:6)421-affb9[6](https://github.com/opendatahub-io/opendatahub-operator/actions/runs/8390354373/job/22978408816?pr=933#step:4:7)[7](https://github.com/opendatahub-io/opendatahub-operator/actions/runs/8390354373/job/22978408816?pr=933#step:4:8)08000
go: downloading …
```
> fix(test): pin version not latest which just introduced to use go 1.22

- controllers/status/status.go
After introducing validating webhook these are not needed anymore.
> chore: removes unused statuses

- pkg/feature/manifest.go
- pkg/feature/manifest_test.go
- tests/integration/features/manifests_int_test.go
This PR removes (for now) `KustomizationManifest`. Reason being this comment from review of #932 
```
In a retrospect, I think making it available right now might be a bit premature. We do not have the whole thing in parity with deploy.go (especially in terms of feature create/update/remove path from the reconcile perspective). At the time we start looking at how to unify the approach we can bring this code back.
```
Note that removing this should be temporary, as Kustomize support with `Feature` should at some point be fully fleshed out. 
Note:  this is not yet used anywhere in the codebase, removing it is safe.
> chore: remove kustomizationManifest + tests

- components/dashboard/dashboard.go
- jupyter-install-python-packages jupyter-update-server-settings jupyter-use-s3-bucket-data jupyter-view-installed-packages  OdhDocument
- jupyter OdhApplication
- deploy-python-model and create-jupyter-notebook OdhQuickStart
to fix odh-nightly build with missing default resource
https://redhat-internal.slack.com/archives/C05NXTEHLGY/p1711380633005149
> fix(dashboard): add app for ODH base to deploy

- get_all_manifests.sh
With the addition of the `dev` [branch](https://github.com/opendatahub-io/kuberay/tree/dev) introduced in ODH/Kuberay we need the ODH Operator to point to it.
Changed `master` to `dev` for Ray in `get_all_manifests.sh`
Run the `get_all_manifests.sh` script and the KubeRay manifsts should be cloned in the odh-manifests folder.
> Changed ODH/Kuberay to point to dev branch

- pkg/cluster/cluster_operations_int_test.go
- pkg/cluster/resources.go
- pkg/feature/servicemesh/resources.go
Previously the desired configmap state was overwritten by existing version fetched using `client.Get`.
This bug resulted in configuration not being propagated to configs maps which are created to share configuration with other controllers residing in the application namespace.
Includes test which fails without the patched function.
> fix: properly updates config map

- components/kserve/kserve.go
- components/kserve/servicemesh_setup.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/capabilities.go
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/servicemesh_setup.go
- controllers/status/reporter.go
- controllers/status/status.go
- pkg/feature/conditions.go
- pkg/feature/handler.go
> [!IMPORTANT]
> There are automated tests missing and they will be added to this PR shortly, opened it for code review to first gather feedback about the solution as such.
> [!WARNING]
> Requires https://github.com/opendatahub-io/odh-model-controller/pull/183 merged to work end-to-end. See `How Has This Been Tested?` part to know which images to use before this PR lands in the main branch.
When Authorino Operator is missing the reconcile will continue without throwing an error about missing pre-requisite and asking user to install it. This fact is instead reported as DSCI.status condition:
```yaml
- lastHeartbeatTime: "2024-04-04T16:32:22Z"
lastTransitionTime: "2024-04-04T16:24:38Z"
message: Authorino operator is not installed on the cluster, skipping authorization capability
reason: …
```
> feat(authz): conditionally enables authorization capability

- components/modelregistry/modelregistry.go
Create dedicated namespace for Model registry to use.
Current this namespace will be used for ODH and downstream but we will have a followup PR to set the correct namespace and logic only for downstream
ref https://issues.redhat.com/browse/RHOAIENG-5027
- create a NS for MR once the component is enabled
- this NS wont get deleted even MR component is set to Removed/Unmanagaedor ODH operator is being uninstalled
result to a namespace with similar labels:
```
labels:
kubernetes.io/metadata.name: odh-model-registries
...
```
> feat(mr): create namespace for Model Registry

- pkg/deploy/deploy.go
previous commit has a if logic error
we should not add ownership when it is CRD or odhdashboardconfig
the error is causing:
- odhdashboardconfig CR still has ownership set to it
- CRD also gets ownership set on them
ref: https://issues.redhat.com/browse/RHOAIENG-3963
live build quay.io/wenzhou/rhods-operator-catalog:v2.9.3963-419
> fix(deploy): wrong logic in if when apply ownership

- pkg/gvk/gvk.go
- pkg/upgrade/upgrade.go
Remove deprecated dashboard resources, watson-studio
Jira: https://issues.redhat.com/browse/RHOAIENG-4764
- Install odh-2.9.0
- Deploy odh-manifests/dashboard/overlays/apps/base/watson
- Check odhapplications.dashboard.opendatahub.io, odhdocuments.dashboard.opendatahub.io and odhquickstarts.console.openshift.io in opendatahub namespace, watson objects exist
- Deploy PR version
- Restart operator pod
- Observe that watson objects do not exist anymore
> pkg/upgrade: remove watson-studio dashboard application

- tests/e2e/controller_setup_test.go
- tests/e2e/dsc_cfmap_deletion_test.go
- tests/e2e/dsc_deletion_test.go
- only test negative case when set to false: resource should remain
- if we test postivie case, we wont get prow pod log after csv is deleted
e2e flow:
- creation   => no changes in PR
- create DSCI
- create more DSCI, should fail
- create DSC
- create more DSC should fail
- ....
- test configmap case  => change in PR , previous as positive case to delete all, now negative should not delete
- set to configmap but not enable deletion label
- namespace still exists (MR namespace wont get label)
- test deletion case  => move from 2nd test suite to the 3rd one
- check all components are enabled first
- delete DSC CR
- loop thro components: see their resources are all gone.
- delete DSCI CR
> fix(e2e): do not test deletion configmap is true

- pkg/deploy/deploy.go
This is a very targeted change for Kserve component. The PR adds ability to configure `resources` field in Deployments objects of the component.
Eventually we will move to a generalize solution to whitelist fields for all components. See [[wip]ADR](https://github.com/opendatahub-io/architecture-decision-records/pull/32)
Jira Issue: https://issues.redhat.com/browse/RHOAIENG-280
1. Deploy custom operator image
2. Set Kserve component to Managed in DSC
3. Update `resources` field in `kserve-controller-manager` Deployment
4. Verify values are not overwritten
5.  Update `resources` field in  Deployment of any other component
6. Verify values are overwritten
> Add Ability to configure resources in Kserve

- config/manager/manager.yaml
Add Opendatahub-operator pod selector label. Same is used in ODS_CI test suits to validate operator pod is running.
https://github.com/vaibhavjainwiz/ods-ci/blob/support_odh/ods_ci/tasks/Resources/RHODS_OLM/install/oc_install.robot#L77
Similliar label is already a part of rhods-operator.
I am doing this change as an effort to enable ODS_CI testsuit for ODH testing as well.
https://issues.redhat.com/browse/RHOAIENG-5321
> Add Opendatahub-operator pod selector label

- components/datasciencepipelines/datasciencepipelines.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/status/status.go
- main.go
Jira Issue: https://issues.redhat.com/browse/RHOAIENG-4570
This PR introduces changes to handle existing Argo workflows for new install and upgrade. Following is the expected workflow 
```
For version n
1. New Install
- Argo Workflow exists
- All components in n deployed successfully except DSP
- New Dashboard(n) shows warning banner
2. Upgrade from n-1 --> n
- Argo workflow exists and DSP is enabled
- Do not upgrade any component. All components in (n-1)
- Dashboard will not show any warning
- DSC(Operator) will trigger events stating remove Argo or disable DSP to upgrade to new version
- Note, (n-1) manifests are no longer managed here
``` 
1. Deploy [Workflow CRD ](https://github.com/opendatahub-io/data-science-pipelines-operator/blob/v2.0.1/config/argo/crd.workflows.yaml).
2. Deploy …
> Add check for existing Argo Workflows

- components/datasciencepipelines/datasciencepipelines.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- pkg/deploy/deploy.go
- pkg/metadata/annotations/annoations.go
- when label has value "true" means Argo CDR is from DSPv2
- if label has value "false" could be a pre-exist cluster CRD
https://issues.redhat.com/browse/RHOAIENG-4570
based on https://github.com/opendatahub-io/opendatahub-operator/pull/955
> fix(dspv2): label should be check on existance and value as well

- pkg/cluster/cluster_operations_int_test.go
- pkg/cluster/meta.go
- pkg/cluster/resources.go
- pkg/feature/servicemesh/resources.go
This is a follow-up PR to #948.
One thing which I missed was updating labels if the config map already existed. This is now ensured for both `Create` and `Update` paths and captured in tests.
In addition, `CreateOrUpdateConfigMap` takes a pointer to a ConfigMap "prototype" instance, where you can define `ObjectMeta` and `Data`. This simplifies function signature and allows you to pass an anonymous struct when you do not want to use the return value later. Previously this had to be ignored by using `_` as a variable name.
- `ConfigMap.ObjectMeta.[Name|Namespace]` is required as it will be used for the initial `Get` call. It returns an error otherwise. Previously both `name` and `namespace` string params were not validated before invoking k8s client.
- `.Data` keys will be merged if …
> fix(cfgmap): simplifies create/update (again!)

- pkg/cluster/resources.go
- tests/integration/features/fixtures/cluster_test_fixtures.go
- adds godoc for `CreateOrUpdateConfigMap` func
- removes unused `GetConfigMap` func in the test code.
> chore: removes dead code and adds godoc

- tests/e2e/dsc_creation_test.go
- tests/e2e/dsc_deletion_test.go
After installing serverless/servicemesh operators there is no exception to handle kserve so use recently exported dsc.GetComponents() method and handle all the component pods checks (creation and deletion) the same way inside loops.
No functional changes except generated test names for component pod validation are changed (generated now using GetComponentName()).
> tests: e2e: use loop to iterate over components

- controllers/datasciencecluster/datasciencecluster_controller.go
ref: https://issues.redhat.com/browse/RHOAIENG-415
local build quay.io/wenzhou/opendatahub-operator-catalog:v2.10.415-1
> fix(status): do not set Unknown back to component for every loop on reconcile

- components/dashboard/dashboard.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/monitoring.go
- controllers/secretgenerator/secretgenerator_controller.go
- main.go
- pkg/cluster/cluster_config.go
- pkg/upgrade/upgrade.go
we have context defined and pass from upper caller, this is just to make sure the ones we set to TODO can be using ctx
> chore: passing down ctx in the chain than placeholder TODO()

- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/status/status.go
- in most of the case, DSC CR should have Degraded as False if that was caused by subcomponent reconcile failure (component or dependencies)
- in the case of a missing/invalid DSCI, DSC CR is totally malfunction,
related to https://issues.redhat.com/browse/RHOAIENG-3913 but not to fix the Degraded in the case of "failed to get dependency of component"
local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.10.3913
- install operator
- do not create DSCI CR, only create DSC CR with default content
- check DSC CR status
here Degraded is True
- go create DSCI CR
- wait till all Managed components finished reoncile
- check DSC CR status again
here Degraded is False
> feat(status): change Degraded status from False to True if no DSCI CR

- components/kserve/kserve_config_handler.go
- both depedent operators have been check in configureServerlessFeatures
we have checkDependentOperators to check both servicemesh and serverless operator
but also in configureServerlessFeatures we have 
- serverless.EnsureServerlessOperatorInstalled		
- servicemesh.EnsureServiceMeshInstalled,
> chore(cleanup): remove checkDependentOperators as duplicated logic

- pkg/upgrade/uninstallation.go
the function was firstly introduced in RHOAI 2.7.0 https://github.com/opendatahub-io/opendatahub-operator/pull/796 but if this is conflicted with Addon logic we should not have it for Managed cluster.
ref https://issues.redhat.com/browse/RHOAIENG-1452 (https://issues.redhat.com/browse/RHOAIENG-1452?focusedId=24640022&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24640022)
> fix(uninstallation): do not delete subscription on Managed offering

- pkg/feature/servicemesh/resources.go
Small change, adding the namespace authorino is deployed to into our `auth-refs` configmap for reference. 
Tested manually on CRC with image `quay.io/cgarriso/opendatahub-operator:dev-add-auth-ns-refs`
Ensured that when no auth namespace was specified in created DSCI with appNamespace: `opendatahub` that the name in the configmap was default (`opendatahub-auth-provider`) and that when the auth namespace was specified in created DSCI then the specified namespace was present in the configmap.
> chore: add auth namespace to auth cfgmap

- main.go
- pkg/upgrade/upgrade.go
- in the current v2 version, we only support from v2.4 and so on as From for upgrade
- old kfdef CRs will be either cleanedup by v2.4 as upgrade or not even in the cluster from clean installation
- move createdefaultDSC caller into main
- move unsetownerreference into cleanupexistingresource
- this will help to cleanup package dependency in downstream
- internal thread https://redhat-internal.slack.com/archives/C05QFFW56HL/p1714054539268969?thread_ts=1714029372.306169&cid=C05QFFW56HL
ref: https://issues.redhat.com/browse/RHOAIENG-6571
local build quay.io/wenzhou/opendatahub-operator-catalog:v2.10.0-13
> chore(cleanup): remove cleanup functions for upgrade from v1 to v2

- pkg/cluster/resources.go
- pkg/upgrade/upgrade.go
After removing leader election, operator fails to start if it is instructed to create default DSCI. Looks like webhook is not ready by the time:
```
create default DSCI CR.
{"level":"error","ts":"2024-05-13T09:25:58Z","logger":"setup","msg":"unable to create initial setup for the operator","error":"Internal error occurred: failed calling webhook \"operator.opendatahub.io\": failed to call webhook: Post \"https://opendatahub-operator-controller-manager-service.oo-2ts9m.svc:443/validate-opendatahub-io-v1?timeout=10s\": no endpoints available for service \"opendatahub-operator-controller-manager-service\"","stacktrace":"main.main.func1\n\t/workspace/main.go:200\nsigs.k8s.io/controller-runtime/pkg/manager.RunnableFunc.Start\n\t/remote-source/operator/deps/gomod/pkg/mod/sigs.k8s.io/controller-r …
```
> upgrade: retry if default DSCI creation fails

- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
- pkg/cluster/resources.go
- pkg/upgrade/upgrade.go
> Sync odh-2.12

- .github/actions/update-manifest-branches/action.yaml
- .github/scripts/get-component-release-notes.js
- .github/scripts/get-release-branches.js
- .github/scripts/update-manifests-tags.sh
- .github/scripts/update-versions.sh
- .github/scripts/validate-semver.sh
- .github/scripts/wait-for-checks.sh
- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
- Makefile
A set of github actions/ scripts to automate the entire release process in github.
This change enables us to automate the odh release process through a set of github actions and scripts.
A detailed explanation can be found [here](https://docs.google.com/document/d/1cmMNGCKU9r4HUPtR16g-dqHL7UqPBDIpE72pXRWb-FA/edit).
> ODH release automation

- components/kserve/kserve.go
Jira: https://issues.redhat.com/browse/RHOAIENG-7312
kserve depends on odh-model-controller which it starts by deploying
manifests of Dependent Operator. The controller behaviour depends of
configuration (authorino) which is later deployed by configuring
servicemesh features. Here is a race, there are 2 checks in the
odh-model-controller for the presence of AuthorizationPolicy (which
is deployed by servicemesh configuration):
1) to add a type to the schema
2) to watch the objects of that type.
If the object appears in between odh-model-controller complains:
```
2024-05-16T06:46:03Z ERROR Reconciler error {"controller": "inferenceservice", "controllerGroup": "serving.kserve.io", "controllerKind": "InferenceService", "InferenceService": {"name":"xf","namespace":"single-model-test"}, …
```
>  kserve: configure servicemesh before deploying manifests

- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- components/component.go
- components/kueue/kueue.go
- components/trainingoperator/trainingoperator.go
- components/trustyai/trustyai.go
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- docs/api-overview.md
- we have a bit lag for maintain the devFlags since new componets added and path changed
- contextDir is not necessary if it has default value
ref: https://issues.redhat.com/browse/RHOAIENG-6882
> fix: wrong path when use devFlag + wrong default value + special name in TrustyAI

- pkg/deploy/deploy.go
Jira Issue: https://issues.redhat.com/browse/RHOAIENG-7401 
This PR also refactors the `manageResource` function.
**Testing Steps:**
1. Deploy a clusterwide resource without operator. E.g (Kuberay [clusterrole](https://github.com/opendatahub-io/kuberay/blob/dev/ray-operator/config/rbac/role.yaml))
2. Deploy operator
3. Create DSC with Kuberay set to Removed
4. Verify Kuberay clusterrole is not removed
5. Verify `metadata.managedFields must be nil` error is not triggered.
> Fix metadata.managedFields must be nil error in DSC

- components/codeflare/codeflare.go
- components/kserve/servicemesh_setup.go
- controllers/dscinitialization/servicemesh_setup.go
- pkg/cluster/operator.go
- pkg/deploy/deploy.go
- pkg/feature/conditions.go
- pkg/upgrade/uninstallation.go
They do not belong to `pkg/deploy` as they are about reading/writing cluster resources rather than deploying resources.
I also think `pkg/deploy/deploy.go` should be reviewed and responsibilities split even further, as now it's still doing both kustomize manifests deployments and cluster resources manipulation which were added lately.
This change is stacked PR which unblocks us from cyclic import on our end :)
> chore: moves operator/subscriptions funcs to pkg/cluster

- components/dashboard/dashboard.go
dashboard removed modelserving path and this breaks odh incubation build.
code has been synced to downstream so the change is for both ODH and downstream
ref: https://github.com/opendatahub-io/odh-dashboard/pull/2706
local build quay.io/wenzhou/opendatahub-operator:2.12.1
> feat: remove modelserving from dashboard manifests

- pkg/cluster/cluster_config.go
- pkg/cluster/gvk/gvk.go
- pkg/upgrade/uninstallation.go
GetClusterServiceVersion() may return nil error and nil pointer. On one hand it's ok to check object for nil in not found condition but it's a bit counter intuitive to have err nil when there is acutally "not found"
It caused a problem in GetVersion where this nil condition was not checked.
Refactor it to return the error and handle it properly.
> cluster_config: make GetClusterServiceVersion return NotFound error

- main.go
- we see throttling in some clusters, this is just to uplift the default value
- this could help in the later call e.g CleanupExistingResource and UpdateFromLegacyVersion but probably wont help that much for GetPlatform in main.go
> feat: increase QPS and Burst for client

- components/dashboard/dashboard.go
- components/kserve/kserve.go
- components/modelmeshserving/modelmeshserving.go
- components/modelregistry/modelregistry.go
- components/workbenches/workbenches.go
- controllers/dscinitialization/monitoring.go
- pkg/cluster/cluster_operations_int_test.go
- pkg/cluster/resources.go
- pkg/feature/resources.go
- pkg/feature/servicemesh/conditions.go
- pkg/feature/servicemesh/resources.go
- tests/integration/features/manifests_int_test.go
- tests/integration/features/resources_int_test.go
context should be determined by the caller and propagated down the call chain.
> chore: Open up util functions for context propagation

- pkg/cluster/cluster_operations_int_test.go
- pkg/cluster/meta.go
- pkg/feature/feature.go
- pkg/feature/servicemesh/conditions.go
- pkg/feature/servicemesh/resources.go
This PR changes the way that `OwnerReference`s are added to resources created by Features. Previously, we were calling `unstructured.SetOwnerReferences` on objects to add the ownerReference to the relevant resources. This function was not appropriate for our usage, as it sets the ownerReferences on the object by replacing the object's OwnerReferences, potentially losing existing OwnerRefs that the object may have.
The PR changes it so we now call `controllerutil.SetOwnerReference(owner, obj, scheme)` which upsert's the owner into the object's OwnerReferences.
This sets up for a follow-up PR adding the relevant Owning DSC/DSCI to resources marked as Managed() in the FeatureBuilder.  
Ensured preexisting unit test checking ownerReferences still functioned, deployed operator with changes …
> chore: append ownerRef to resources owned by Features

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
- since we already have these resource for create, list, delete etc, no harm to add get on them
related to some offline discussion for the error seen recently:
`"buildconfigs.build.openshift.io "rstudio-server-rhel9" is forbidden: User "system:serviceaccount:redhat-ods-operator:redhat-ods-operator-controller-manager" cannot get resource "buildconfigs" in API group "build.openshift.io" in the namespace "redhat-ods-applications"`
root cause has not been identify, but should be no harm to have all our  resource with get permission.
> add: get permission on resources

- pkg/deploy/deploy.go
- for Removed, resource wont get removed since CRD not exist, resource wont exists as well.
- thanks @ykaliuta pointed to the error for this case
ref: https://issues.redhat.com/browse/RHOAIENG-8297
> fix: when delete resource if no CRD in the cluster

- pkg/deploy/deploy.go
Avoid returning (nil, nil), convert error if CRD not present to NotFound and handle them in the caller code.
Avoid checking for found == nil but handle only error code.
This is more idiomatic and less error prone.
ref: https://issues.redhat.com/browse/RHOAIENG-8297
> deploy: refactor getResource to return NotFound for both cases

- components/kserve/feature_resources.go
- components/kserve/serverless_setup.go
- components/kserve/servicemesh_setup.go
- controllers/dscinitialization/feature_resources.go
- controllers/dscinitialization/servicemesh_setup.go
- pkg/feature/builder.go
- tests/integration/features/manifests_int_test.go
- tests/integration/features/resources_int_test.go
- tests/integration/features/servicemesh_feature_test.go
Minor refactoring
- Source is already used elsewhere in Feature DSL, so we might want to avoid confusion
- Location fits the purpose of this field better
by running `make`
> chore: renames manifests source to location

- main.go
- pkg/upgrade/upgrade.go
Create DSC the same way as DSCI to make it working with webhook
> Dsc creation postpone

- config/crd/external/operators.coreos.com_operatorconditions.yaml
- controllers/dscinitialization/suite_test.go
- pkg/cluster/cluster_config.go
Jira: https://issues.redhat.com/browse/RHOAIENG-8483
Depending of the way operators installed CSVs can be seen in all
namespace so listing of them causes producing N * M results (where N
is number of namespaces and M is number of CSVs) which is not
scalable in general and in practice causes timeouts on such large
clusters.
The function basically checks if ODH or RHOAI operator installed and
there is already such function in the package, OperatorExists(). So,
reuse it.
> cluster: GetPlatform: replace CSV list with OperatorExists calls

- components/codeflare/codeflare.go
- components/component.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/kueue/kueue.go
- components/modelmeshserving/modelmeshserving.go
- components/modelregistry/modelregistry.go
- components/ray/ray.go
- components/trainingoperator/trainingoperator.go
- components/trustyai/trustyai.go
- components/workbenches/workbenches.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- go.mod
- get in DSC and pass into compoment
ref : https://issues.redhat.com/browse/RHOAIENG-8483
> chore: remove duplicated GetPlatform call in each component

- get_all_manifests.sh
The GITHUB_URL was set to https://github.com/ (note the trailing slash)
which causes the script to fail in certain environment where git is
configured to rewrite the url i.e. to always use the ssh protocol:
```
[url "git@github.com:"]
insteadOf = https://github.com
```
- `get_all_manifests.sh` script executed with vanilla git config
- `get_all_manifests.sh` script executed with git url rewriting
> chore: fix remove trailing slash from GITHUB_URL

- README.md
- apis/infrastructure/v1/cert_types.go
- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- config/rbac/role.yaml
- config/samples/datasciencecluster_v1_datasciencecluster.yaml
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/datasciencecluster/kubebuilder_rbac.go
- docs/api-overview.md
- main.go
- pkg/cluster/cert.go
- pkg/feature/cert.go
- pkg/feature/serverless/loaders.go
- pkg/feature/serverless/resources.go
- tests/e2e/controller_setup_test.go
- tests/e2e/dsc_creation_test.go
- tests/e2e/helper_test.go
- tests/integration/features/serverless_feature_test.go
Jira Issue: https://issues.redhat.com/browse/RHOAIENG-4221
> Add support for default Ingress Cert

- pkg/cluster/cert.go
- pkg/feature/serverless/loaders.go
- pkg/feature/serverless/resources.go
- tests/e2e/dsc_creation_test.go
- tests/integration/features/serverless_feature_test.go
PR #1022 promoted knative default secret name as the default for the entire platform as part of the `cert.go` move. This can be confusing, therefore this change makes it local to kserve again.
Follow-up to #1022
ref: https://issues.redhat.com/browse/RHOAIENG-4221
> fix: makes default knative secret local for serverless

- apis/dscinitialization/v1/dscinitialization_types.go
- apis/dscinitialization/v1/zz_generated.deepcopy.go
- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- components/kserve/kserve.go
- components/kserve/servicemesh_setup.go
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
- controllers/dscinitialization/dscinitialization_test.go
- controllers/dscinitialization/servicemesh_setup.go
- controllers/webhook/webhook_suite_test.go
- docs/api-overview.md
- pkg/feature/builder.go
- pkg/trustedcabundle/trustedcabundle.go
- pkg/upgrade/upgrade.go
- tests/e2e/dsc_creation_test.go
- tests/e2e/helper_test.go
- tests/integration/features/fixtures/cluster_test_fixtures.go
- tests/integration/features/servicemesh_feature_test.go
- change trustCABundle to pointer, so if not set it is the same as set to Removed
- change serviceMesh to pointer too,  so if not set it is the same as set to Removed
- also include a fix in e2e test which set to use the wrong component name
ref : https://issues.redhat.com/browse/RHOAIENG-6295 
When user install operator from OperatorHub UI it is not a problem, the default fields are added there by CSV
When user manually create DSCI via CLI, they might not know if any new fields have been added into release.
e.g  a mini config of DSCI will cause operator crash
```
apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
name: default-dsci
spec:
applicationsNamespace: opendatahub
monitoring:
namespace: opendatahub
```
NEW:
live-build …
> fix(DSCI): change serviceMesh and trustCAbundle to pointer type

- components/datasciencepipelines/datasciencepipelines.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/status/status.go
I believe the top level `status.go` is intended for general purpose funcs to report status/conditions, not component specific ones. 
This PR moves Argo status func to `pipelines` component where `ArgoWorkflowCRD` is also defined.
> chore: moves ArgoCD conditions to pipelines component

- components/kserve/kserve.go
- components/kserve/kserve_config_handler.go
- components/kserve/servicemesh_setup.go
We were passing instance of `client.Client` to the functions that don't need it. Most likely copy-paste mistake. 
This PR cleans it up.
> chore: removes unused client parameter

- .github/workflows/linter.yaml
- .golangci.yml
- Makefile
- components/kserve/kserve_config_handler.go
- controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/secretgenerator/secret.go
- controllers/secretgenerator/secretgenerator_controller.go
- controllers/status/reporter.go
- pkg/cluster/resources.go
- pkg/deploy/deploy.go
- pkg/feature/builder.go
- pkg/feature/feature_tracker_handler.go
- pkg/feature/manifest.go
- pkg/feature/serverless/conditions.go
- tests/e2e/controller_setup_test.go
- tests/e2e/dsc_cfmap_deletion_test.go
- tests/e2e/dsc_creation_test.go
- tests/envtestutil/cleaner.go
- tests/envtestutil/utils.go
- tests/integration/features/serverless_feature_test.go
- tests/integration/features/tracker_int_test.go
- removed irrelevant `//nolint` comments (see config updates below)
- converted unused func params to blank identifier when impl does not need it
`perfsprint`
- disabled fmt.Sprintf checks for one argument string message, as it's been used in multiple places. I assume it's to favor readability and ease for further extension if more args needs
- adjusted errors creation to use errors.New instead of fmt.Errorf when no-arg strings are used as messages
- configured revive to not complain about dot-imports for testing libraries
- adjusted configuration due to changes in the structure (see `skip-dirs`)
- some deprecated linters were removed from golangci-lint toolchain so they are now gone from the config too
> chore(lint): updates golangci-lint to latest version

- .github/scripts/get-component-release-notes.js
- .github/scripts/get-release-branches.js
Improve the release branch reading logic in release automation.
The previous version had a hardcoded index of "2" to get the list of components and their release branches. Now the logic is improved to read the component data which is added(as bullet points) exactly after the `#Release#`.
https://issues.redhat.com/browse/RHOAIENG-8829
Mock tracker: https://github.com/AjayJagan/notes-operator/issues/2
Changed logic and it was able to create the draft pr for e2e: https://github.com/AjayJagan/opendatahub-operator/pull/287
> chore: Improve automation logic for reading release branches

- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/monitoring.go
- dashboard is using segment-io's configmap to flip monitoring settings
- upon upgrade, Operator redploy the same configmap to set data to "true"
- pass in context
https://issues.redhat.com/browse/RHOAIENG-1205
> fix: do not redeploy segment-io's if it has been deployed previously

- pkg/cluster/cert.go
> chore: remove duplicated logic by function call

- .golangci.yml
- controllers/status/reporter.go
- pkg/plugins/addLabelsplugin.go
- pkg/plugins/namespacePlugin.go
Instead of using `//nolint:ireturn` the linter allows the use of `generic` return types through the global config (on top of the listed defaults which now have been explicitly set).
This approach also eliminates a recurring issue where `nolintlint` reports the directive above as not used by the defined linter.
Related issue: https://github.com/golangci/golangci-lint/issues/3228
On top of that, we have `--fix` flag enabled for `golangci-lint` runner. This results in the removal of these comments as `nolintlint` tries to auto fix.
As a consequence the subsequent run of `make lint` yields errors for previously disabled linters and the cycle continues :)
> [!IMPORTANT]
> This behaviour has also been observed for other linters.
As part of this work, the declarations of kustomize plugin …
> fix(lint): explicitly configures ireturn exceptions

- controllers/webhook/webhook.go
Prepare to implement deletion check.
- Use switch to select supported requests, easier to add Delete then.
- Remove misleading messages for the allowed case, the last one only is in use.
- Use helpers to count and to compare, there will be the same logic for deletion check.
- Tune allowed message.
- Use go style case with several variants instead of C-style.
> webhook: refactor with switch and helpers

- controllers/datasciencecluster/datasciencecluster_controller.go
modelmesh started to create NWP odh-model-mesh when this has been a part of kserve deployment
this is causing both components successfully deployed but Operator reconcile.
to whiltelist this NWP CR with this PR unless kserve and modelmesh have been solution from their side to only create it once.
ref: https://issues.redhat.com/browse/RHOAIENG-8996
local build:  quay.io/wenzhou/opendatahub-operator-catalog:v2.14.0-1
test:
- create DSC only with kserve and modelmesh enabled
- no new reconcile once both are deployed successuflly
> fix: add odh-modle-controller NWP to whitelist

- pkg/feature/builder.go
- pkg/feature/feature.go
- tests/integration/features/cleanup_int_test.go
This PR introduces a featureBuilder function that enables conditional toggling of features named `EnabledWhen`. Features can now be activated or deactivated based on specific conditions such as the target platform, management mode, or the presence of particular resources in the cluster.
Building on the previous PR linked below which we didn't finish up, this update ensures that feature.Cleanup() is called if a feature's EnabledWhen() status changes from true to false across multiple reconciles. Additionally, this PR includes enhanced testing to validate these changes.
https://issues.redhat.com/browse/RHOAIENG-8540
re-doing and finishing up work from PR #793 
Wrote additional cleanup integration tests - using an example function checking if a certain namespace exists to enable the feature. …
> feat: adds EnabledWhen to the feature builder

- components/README.md
- components/codeflare/codeflare.go
- components/component.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/kueue/kueue.go
- components/modelmeshserving/modelmeshserving.go
- components/modelregistry/modelregistry.go
- components/ray/ray.go
- components/trainingoperator/trainingoperator.go
- components/trustyai/trustyai.go
- components/workbenches/workbenches.go
- pkg/deploy/deploy.go
- pkg/plugins/addLabelsplugin.go
- pkg/plugins/namespacePlugin.go
- also update the method parameters
- and some cleanup functions
currently the build is based on changes from https://github.com/opendatahub-io/odh-dashboard/pull/2906
which just got merged
ref: https://issues.redhat.com/browse/RHOAIENG-8510
- local  ODH build: quay.io/wenzhou/opendatahub-operator-catalog:v2.12.8510-1 
- local RHOAI build:  ~~quay.io/wenzhou/rhods-operator-catalog:v2.12.851-2~~  quay.io/wenzhou/rhods-operator-catalog:v2.12.8510-2
> refactor: dashboard with new manifests structure

- pkg/feature/feature.go
- pkg/feature/feature_tracker_handler.go
Refactors `FeatureTracker`-related functions to plain functions instead of Feature receivers. This eliminates unnecessary coupling with the `Feature` struct.
`make` + manual with simple KServe setup (which I hope can be part of an automated test suite one day...)
> chore(feature-tracker): simplifies struct handling

- controllers/dscinitialization/servicemesh_setup.go
- pkg/feature/feature.go
Instead of performing patching of Authorino deployment as part of `PostConditions` hook, it is now a `Feature` on its own.
As a result, we no longer need the `ApplyManifest` mehtod for the `Feature` struct. This function was created solely to apply a single manifest as an `Action` and was used only for this specific use case. With the dedicated feature, a deployment patch can now be defined as a regular manifest source and included as a part of the Apply phase.
I tested both the upgrade path and regular deployment on ROSA (hence `serviceMesh.auth.audiences` entry in the DSCI below)
Prerequisite: DSCI with Service Mesh enabled
```yaml
apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
name: default-dsci
spec:
applicationsNamespace: opendatahub
monitoring: …
```
> chore: reworks authorino istio proxy injection patch

- config/webhook/manifests.yaml
- controllers/webhook/webhook.go
- controllers/webhook/webhook_suite_test.go
- pkg/cluster/gvk/gvk.go
This PR fixes a race condition that happens while uninstalling the odh-operator. The issue occurs while uninstalling, at times DSCI instance gets removed first and DSC instance hangs over with error status expecting DSCI instance to be created. Manual deletion also does not remove the hanging DSC instance. This PR address the issue by blocking the deletion of DSCI before DSC through webhooks.
JIRA issue: https://issues.redhat.com/browse/RHOAIENG-2974
Issue was reported as a race condition. To reproduce the race condition manually, followed the below steps
- Built and deployed the operator with this code changes.
- Created DSCI and DSC instances and checked pod logs if they are fine without errors.
- Deleted DSCI instance first and checked the status of DSC to be in error status
- Manually …
> RHOAIENG-2974: Restrict DSCI deletion before DSC

- pkg/feature/manifest.go
- pkg/feature/raw_resources.go
- tests/integration/features/fixtures/templates/local-gateway-svc.tmpl.yaml
- tests/integration/features/fixtures/templates/unmanaged-svc.yaml
- tests/integration/features/resources_int_test.go
Aligns reconcile strategy for `Managed()` features to rely on Server-side apply rather than Update. The SSA approach is used by `deploy` package when reconciling kustomize resources, so keeping it the same makes sense. 
The previous one, based on `client.Update` call, tries to overwrite the entire resource rather than using a patch operation, which can lead to errors when trying to overwrite immutable fields such as:
```
failed to update object test-namespace/knative-local-gateway: Service "knative-local-gateway" is invalid: [metadata.resourceVersion: Invalid value: "": must be specified for an update, spec.clusterIP: Invalid value: "": field is immutable]
```
- if "managed" annotation is present in one of the resources being part of the feature it will be respected
- reworked tests to be …
> fix(feature): uses server-side apply to reconile

- tests/integration/features/fixtures/templates/managed-svc.tmpl.yaml
- tests/integration/features/fixtures/templates/unmanaged-svc.tmpl.yaml
- tests/integration/features/resources_int_test.go
Ensures each test case deploys resources in its own namespace to avoid sharing state between tests (sometimes unintentionally).
Follow up to #1098
`make`
> chore(tests): isolates resource reconcile tests

- pkg/feature/manifest.go
During the processing of the manifest files, the names of the files were not reported as part of the errors such as missing keys referred in the templates. This commit adds this context to returned errors so the problems can be located faster.
`make` - this is not a functional change, this adds more details to error messages.
> chore(feature): adds context to manifest errors

- .github/scripts/get-component-release-notes.js
- .github/scripts/get-release-branches.js
Allows regex to accept whitespace before and after the delimiter '|' because when added without a whitespace github bleeds the url and makes it redirect to a malformed URL.
JIRA: https://issues.redhat.com/browse/RHOAIENG-9630
context: https://docs.google.com/document/d/1YX0zAxkl4N6-K5t4INsBqnUAxTN0GDPWV1jn9XjkgPg/edit?disco=AAABQq9SeXI
The text to test is
```
#Release#\n\ndata-science-pipelines-operator|https:
//github.com/opendatahub-io/data-science-pipelines-operator/tree/v2.0.1 |https://github.com/opendatahub-io/data-scienc
e-pipelines-operator/releases/tag/v2.0.1
```
and the code to test is https://github.com/opendatahub-io/opendatahub-operator/blob/incubation/.github/scripts/get-release-branches.js#L22-L39 
with the modified regex from the pr.
> Improve regex to accept white spaces before delimiters(release-automation)

- components/kserve/kserve.go
- components/kserve/kserve_config_handler.go
This reverts commit f3e6a135cb0526b4672cdd6fb23a764d32495129.
previous cleanup removed the error from component when ossm and or authorino is not installed
which is causing DSC does not show error but keep reconcile on kserve
this is to revert the change to keep both in DSC and DSCI do the dependent check
https://issues.redhat.com/browse/RHOAIENG-9664
> Revert "chore: remove duplicated logic by function call (#1080)"

- components/kserve/resources/servicemesh/envoy-oauth-temp-fix.tmpl.yaml
- components/kserve/servicemesh_setup.go
- pkg/feature/builder.go
- tests/integration/features/fixtures/templates/local-gateway-svc.tmpl.yaml
The current implementation incorrectly calls removal of a header which is manifested in ingress gateway proxy logs when trying to access inference service:
```
envoy lua external/envoy/source/extensions/filters/http/lua/lua_filter.cc:930  script log: [string "function envoy_on_request(request_handle)..."]:10: bad argument #1 to 'remove' (N5Envoy10Extensions11HttpFilters3Lua16HeaderMapWrapperE expected, got string`
```
This fixes the Lua syntax and marks Service Mesh Features related to KServe setup as `Managed()`. This ensures that updating the existing filters will happen on operator upgrade or next reconcile.
- deploy latest `incubation` operator
- create DSCI with Service Mesh enabled
- create DSC with KServe enabled
- check the content of the filter `oc get …
> fix(envoy-filter): properly removes headers

- .golangci.yml
As we have labels and annotations with values either `true` or `false` we often compare them in the code. This leads to complains of `goconst` linter about extracting these "magic words" to constants. As this are obvious values to check against there's little benefit of doing so.
This change configures `goconst` for golangci-lint runner to skip such cases.
> chore(lint): skips true|false for goconst

- pkg/conversion/conversion.go
- pkg/deploy/deploy.go
- pkg/feature/manifest.go
- pkg/feature/raw_resources.go
We rely on conversion to Unstructured resources in quite a few places in the code base. With the introduction of a dedicated pkg, we can keep those functions together and reuse them across the code base.
> [!IMPORTANT]
> While converting Kustomize `ResMap` we do not use `MustYaml` func anymore, as this one panics. We attempt to convert to YAML and handle the error instead.
> refactor: moves conversion to unstr to dedicated package

- pkg/cluster/resources.go
Jira Issue: https://issues.redhat.com/browse/RHOAIENG-9753
**Root Cause:**
[Commit](https://github.com/opendatahub-io/opendatahub-operator/pull/1041/files#diff-1c2bd1d24587a4323e59931edaa538b2d6538fbd63dad45ea40ef8d1d9bbd939R105 ) introduced a change that failed to identify already existing DSC in Managed clusters.
This change fixes above issue and has been tested on Managed cluster
Operator Error
```
{"level":"error","ts":"2024-07-11T21:42:46Z","logger":"setup","msg":"unable to create default DSC CR by the operator","error":"failed to create DataScienceCluster custom resource: context deadline exceeded","stacktrace":"main.main.func2\n\t/workspace/main.go:245\nsigs.k8s.io/controller-runtime/pkg/manager.RunnableFunc.Start\n\t/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14. …
```
> Fix: Return if DSC already exists

- pkg/cluster/roles.go
Introduces functions to create, update, and delete ClusterRoles and ClusterRoleBindings.
This is part of Authorization capability work provided as stacked PR. We simply want to avoid humongous PR like 605 and have focused review instead.
> feat(cluster): add roles and role bindings management

- controllers/dscinitialization/servicemesh_setup.go
With the #1052 refactoring, the order of features added to the Registry was accidentally changed. It results in failing of metrics collection feature which expects SMCP to be created first, but the creation runs afterwards. The setup is eventually consistent, as the reconcile will retry, so this not a bug per se, but results in unnecassary errors.
This fix ensures features are ordered as before and levarages `.EnabledWhen` instead of wrapping features in `if`s.
- create DSCI with Service Mesh enabled
- observe logs
<details>
<summary>BEFORE: Reconcile log</summary>
```json
[
{
"level": "info",
"ts": "2024-07-12T07:52:53Z",
"logger": "features",
"msg": "waiting for control plane components to be ready",
"feature": "mesh-metrics-collection",
"control-plane": "data-science-smcp", …
```
> fix: ensures SMCP is created before any other features

- pkg/upgrade/upgrade.go
- in a rare condition since we change the CreateWithRetry() return
follow up from 
https://github.com/opendatahub-io/opendatahub-operator/pull/1116
> update: check return of create dsci if failed because of existing

- pkg/upgrade/upgrade.go
Reverts opendatahub-io/opendatahub-operator#1117
> Revert "update: check return of create dsci if failed because of existing"

- pkg/cluster/resources.go
- pkg/upgrade/upgrade.go
- revert [2110c0501ea24fb8df12d12ea682e5e483e62281](https://github.com/opendatahub-io/opendatahub-operator/pull/1122)
- add sleep before first calling CreateWithRery on DSCI
https://issues.redhat.com/browse/RHOAIENG-10065
local test with auto creation enabled to mimic internal build system: 
quay.io/wenzhou/opendatahub-operator:2.14.1
> fix: auto creation DSCI during startup

- pkg/deploy/deploy.go
- pkg/deploy/envParams.go
- pkg/deploy/utils.go
can be good prepare for https://github.com/opendatahub-io/opendatahub-operator/pull/1026
> chore: refactor on some logic for component manifests resources

- pkg/cluster/const.go
This PR amends the release.name for ODH csv.
Related JIRA: https://issues.redhat.com/browse/RHOAIENG-9751
Installing manually the ODH operator in a cluster and check that Open Data Hub is shown in the release.name field
> RHOAIENG-9751: Update release.name from DSC and DSCI in ODH

- controllers/dscinitialization/servicemesh_setup.go
If the authorization provider namespace is not specified in the DSCI the default is constructed to be `application-namespace-auth-provider`, e.g. `opendatahub-auth-provider`.
With the #1052 refactoring, the regression has been introduced where the value is directly read from the spec instead of being dynamically constructed based on the rule described above.
This is manifested with the following error, as the feature mistakenly waits for pods across all namespaces (because of list option for namespace being `corev1.NamespaceAll == ""`). This obviously rarely is true, especially for large clusters.
```json
Failed applying [enable-proxy-injection-in-authorino-deployment]: 1 error occurred:
* client rate limiter Wait returned an error: context deadline exceeded
```
leading to failure of …
> fix: authz patch injection feature precondition uses correct namespace value

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- pkg/cluster/cluster_config.go
this reduce the call to read local /var/ file if it is already there
this is the env variable we already used in makefile/readme
local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.15.84
debug shows operatorNS got the value openshift-operator on this local build.
> chore: get operator namespace from deployment as env variable

- controllers/dscinitialization/dscinitialization_controller.go
For investigation in https://issues.redhat.com/browse/RHOAIENG-10300 we can identify the problem is from an updated DSCI before removing finalizer.
**To unblock this problem in regression, this is just a workaround.**
and we need a proper work as suggested in https://issues.redhat.com/browse/RHOAIENG-10300
Current change:
- after remove servicemesh and update condition, instance has been updated
- use retryonconflict to make sure it is removed when something else might also update DSCI at the same time
https://issues.redhat.com/browse/RHOAIENG-9606
local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.15.1-9096
test step:
- remove ossm from cluster
- create dsci and dsc cr
- wait tiil "missing ossm" error in both
- delete dsc cr
- delete dsci cr
- done
also verified in QE cluster
> fix: when delete DSCI CR get stuck because the current instance updated and not preperly remove finalizer on it

- .gitignore
- CONTRIBUTING.md
- Dockerfiles/Dockerfile
- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- get_all_manifests.sh
- pkg/deploy/deploy.go
- from odh-manifests to opt/manifests which is where image is using
- set default manifests path in CSV for release
- user can point to local manifests for debug
`>make clean`
removed opt/manifests folder
`>make get-manifests`
downloaded components manifests into $(pwd)/opt/manifests
local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.15.7-29
create DSCI and DSC CR
check pods in application NS
`>oc get pod -n opendatahub`
NAME                                                              READY   STATUS    RESTARTS   AGE
codeflare-operator-manager-5bb9f6745c-7mhv9                       1/1     Running   0          2m1s
data-science-pipelines-operator-controller-manager-79468c977tct   1/1     Running   0          2m43s
etcd-5cd44cd8dd-hbrrn …
> chore: change local "manifests" folder to match in-image path

- .github/actions/update-release-version/action.yaml
- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
Token expiry fix:
The installation token generated through the GH app has a validity of 1 hour. ref: https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app So the issue is, when waiting for e2e tests(github checks) which runs for more than 1 hr to finish, the token gets expired and then the gh action is no longer able to do other tasks(such as creating a pr)
In order to fix this, we can use the GITHUB_TOKEN that is generated for each workflow. ref: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret The GITHUB_TOKEN expires when a job finishes or after a maximum of 24 hours.
Move version update to composite action:
There are 2 sets of steps in …
> (chore): Fix the token expiry and move release version update code to a composite action.

- components/dashboard/dashboard.go
- priority for image: 
1. when set devFlag: 
devFlag > imageParam 
2. when not set devFlag: 
imageParam > default value during operator build time
- prioirty for url, title, groups: 
regardless set devFlags or not, always determinated by Platform value
https://issues.redhat.com/browse/RHOAIENG-10276
local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.15.10276
when DSC set to:
```
dashboard:
```
params.env is
```
admin_groups=odh-admins
odh-dashboard-image=<cpaas image>
dashboard-url=https://odh-dashboard-opendatahub.apps.rosa.wen-rosa-6.kuuz.p3.openshiftapps.com
section-title=OpenShift Open Data Hub
```
When DSC set to:
```
dashboard:
devFlags:
manifests:
- contextDir: manifests
uri: …
```
> fix: devFlags for dashboard did not set correct values

- pkg/cluster/cluster_config.go
During testing, we found out the Managed has Catsrc installed into a different cluster.
https://issues.redhat.com/browse/RHOAIENG-10678
> fix: for Managed cluster, we need another namespace or it will be deteced as self-managed

- pkg/feature/builder.go
This change ensures that original target namespace is used when invoked directly in the builder.
Typically subsequent calls of `.TargetNamespace` in the feature builder indicate coding/copy-paste error and should be reduced to one.
However,in the FeatureHandler, where we group features together we do not have to specify target namespace for each feature, as it is defaulted to the one defined on the handler level. This is convenient, but limits application of features to a single namespace, as the value is always overwritten.
By running `make` tests.
> fix(feature): preserves original target namespace

- pkg/feature/servicemesh/const.go
- pkg/feature/servicemesh/resources.go
While creating service mesh features, certain configs are written to the config maps. To allow extending of this shared configuration across the code base the names have been extracted and exported as const in `servicemesh` package.
> chore(service-mesh): exports configmap names to const

- components/component.go
- components/modelregistry/modelregistry.go
Adds managed model registry prometheus config handling logic
Fixes RHOAIENG-4273
https://issues.redhat.com/browse/RHOAIENG-4273
Tested that the code changes do not affect ODH unit tests. 
Further testing of the actual prometheus config will continue for other PR https://github.com/red-hat-data-services/rhods-operator/pull/318
But no component code changes will be needed for any changes in the prometheus config.
> feat: add managed model registry prometheus config handling logic, fixes RHOAIENG-4273

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/webhook/manifests.yaml
- controllers/webhook/webhook.go
alot in logs from Operator Pod on operator of UPDATE:
`{"level":"info","ts":"2024-07-23T14:01:16Z","logger":"odh-controller-webhook","msg":"No logic check by webhook is applied on UPDATE request"}` this is confusing users.
- the changes is to remove this message from pod by not filter on Update operation.
`make unit-test`
> chore: remove UPDATE from webhook operation list

- go.mod
- go.sum
some packages are not used after we cleanedup old code
this is only to get these removed from go.mod
> chore: cleanup Warning for unused packages

- pkg/cluster/resources.go
- pkg/upgrade/upgrade.go
Make CreateWithRetry work for already existing object and remove extra handling for AlreadyExists in the caller code. This does not work for webhook case anyway.
Tested webhook configuration:
- enable automatic dsci creation, in config/manager/manager.yaml set DISABLE_DSC_CONFIG to false
- install on clean cluster:
- logs show `Error creating object: Internal error occurred: failed calling webhook "operator.opendatahub.io": failed to call webhook: Post "https://opendatahub-operator-webhook-service.opendatahub-operator-system.svc:443/validate-opendatahub-io-v1?timeout=10s": no endpoints available for service "opendatahub-operator-webhook-service". Retrying...`
- after some time `oc get dsci` shows default-dsci Ready
- restart the pod (delete)
- logs show `Resource default-dsci already …
> upgrade: cleanup CreateWithRetry usage

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- reduce cpu and mem usage
- request is  some data from testing in a large cluster psi-04
- limit is data from attached file in jira 9806
- 
related to https://issues.redhat.com/browse/RHOAIENG-9806
> chore: tuning resource usage for operator pod

- pkg/feature/resource/operations.go
- tests/integration/features/fixtures/templates/namespace.yaml
- tests/integration/features/fixtures/templates/namespaces.yaml
- tests/integration/features/manifests_int_test.go
Manifests used by Feature to create cluster resources can be either defined as a single resource per file or grouped together and separated using the `---` delimiter. Even though the former approach is currently preferred across the codebase, the latter is used to create Envoy filters for the KServe setup.
When applying resources not yet present in the cluster, the original implementation returns after creating the first resource, leaving the rest unprocessed. They are applied in the next reconcile loop, though again on a one-per-reconcile event basis. This is not a bug per se, as it will eventually result in creating all resources; however, it is suboptimal.
This change ensures all resources defined in a single YAML manifest, separated using `---`, are processed in a single go.
Enhanced …
> fix(feature): ensures all new resources are created in one reconcile

- pkg/cluster/meta.go
This change removes the declaration of map size. Relying on default allocation is sufficient for this use case, but more importantly, given the modulo check before, it has always been 0 (mistakenly using `%` operator). 
This is not only confusing for the reader but can result in immediate map resizing.
> chore(meta): removes map size declaration

- pkg/upgrade/upgrade.go
to follow up discussion https://github.com/opendatahub-io/opendatahub-operator/pull/1145#discussion_r1700136942
By reading upgrade document, my understanding is, the code logic is correct but the comments did not get updated.
> doc: correct godoc

- components/kserve/resources/serving-install/knative-serving.tmpl.yaml
chore: Enable by default the serving features to allow pvc mounts.
> [RHOAIENG-10647] - Configure Knative PVC support as default

- Makefile
The current list of default targets includes `manifests` which generates CRDs based on API code changes. Still, it does not invoke `generate` which is responsible for generating additional code (namely `DeepCopy` funcs).
This can result in incomplete implementation where CRDs reflect the latest changes in the API, but internally it might not be possible to use due to missing copy methods or even outdated implementations of those that already exist.
This change adds it to the list of default targets so that each code change can be committed with the complete set of changes for `controller-runtime`.
> feat(make): adds generate to default targets

- components/kserve/kserve.go
The call is not need since the code just declare empty parameters list:
var imageParamMap = map[string]string{}
Fixes the issue of calling ApplyParams for non-enabled case.
Credits-to: Wen Zhou <wenzhou@redhat.com>
> kserve: do not call ApplyParams for the empty list

- components/codeflare/codeflare.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/kueue/kueue.go
- components/modelmeshserving/modelmeshserving.go
- components/modelregistry/modelregistry.go
- components/ray/ray.go
- components/trainingoperator/trainingoperator.go
- components/trustyai/trustyai.go
- components/workbenches/workbenches.go
- pkg/deploy/envParams.go
previously we use the boolean in ApplyParams() for some DW cases(CFO and Ray need, TO not really), because they would like to pass extra value (in that case namespace)
later for dashboard, extraParamsMaps has been introduced but the old boolean did not get cleaned up.
extraParamsMaps is generic to use, this PR is only to cleanup boolean and move the namespace variable from imageParamsMap away
quay.io/wenzhou/opendatahub-operator-catalog:v2.16.96
> update: remove unnecessary param from ApplyParams()

- Dockerfiles/Dockerfile
- in this case, we will get '-rw-rw-r--'
- non-1001 users can run as user for operator pod
https://issues.redhat.com/browse/RHOAIENG-10272
similar test:
to add restrict pipeline scc with priority to 10 and user 1000
operator pod can run with no error regarding permission of files
> update: open root group to the same permission as owner

- components/kserve/kserve_config_handler.go
This change ensures that ServiceMesh spec is set before proceeding with Serverless setup.
`DSCI.ServiceMesh` has been changed to a pointer to be truly `optional` in the DSCI CR. If it is not defined in the DSCI API, it is `nil` struct instead of being defaulted by the apiserver.
This resulted in panic when DSC has KServe with Serverless enabled, and it expects to have ServiceMesh configuration present to proceed with its settings.
Create the following DSCI and DSC:
```yaml
apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
name: default
spec:
applicationsNamespace: opendatahub
trustedCABundle:
managementState: Removed
monitoring:
namespace: opendatahub
---
apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster …
```
> fix(serverless): checks if Service Mesh is defined

- controllers/dscinitialization/servicemesh_setup.go
- pkg/feature/builder.go
- pkg/feature/feature.go
- pkg/feature/feature_tracker_handler.go
- pkg/feature/servicemesh/cleanup.go
- tests/integration/features/servicemesh_feature_test.go
Initially, `Cleanup` functions did not rely on loading Feature's data for invocation, as certain data was held as fields of the Feature struct, making it implicitly available. With the refactoring of Feature to become a "glorified map" container, this behavior has changed, leading to errors under certain circumstances.
With `DSCI.ServiceMesh` now being a pointer to a struct, there is a corner case where the (now needed) ServiceMesh spec is `nil`, leading to a panic.
When the reconciliation of DSC is triggered, it is invoked for each component, even if it is never defined or changed. In a simple case where DSCI does not have a specified ServiceMesh (`nil` instead of the default), and DSC has a single `Managed` component that is not KServe/Serverless, the reconciliation will trigger the …
> fix(feature): cleanup funcs should not rely on feature's data

- Makefile
- crd-ref-docs.config.yaml
- docs/api-overview.md
- warning when "make api-docs": egrep: warning: egrep is obsolescent; using grep -E
- and set to correct k8s version
rerun target and no changes made
> chore : use grep -E than egrep in make and set min k8s version

- .github/workflows/linter.yaml
- Makefile
- tests/e2e/dsc_creation_test.go
While I've fixed a lint finding on one of the e2e tests, I also reworked it a bit (in a separate commit) since there were a condition that was not properly taken into account.
I could split this PR in two separate ones if it makes things more clear.
> chore: update golangci-lint to v1.60.2, fix misleading test

- get_all_manifests.sh
On MacOSX, /bin/bash is quite outdate 3.2.57 and does not suport
`declare -A` which leads to the get_all_manifests.sh to fail.
Signed-off-by: Luca Burgazzoli <lburgazzoli@gmail.com>
> chore: use /usr/bin/env to locate the bash interpreter based on the user's PATH settings.

- components/modelregistry/modelregistry.go
- components/modelregistry/resources/servicemesh-member.tmpl.yaml
- tests/e2e/dsc_creation_test.go
Add servicemeshmember for model registry namespace
Fixes RHOAIENG-11831
Added test to confirm that the smm gets created in the MR namespace
To verify that model registry component is worked, make sure it's set to Managed in the dsc, and perform the following steps:
1. Clone the model registry operator repo for sample configuration
2. Run the following commands to checkout the sample, create sample MR:
```shell
git clone git@github.com:opendatahub-io/model-registry-operator.git
cd model-registry-operator
oc project odh-model-registries
make certificates
oc apply -k config/samples/secure-db/mysql-tls/
oc wait --for=condition=Available=true modelregistries/modelregistry-sample --timeout=5m
```
3. Run the following commands to run a curl command against the sample MR API to verify it works: …
> feat: add servicemeshmember for model registry namespace, fixes RHOAIENG-11831

- Makefile
- docs/api-overview.md
- their release changed and support different os/arch binary
- and it is named as x86_64 not amd64 :shushing_face:
> deps: uplift crd-ref-docs to 0.1.0

- Makefile
- components/codeflare/codeflare.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/kueue/kueue.go
- components/modelmeshserving/modelmeshserving.go
- components/modelregistry/modelregistry.go
- components/ray/ray.go
- components/trainingoperator/trainingoperator.go
- components/trustyai/trustyai.go
- components/workbenches/workbenches.go
- pkg/cluster/resources.go
- tests/e2e/controller_setup_test.go
- tests/e2e/dsc_creation_test.go
- wait for component's deployment is ready before return to caller
- reduce logging
- prolong timeout for workbench, trustyai, dsp, kserve
change based on https://github.com/opendatahub-io/opendatahub-operator/pull/1014
https://issues.redhat.com/browse/RHOAIENG-349
> fix: add check for all platform offering on components

- components/workbenches/workbenches.go
This should address the [1]. With current code it wasn't possible to override the images used for the notebook controllers via env property, now it should be possible.
[1] https://issues.redhat.com/browse/RHOAIENG-11134
I installed the latest OpenDataHub operator (v2.16) and amended the CSV by:
1. pointing the deployment containter to the image build for this PR
2. added the desired env variables `RELATED_IMAGE_ODH_KF_NOTEBOOK_CONTROLLER_IMAGE` and `RELATED_IMAGE_ODH_NOTEBOOK_CONTROLLER_IMAGE`
3. then create the DSCI and DSC instances and see what images were used for the both notebook controller pods
CSV
```
...
containers:
env:
- name: DISABLE_DSC_CONFIG
value: 'true'
- name: OPERATOR_NAMESPACE
valueFrom:
fieldRef:
fieldPath: metadata.namespace
- name: DEFAULT_MANIFESTS_PATH
value: …
```
> Don't restrict the nbc image update to downstream only

- pkg/deploy/envParams.go
Optimize file operations, do not rewrite params.env on every reconcile if no updates for it. In practice updates happen only on the first run.
Jira:  https://issues.redhat.com/browse/RHOAIENG-11594
> deploy: ApplyParams: do not write params.env if there are no updates

- controllers/dscinitialization/dscinitialization_controller.go
- the same code has been called up in the Reconcile()
https://github.com/opendatahub-io/opendatahub-operator/blame/778ca9962ed79313cb389ba2772c5fd21ebb97ec/controllers/dscinitialization/dscinitialization_controller.go#L138
> chore: remove dead code

- tests/e2e/creation_test.go
- do not print Trying again if cannot list deployments
- enable immediate for PollUntilContextTimeout
- remove check for dependent operator
- early return from the loop
> tests: e2e: testApplicationCreation cleanup

- .github/scripts/get-component-release-notes.js
- .github/scripts/get-release-branches.js
- .github/workflows/pre-release.yaml
The following changes are added
- Allow the tracker URL to support adding tags ie. 
- If a component has both tag and branch as the same value then the tracker can be updated as `component_name|branch-or-tag-url`
- If a component has different tag and branch values, the the tracker can be updated as 
`component_name|branch-or-tag-url|release-notes-url`
- Remove wait for checks for the version update pr as we can manually verify the checks and merge(This merge will trigger the next set of gh actions)
- Improve grouping in the release notes. eg: Under "Serving" heading we should have the notes of Modelmesh, odh-model-controller etc
- Fix skopeo login issue
Tested in my repo:
https://github.com/AjayJagan/opendatahub-operator/actions/runs/10501974699 …
> chore: Rework release automation - ||

- tests/e2e/controller_test.go
- tests/e2e/creation_test.go
- tests/e2e/deletion_test.go
- tests/e2e/helper_test.go
- tests/e2e/odh_manager_test.go
- make check on CRD run in parallel
- add loop for check DSC status, so test on DSC status wont fail with timout
- move resourceCreationgTimeout and resourceRetryInterval out of tc
- rename resourceRetryInterval to generalRetryInterval
- create different timeout instead of using resourceCreationgTimeout for all cases
- move check on DSC ready out of testDSCCreation into validateDSCReady which calls waitDSCReady
- rename testAllApplicationCreation to testAllComponentCreation
- rename  testApplicationCreation to testComponentCreation
- do not immediate check func in testComponentCreation
- rename testApplicationDeletion to testComponentDeletion
- immediate check func in testComponentletion
- rename waitForControllerDeployment to waitForOperatorDeployment
- set new timeout, see const block
> tests: performance and time tuning for e2e

- main.go
it is causing problem in modelreg with reconcile in Operator pod
related to https://github.com/opendatahub-io/opendatahub-operator/pull/1190
> fix(cache): since we add new secret from modelreg with cache, we need to lose the cache for istio-system ns

- components/dashboard/dashboard.go
- if DSC CR has old format with empty devFlag:{}, it can cause downstream image not replace but run with quay.io one
https://issues.redhat.com/browse/RHOAIENG-12300
local build and test: 'quay.io/wenzhou/opendatahub-operator:2.12300.1'
steps:
create DSC CR with 
```
dashboard:
devFlags: {}
```
and
```
dashboard:
```
does not trigger debug into `OverrideManifests`
use
```
dashboard:
devFlags:
manifests: [
uri: "https://wen.zhou.com"
]
}
```
into error, expected,` "https://wen.zhou.com\": dial tcp: lookup wen.zhou.com on 172.30.0.10:53: no such host",`
> fix: dashboard image not get set in downstream due to devFlags config

- components/workbenches/workbenches.go
- pkg/cluster/const.go
- fix wrong caller on notebookControllerPath
this is the problem when we have reconcile twice on odh-notebook-controller see https://issues.redhat.com/browse/RHOAIENG-12732
old: DeployManifestsFromPath on notebookControllerPath, then update params.env file. 
new: update params.env file then do call  DeployManifestsFromPath on notebookControllerPath
- remove downstream speicific path for notebook:  `notebookImagesPathSupported` is removed (along with defaultKustomizePathSupported) , see downstream [PR](https://github.com/red-hat-data-services/rhods-operator/pull/343)
- move default workbench namespace into const
- removed duplicated comments, probably from rebase long time ago
a similar PR in downstream https://github.com/red-hat-data-services/rhods-operator/pull/343, since it also need to …
> fix: nbc not use correct image for downstream + cleanup downstream path

- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- main.go
- pkg/cluster/cluster_config.go
- pkg/upgrade/upgrade.go
https://issues.redhat.com/browse/RHOAIENG-11891
local build: from odh quay.io/wenzhou/opendatahub-operator-catalog:v2.18.11891-0
**for odh build**:  quay.io/wenzhou/opendatahub-operator-catalog:v2.18.11891-0
**for rhoai:**  quay.io/wenzhou/rhoai-operator-catalog:v2.14.11891-0
tests on rhoai local build: 
**New install**
- clean installation of local build
get     ` disableBiasMetrics: false`
**Upgrade**
-  prepare:
install RHOAI 2.12 + enable dashbaord
check ODC CR, get `disableBiasMetrics: true`
uninstall operator but keep DSCI not deleted
check DSCI CR should have  `release.name: OpenShift AI Self-Managed` and `release.version: 2.12.0`
- test:
install rhoai local build , no need enable any component
after pod stable, check ODC CR, get  `disableBiasMetrics: false`    **=> expected, as …
> feat: enable Trusty's Bias Feature Flag

- components/component.go
- components/kserve/kserve.go
- components/kserve/kserve_config_handler.go
- components/kserve/servicemesh_setup.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/servicemesh_setup.go
- controllers/status/reporter.go
- pkg/cluster/gvk/gvk.go
- pkg/cluster/meta.go
- pkg/feature/builder.go
- pkg/feature/feature.go
- pkg/feature/feature_tracker_handler.go
- pkg/feature/handler.go
- pkg/feature/servicemesh/cleanup.go
- tests/integration/features/cleanup_int_test.go
- tests/integration/features/features_suite_int_test.go
- tests/integration/features/fixtures/cluster_test_fixtures.go
- tests/integration/features/manifests_int_test.go
- tests/integration/features/preconditions_int_test.go
- tests/integration/features/resources_int_test.go
- tests/integration/features/serverless_feature_test.go
- tests/integration/features/servicemesh_feature_test.go
- tests/integration/features/tracker_int_test.go
Introduces the ability to define owner reference for FeatureTracker (internal custom resource). This enables garbage collection of resources belonging to the given Feature when its owner such as DSC or DSCI has been removed.
When Features are grouped through means of `FeatureHandler`s, the ownership is defined under the hood, linking it to DSCI or DSC, depending on the type used.
In addition, this PR simplifies how Feature relies on `client.Client` instance. Instead of creating its own instance, it expects to have one passed as part of the builder call chain. It creates a default one otherwise. With that we can rely on a client configured for controllers with the right schemas, caching rules, etc. As a consequence the change of retry logic for status needed to be adjusted. Besides a …
> feat(tracker): allows to define ownerReferences for FeatureTrackers

- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- main.go
- pkg/cluster/cluster_config.go
- pkg/upgrade/upgrade.go
GetReleaseFromCSV name is more about implementation than the task it
performs. The function fetches actual running operator release and
CSV is only one possibility for that.
GetReleaseFromCR name is more about implementation than the task it
performs. The function fetches release from DSC/DSCI mean the latest
release the data science cluster was deployed by. Consider it as
"deployed release".
> Rename GetPlatform functions to not reflect implementation

- apis/dscinitialization/v1/dscinitialization_types.go
- bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
**put on-hold label for now , just waiting for reviewers all agree on this change**
- we do not support other values for now, this is to prevent user change to different value and cause old and new both running
- till we have a good solution to support this configable filed it is better to make it fixed value instead of dealing with post-fix when user change to another namespace after default one has been used.
local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.18.112
- instnall operator
- create default DSCI CR with opendatahub as applicationNamespace
- change applicatoinNamspace from `opendatahub` to `opendatahub2`, got error "Error "Invalid value: "string": ApplicationsNamespace is immutable" for field "spec.applicationsNamespace"."
- delete DSCI CR
- create another DSCI CR …
> feat: set DSCI application namespace to be immutable

- tests/envtestutil/name_gen.go
- tests/integration/features/cleanup_int_test.go
- tests/integration/features/fixtures/cluster_test_fixtures.go
- tests/integration/features/manifests_int_test.go
- tests/integration/features/preconditions_int_test.go
- tests/integration/features/resources_int_test.go
- tests/integration/features/serverless_feature_test.go
- tests/integration/features/servicemesh_feature_test.go
- tests/integration/features/tracker_int_test.go
Ensures each test uses a different DSCI instance as a test fixture. Without this change, tests are failing (as they do in the latest incubation commit). The reason is #1222 that introduced a validation check to ensure `AppNamespace` is immutable, but #1228 is trying to update DSCI violating the new constraint. The issue is that #1228 was merged first and only then #1222 came in, but without being first rebased on top of `incubation`.
With this change, each test uses a dedicated DSCI.
> [!IMPORTANT]
> This issue was not caught earlier for two reasons:
> * PRs are not enforced to be up-to-date with latest state of `incubation` before merged.
> * Pushes to `incubation` do not trigger test jobs.
>
> With this we ended up with #1228 merged first and #1222 being behind was merged afterwards …
> fix(test): makes DSCI-dependent tests self-contained

- components/kserve/kserve_config_handler.go
- components/kserve/servicemesh_setup.go
- controllers/dscinitialization/servicemesh_setup.go
- pkg/feature/builder.go
- pkg/feature/conditions.go
- pkg/feature/feature.go
- pkg/feature/feature_data.go
- pkg/feature/feature_tracker_handler.go
- pkg/feature/handler.go
- pkg/feature/resources.go
- pkg/feature/serverless/conditions.go
- pkg/feature/serverless/resources.go
- pkg/feature/servicemesh/conditions.go
- pkg/feature/servicemesh/resources.go
- tests/integration/features/cleanup_int_test.go
- tests/integration/features/fixtures/cluster_test_fixtures.go
- tests/integration/features/manifests_int_test.go
- tests/integration/features/preconditions_int_test.go
- tests/integration/features/resources_int_test.go
- tests/integration/features/serverless_feature_test.go
- tests/integration/features/servicemesh_feature_test.go
- tests/integration/features/tracker_int_test.go
Including the client in the function signature and decoupling it from `Feature` struct makes its usage explicit and more idiomatic. This approach clarifies that the client is intended for use within the function. 
It's a follow-up to PR [#1228](https://github.com/opendatahub-io/opendatahub-operator/pull/1228#issuecomment-2343046440).
> refactor(feature): decouples Feature from the client

- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- when we do not have e.g dependent operators installed, we should have .status.release info as well
- previous problem is, status update is in the end when reconcile on DSC/DSCI is finished, which can lead to a init value 0.0.0 and dashboard set to 0.0.0 to "About Modal"
https://issues.redhat.com/browse/RHOAIENG-12630
local build:
quay.io/wenzhou/opendatahub-operator-catalog:v2.18.12630
steps:
- uninstall ossm operator in the cluster
- create DSCI with default values
- wait for seconds to check DSCI has
```
- status:
conditions:
....
message: "2 errors occurred:\n\t* failed applying FeatureHandler features. cause: 1 error occurred:\n\t* 1 error occurred:\n\t* failed to find the pre-requisite Service Mesh Operator subscription, please ensure Service Mesh Operator is installed. failed to …
```
> fix: update DSC/DSCI .status.release not depend on other's reconcile

- controllers/webhook/webhook.go
these two cases should not block operation, for backwards compataible
- when modelreg is not set in DSC
- when modelreg is set to be Removed 
https://issues.redhat.com/browse/RHOAIENG-13052
local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.18.13052
> fix: only replace/set default model reg namespace by webhook if comnent is enabled

- controllers/webhook/webhook.go
- controllers/webhook/webhook_suite_test.go
- main.go
- use Default() instead of setDSCDefaults()
> refactor(webhook): change for mutating webhook to use Default to set ModelReg namespace

- .github/workflows/unit-tests.yaml
Unit tests job is currently only executed on PRs, leaving pushes on e.g. incubation branch untested. This can lead to issues like the one described in #1235
This PR enables GH Action to be run also for push events.
You can use [`act`](https://github.com/nektos/act) to test GH Actions locally instead of running them on your fork.
```sh
act "on: push" -j unit-test -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
```
> ci: ensures tests are run on push

- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/utils.go
- main.go
- pkg/cluster/cluster_operations_int_test.go
- pkg/cluster/cluster_operations_suite_int_test.go
- pkg/upgrade/uninstallation.go
- move check on platform into top of dsc and dsci reconcile to reduce duplicated calls
- add logger when operator start to show which platform is running on
(split from https://github.com/opendatahub-io/opendatahub-operator/pull/1231)
local build: quay.io/wenzhou/opendatahub-operator:2.18.919-1
> refactor: get platform calls

- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- we have get the Release can derive info from it.
- rename variable to be clear not only version but also name/platform
> chore: reduce more call to get platform

- main.go
- pkg/cluster/cluster_config.go
- pkg/cluster/cluster_operations_int_test.go
- pkg/cluster/cluster_operations_suite_int_test.go
There is no need to maintain the api since GetRelease performs the call and returns the information.
The extra work GetRelease does (in addition to GetPlatform) is not important since only one call in startup left.
Since the api removed, tests do not make sense, so revert testing part of d73b3da69ccc ("refactor: get platform calls (#1251)")
> cluster: remove GetPlatform api

- apis/infrastructure/v1/servicemesh_types.go
- bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
- docs/api-overview.md
This commit introduces a validation pattern and maximum length constraint to the `Namespace` fields in our structs. We have missed it in the early days.
Validation rules ensure that namespace names does not exceed max length defined and are valid [RFC 1123 DNS labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#namespaces-and-dns).
> fix(crd): adds validation pattern and max length for ns fields

- components/README.md
- components/codeflare/codeflare.go
- components/component.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/kueue/kueue.go
- components/modelmeshserving/modelmeshserving.go
- components/modelregistry/modelregistry.go
- components/ray/ray.go
- components/trainingoperator/trainingoperator.go
- components/trustyai/trustyai.go
- components/workbenches/workbenches.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- main.go
- pkg/logger/logger.go
- components: move logger creation to pkg/logger
Remove ConfigComponentLogger method from ComponentInterface. In the
original code this is totally internal function, not used by
external interface users.
But moreover by its functionality it prepares a logger from the
caller to be used in component's context (creates new one with
required log levels and DSC prefix or just adds the prefix to the
caller's one) so make a utility function NewNamedLogger out of
it. The actual component related configuration comes from DSC
reconciler, so wrap it as newComponentLogger there.
This is a pretty contradictive change since adding context name
idiomatically belongs to the context (component), but this allows to
do it in one place.
Alternative is to create just a final logger in the component
(l = …
> components: move logger creation to pkg/logger

- .github/scripts/get-component-release-notes.js
- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
(fix): ODH release automation: Release notes generation 
- The GH action [softprops/action-gh-release@v2](https://github.com/softprops/action-gh-release) currently doesnot support choosing a tag range for the change-log. ie we cannot set a previous tag. ref: https://github.com/softprops/action-gh-release/issues/465 
This fix(PR) is aimed to work around it by using the GH api directly and creating the body of the release notes ourselves.
- A minor fix which prevents gh action from doing a merge-commit.
ref: https://issues.redhat.com/browse/RHOAIENG-13458
- Tested the action by running on my repo.
> (fix): ODH release automation: Release notes generation

- CONTRIBUTING.md
- README.md
- docs/troubleshooting.md
Jira Issue: https://issues.redhat.com/browse/RHOAIENG-990
This PR updates the contribution guidelines to reflect current working process of the team
> docs: Update Contribution Guidelines

- main.go
when running in managed cluster: DSCI is stopped at Init status.
due to missing secret from namespace
https://issues.redhat.com/browse/RHOAIENG-13661
> fix: add downstream operator namespace into cache for secret

- pkg/upgrade/upgrade.go
- seems duplicate to create a new function but mainly:
- can  have a different value for the version
- if we want to keep one and remove another just comment out function
- probably we will have some other with similar logic later till it can be done in UI logic
- some not related changes in BiasMetrics function
https://issues.redhat.com/browse/RHOAIENG-13604
local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.14.13604
For ODH case
- keep a ODC CR with     `disableModelRegistry: true`
- keep a DSCI with release 2.13.0 from previous installation
- install local build
- check ODC CR see   `disableModelRegistry: true`
For downstream case
- keep a ODC CR with     `disableModelRegistry: true`
- keep a DSCI with release 2.13.0 from previous installation
-  fake cluster to be a Managed …
> feat: add support for upgrade to force disableModelRegistry to false

- controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/monitoring.go
- controllers/dscinitialization/servicemesh_setup.go
- controllers/dscinitialization/utils.go
- controllers/secretgenerator/secretgenerator_controller.go
Prepare to switch to dynamic logger. It can be k8s contextual logging [1] or some internal one. Copy reconciler's logger into local variables.
Just to avoid polluting the other patch with the replacements.
[1] https://www.kubernetes.dev/blog/2022/05/25/contextual-logging/
> controllers, monitoring: use local variable for logger

- apis/dscinitialization/v1/dscinitialization_types.go
- bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
- docs/api-overview.md
default is a separate mode in the sources, not just selection of one of the others, so allow it explicitly.
There is no difference if it is set to "" explicitly or not set since "" is a string default value.
In the current code as soon as devFlags are present, the mode is taken in use, so it is reset to default even if it is not set which does not look right (I would expect leave it untouched if is not set). If it is fixed, then it will be impossible to reset logging mode to default from devel or prod: if "" is considered as "not set explicitly", then there is no value for default, the object checker rejects values not in list.
> DSCI CRD: allow default as a value for logmode

- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- main.go
- pkg/cluster/cluster_config.go
Cluster configuration is supposed to be the same during operator pod
lifetime. There is no point to detect it on every reconcile cycle
keeping in mind that it can causes many api requests.
Do the initialization on startup. Keep GetOperatorNamespace()
returning error since it defines some logic in the DSCInitialization
reconciler.
Automatically called init() won't work here due to need to check
error of the initialization.
Leave GetDomain() as is since it uses OpenshiftIngress configuration
which is created when DSCInitialization instantiated.
Log cluster configuration on success.
> cluster_config: init cluster variables on startup

- components/codeflare/codeflare.go
- components/component.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/kueue/kueue.go
- components/modelmeshserving/modelmeshserving.go
- components/modelregistry/modelregistry.go
- components/ray/ray.go
- components/trainingoperator/trainingoperator.go
- components/trustyai/trustyai.go
- components/workbenches/workbenches.go
- main.go
Jira: https://issues.redhat.com/browse/RHOAIENG-11592
Image names in environment are not supposed to be changed during
runtime of the operator, so it makes sense to update them only on
startup.
If manifests are overriden by DevFlags, the DevFlags' version will
be used.
The change is straight forward for most of the components where only
images are updated and params.env is located in the kustomize root
directory, but some components (dashboard, ray, codeflare,
modelregistry) also update some extra parameters. For them image
part only is moved to Init since other updates require runtime DSCI
information.
The patch also changes logic for ray, codeflare, and modelregistry
in this regard to update non-image parameters regardless of DevFlags
like it was changed in dashboard recently.
The …
> components: move params.env image updating to Init stage

- main.go
- pkg/logger/logger.go
Allow to tune preconfigured by --log-mode zap backend with standard zap command line switches from controller-runtime (zap-devel, zap-encoder, zap-log-level, zap-stacktrace-level,
zap-time-encoding).
This brings flexibility in logger setup for development environments first of all.
The patch does not change default logger setup and does not change DSCI override functionality.
This is a part of #1268
> logger: add zap command line switches

- controllers/webhook/webhook.go
- main.go
Add webhook.Init() function and hide webhook setup inside of the module. It will make it possible to replace Init with a NOP (no operation) with conditional compilation for no-webhook build.
> webhook: move initialization inside of the module

- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
previously when fixing https://issues.redhat.com/browse/RHOAIENG-12630 for "version not updated during installation with failure", a bug is introduced which only updates the version if it is clean installation, the code does not cover upgrade case.
this change is
- on DSCI: since we only call update on init + successfully reconcoile, so add a new check if existing version value is not the same as the should be value, then update it
- on DSC: we have both successful reconcile and failed reconcile, inject extra update on version into the same call.
- 
https://issues.redhat.com/browse/RHOAIENG-14187
local build:
quay.io/wenzhou/opendatahub-operator-catalog:v2.19.14187
> fix: update release version in DSCI and DSC for upgrade case

- Makefile
- controllers/webhook/nowebhook.go
- controllers/webhook/webhook.go
Make it possible to compile operator without webhook enabled (with -tags nowebhook). Create a stub webhook.Init() function for that.
Add run-nowebhook target to run webhook locally. It requires `make install` to be executed on the cluster beforehand.
Since it repeats `make run`, move the command to a variable. Also use variable RUN_ARGS for operator arguments. It makes it possible to override them from the command line.
In VSCode it is possible to debug it with the following example launch.json configuration:
```
{
"name": "Debug Operator No Webhook",
"type": "go",
"request": "launch",
"mode": "debug",
"program": "main.go",
"buildFlags": [
"-tags", "nowebhook"
],
"env": {
"OPERATOR_NAMESPACE": "opendatahub-operator-system",
"DEFAULT_MANIFESTS_PATH": "./opt/manifests"
},
"args": [ …
```
> Makefile, webhook: add run-nowebhook

- controllers/dscinitialization/utils.go
- main.go
- pkg/cluster/cluster_config.go
- thses 2 fallbacked cases are only needed when it is downstream speicificly
> update: use namespace dyniamically from operator env than hardcode value

- controllers/webhook/webhook.go
Use k8s contextual logger instead of own. Comparing to other parts of the operator webhook is a bit special since it serves own endpoints and has context independent from controllers.
Include more info (operation), just to get more details. Do not add kind since it's clear from "resource" field.
Since controller-framework adds "admission" to the name, use own LogConstructor with own base logger for the framework's DefaultLogConstructor.
Add name locally to distinguish from framework's messages.
Add Name field to the structures to avoid copying string literal for both WithName() and WithValues().
The output changes and it looks like
```
{"level":"info","ts":"2024-10-11T05:17:20Z","logger":"ValidatingWebhook","msg":"Validation request","object":{"name":"default-dsci"},"namespace":"","name":" …
```
> webhook: switch to contextual logger

- controllers/dscinitialization/monitoring.go
- controllers/dscinitialization/utils.go
- pkg/cluster/resources.go
- pkg/cluster/roles.go
- pkg/trustedcabundle/trustedcabundle.go
- tests/e2e/deletion_test.go
- tests/e2e/helper_test.go
- tests/integration/features/cleanup_int_test.go
- tests/integration/features/servicemesh_feature_test.go
- use k8serr as alias to match other places in the code
- use OjectKeyFromObject with object already set for .Get()
local build: 'quay.io/wenzhou/opendatahub-operator:2.19.1014-1'
> chore: use client.OjectKeyFromObject in client.Get() and add k8serr as alias

- .github/workflows/check-file-updates.yaml
(fix): Change on trigger to `pull_request_target` in the "Check config and readme updates / Ensure generated files are included (pull_request)" action to fix "Resource not accessible by integration" error while running the action
The "Check config and readme updates / Ensure generated files are included (pull_request)" action fails when trying to comment on the pr.
There are 2 cases which might cause this
1. The GITHUB_TOKEN does not have a `pull-requests: write` permission.
2. The workflow does not have `Read and Write` permission in the repo.
But the above 2 cases are satisfied for opendatahub-operator.
So the last possible case is to add change `on: pull_request` to `on: pull_request _target`(as per https://github.com/thollander/actions-comment-pull-request?tab=readme-ov-file#permission …
> (fix): Change on trigger to  pull_request_target in the "check-file-updates.yaml" action

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/crd/external/config.openshift.io_authentications.yaml
- config/rbac/role.yaml
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/dscinitialization_test.go
- controllers/dscinitialization/suite_test.go
- main.go
- pkg/cluster/cluster_config.go
- pkg/cluster/const.go
feat: Operator disable create usergroup if detect users enabled external auth
- user internal Authentication CR Type indicate if Operator should create or not
-  only grant "get, watch , list" as least permission
- remove duplicated rbac for "ingress"
- add object into cache 
(a different soltuion than https://github.com/opendatahub-io/opendatahub-operator/pull/1278)
https://issues.redhat.com/browse/RHOAIENG-14214
local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.14214.8
1.
- on a clean cluster, without `odh-admins` group, create
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
name: opendatahub-operator
namespace: openshift-operators
spec:
channel: fast
name: usergroup
source: usergroup
sourceNamespace: openshift-marketplace
InstallPlanApproval: …
```
> feat: Operator disable create usergroup if detect user enabled external auth

- components/codeflare/codeflare.go
- components/component.go
- components/dashboard/dashboard.go
- components/datasciencepipelines/datasciencepipelines.go
- components/kserve/kserve.go
- components/kueue/kueue.go
- components/modelmeshserving/modelmeshserving.go
- components/modelregistry/modelregistry.go
- components/ray/ray.go
- components/trainingoperator/trainingoperator.go
- components/trustyai/trustyai.go
- components/workbenches/workbenches.go
- controllers/datasciencecluster/datasciencecluster_controller.go
Jira: https://issues.redhat.com/browse/RHOAIENG-14366
Switch ReconcileComponent from passing logger explicitly to wrapping
it into context[1][2]
Makes one parameter less to pass and will allow called utilities to
report component context where they are called from.
No user or logging format impact until utilities takes contextual
logging in use.
[1] https://www.kubernetes.dev/blog/2022/05/25/contextual-logging/
[2] https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/3077-contextual-logging/README.md
Credits-To: Bartosz Majsak <bartosz.majsak@gmail.com>
Signed-off-by: Yauheni Kaliuta <ykaliuta@redhat.com>
> components, logger: use contextual logging approach

- pkg/cluster/cluster_config.go
- previous code, will run into "opendathaub" case if env is not set
- change make in both "not set" and "set to empty string" fall back to old logic with auto detection
related to change from  https://github.com/opendatahub-io/opendatahub-operator/pull/1252
> fix: to make the unset env variable in CSV work with fallback

- components/kserve/servicemesh_setup.go
- controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/monitoring.go
- controllers/dscinitialization/servicemesh_setup.go
- controllers/dscinitialization/suite_test.go
- controllers/dscinitialization/utils.go
- controllers/secretgenerator/secretgenerator_controller.go
- main.go
- pkg/cluster/resources.go
- pkg/upgrade/uninstallation.go
- pkg/upgrade/upgrade.go
Jira: https://issues.redhat.com/browse/RHOAIENG-14096
This is a squashed commit of the following patches:
d012b67bc139 ("controllers: switch to k8s contextual logger")
98805300894c ("logger: blindly convert ctrl.Log users to contextual")
- controllers: switch to k8s contextual logger
Remove own logger from controllers' reconcilers and switch to k8s contextual logger instead [1].
Use contextual logger for SecretGeneratorReconciler and CertConfigmapGeneratorReconciler setups as well.
Add name to the logger coming from the framework. It will contains "controller" field already, and like in webhook with the name it's easy to distinguish framework and operator messages.
- logger: blindly convert ctrl.Log users to contextual
All the users should have proper context now. The log level changes …
> controllers: switch to k8s contextual logger

- Makefile
- The suggestion to tidy up the run-nowebhook recipe comes from this conversation:
https://github.com/opendatahub-io/opendatahub-operator/pull/1304/files#r1806731373
- I believe `clean` should be a PHONY task, since it doesn't create a file called `clean`
I verified that the expected commands would be run as part of the `run-nowebhook` target:
```
➜ make --dry-run run-nowebhook
test -s /var/home/gryan/src/github.com/opendatahub-io/opendatahub-operator/bin/controller-gen || GOBIN=/var/home/gryan/src/github.com/opendatahub-io/opendatahub-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.16.1
/var/home/gryan/src/github.com/opendatahub-io/opendatahub-operator/bin/controller-gen rbac:roleName=controller-manager-role crd:ignoreUnexportedFields=true webhook paths="./..." …
```
> Tidy up run-nowebhook recipe & make clean PHONY

- controllers/secretgenerator/secretgenerator_controller.go
- controllers/secretgenerator/secretgenerator_controller_test.go
The PR is meant to:
- make the code easier to understand, reducing complexity caused by nested if/else and error conditions (align happy path to the left)
- remove shadowed error vars to avoid reporting misleading errors
- add some basic unit test for the reconcile loop
- This does not change the behavior, the default test suite should not be affected. 
- Additional unit test case have been added
> Refactor secret generator controller

- README.md
- apis/dscinitialization/v1/dscinitialization_types.go
- config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- docs/api-overview.md
- main.go
- pkg/logger/logger.go
Jira: https://issues.redhat.com/browse/RHOAIENG-14713
This is a squashed commit of the patchset (original ids):
959f84d33fa9 ("logger: import controller-runtime zap as ctrlzap")
7b8e988d8bab ("logger: add logLevel to DSCI devFlags")
2d3efe27c38b ("components, logger: always use controller's logger")
1ef9266fbf23 ("components, logger: use one function for ctx creation")
- logger: import controller-runtime zap as ctrlzap
To avoid patch polluting with the next changes where uber's zap is imported as `zap`.
- logger: add logLevel to DSCI devFlags
Allow to override global zap log level from DSCI devFlags. Accepts the same values as to `--zap-log-level` command line switch.
Use zap.AtomicLevel type to store loglevel. Locally use atomic to store its value. We must store the structure itsel since …
> logger: add logLevel to DSCI devFlags

- bundle/manifests/components.opendatahub.io_codeflares.yaml
- bundle/manifests/components.opendatahub.io_dashboards.yaml
- bundle/manifests/components.opendatahub.io_datasciencepipelines.yaml
- bundle/manifests/components.opendatahub.io_kserves.yaml
- bundle/manifests/components.opendatahub.io_kueues.yaml
- bundle/manifests/components.opendatahub.io_modelmeshservings.yaml
- bundle/manifests/components.opendatahub.io_modelregistries.yaml
- bundle/manifests/components.opendatahub.io_rays.yaml
- bundle/manifests/components.opendatahub.io_trainingoperators.yaml
- bundle/manifests/components.opendatahub.io_trustyais.yaml
- bundle/manifests/components.opendatahub.io_workbenches.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/components/dashboard/dashboard_controller.go
- controllers/datasciencecluster/kubebuilder_rbac.go
- builder marker only work with type struct definition either we move all these back to the rbac file with DSC or add into API for each => up for decide later
> fix: missing rbac on dashbaord component to start Operator from CSV

- controllers/secretgenerator/secretgenerator_controller.go
- controllers/secretgenerator/secretgenerator_controller_test.go
Previously, if the secret was not found, an error would be reported, despite the fact that the secret would be created later during reconcile.
The change in this PR intends to avoid reporting that 'Secret not found' error case
JIRA reference: [RHOAIENG-14189](https://issues.redhat.com/browse/RHOAIENG-14189)
> secret-generator controller: avoid reporting 'Secret not found' error in reconcile

- components/modelmeshserving/modelmeshserving.go
https://issues.redhat.com/browse/RHOAIENG-13411
> update: remove two SA which does not seem valid

- controllers/datasciencecluster/datasciencecluster_controller.go
- main.go
-  we should watch IngressController from operator.openshift.io, not the k8s ingress
-  this matched the cache we added in main
> fix: wrong type of ingresscontroller

- main.go
> fix: missing comopnent init step for Ray in main

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/components/codeflare/codeflare_controller.go
- controllers/components/datasciencepipelines/datasciencepipelines_controller.go
- controllers/components/kserve/kserve_controller.go
- controllers/components/kueue/kueue_controller.go
- controllers/components/modelmeshserving/modelmeshserving_controller.go
- controllers/components/modelregistry/modelregistry_controller.go
- controllers/components/ray/ray.go
- controllers/components/ray/ray_controller.go
- controllers/components/trainingoperator/trainingoperator_controller.go
- controllers/components/trustyai/trustyai_controller.go
- controllers/components/workbenches/workbenches_controller.go
- controllers/datasciencecluster/kubebuilder_rbac.go
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/kubebuilder_rbac.go
- controllers/dscinitialization/monitoring.go
- pkg/cluster/cluster_config.go
- tests/e2e/helper_test.go
- remove duplicated
- move monitoring's to DSCI for now
- move component dedicated to their block
- move DSC as const in e2e: fix lint
> chore: rbac cleanup + lint fix

- controllers/components/dashboard/dashboard_controller.go
- controllers/components/dashboard/dashboard_controller_actions.go
- controllers/components/modelregistry/modelregistry_controller.go
- controllers/components/ray/ray_controller.go
- pkg/controller/actions/render/action_render_manifests_test.go
- pkg/controller/handlers/handlers.go
- pkg/controller/reconciler/component_reconciler_support.go
- pkg/metadata/labels/types.go
- tests/e2e/dashboard_test.go
- tests/e2e/modelregistry_test.go
- tests/e2e/ray_test.go
This commit replaces then label components.opendatahub.io/managed-by
with components.opendatahub.io/part-of as managed-by was misleading
since the label is mainly used for watching and request mapping
> Replace components.opendatahub.io/managed-by with components.opendatahub.io/part-of

- pkg/trustedcabundle/trustedcabundle.go
- missing newline will cause problem when inject data into configmap
- this happens when user use kustomize with their own CA as overlayer for DSCI, it set to use |- not |
related to https://github.com/kubernetes-sigs/kustomize/issues/4602
i am not fond of the solution provided in https://issues.redhat.com/browse/RHOAIENG-11895 on a component base.
this could protentially cause other components to fail.
quay.io/wenzhou/opendatahub-operator:2.20.114
1. input
```
trustedCABundle:
customCABundle: -----BEGIN CERTIFICATE-----
MIIFVjCCAz6gAwIBAgIUQ+NxE9izWRRdt86M/TX9b7wFjUUwDQYJKoZIhvcNAQEL
...
IrrVQJLuM7IjWcmOvFjai57QGfIvWcaMY1q6n6MLsLOaXLoRuBLpDLvPbmyAhykU
------END ------
```
output in CM:
```
odh-ca-bundle.crt: |
-----BEGIN CERTIFICATE----- …
```
> fix: ensure input CAbundle always end with a newline

- Makefile
- README.md
- tests/e2e/controller_test.go
- tests/e2e/creation_test.go
- tests/e2e/dashboard_test.go
- tests/e2e/modelregistry_test.go
- tests/e2e/ray_test.go
It is not possible to control which e2e test should be executed by passing some flags to the e2e test suite using the `E2E_TEST_FLAGS` env var.
The new flags are:
- `--test-operator-controller` which control the execution of the test meant to validate the operator pod, default **true**
- `--test-webhook`  which control the execution of webhook related tests, default **true**
- `--test-component` a repeatable flag that control what component should be teste, by default all component specific test are executed
As an example, the following command:
```shell
➜  make e2e-test E2E_TEST_FLAGS="--test-operator-controller=false --test-webhook=false --test-component=dashboard"
```
Would result in the following test being executed:
```shell
controller=false --test-webhook=false …
```
> Allow to run the e2e test suite locally, against an out of the cluster operator

- components/modelregistry/modelregistry.go
- pkg/upgrade/upgrade.go
Add check to remove old kube-rbac-proxy container in modelregistry operator
Fixes[ RHOAIENG-15328](https://issues.redhat.com/browse/RHOAIENG-15328)
Tested locally by creating a DSC with MR, and manually adding a kube-rbac-proxy container with the following commands:
```shell
cat - >> rbac-container.yaml << EOF
spec:
template:
spec:
containers:
- args:
- --secure-listen-address=0.0.0.0:8443
- --upstream=http://127.0.0.1:8080/
- --logtostderr=true
- --v=0
- --tls-cert-file=/etc/server-cert/tls.crt
- --tls-private-key-file=/etc/server-cert/tls.key
image: gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1
name: kube-rbac-proxy
ports:
- containerPort: 8443
name: https
protocol: TCP
resources:
limits:
cpu: 500m
memory: 128Mi
requests:
cpu: 5m
memory: 64Mi
securityContext:
allowPrivilegeEscalation: …
```
> fix: add check to remove old kube-rbac-proxy container in modelregistry operator, fixes RHOAIENG-15328

- controllers/components/dashboard/dashboard_controller.go
- controllers/components/modelregistry/modelregistry_controller.go
- controllers/components/ray/ray_controller.go
- pkg/controller/actions/render/kustomize/action_render_manifests.go
- pkg/controller/actions/render/kustomize/action_render_manifests_support.go
- pkg/controller/actions/render/kustomize/action_render_manifests_test.go
- pkg/controller/actions/render/render_metrics.go
- pkg/metadata/annotations/annotations.go
This commit is meant to cleanup the kustomize manifest redering by:
- removing a useless parameter related to the caching mechanism
- moving the code to the kustomize package to accomodate other rendering
engines
- introduce metrics tro track how many resources have been rendered and
to perform blackbox testing against the action
```shell
➜ http :8080/metrics | grep action
action_renderer_manifests_total{controller="dashboard",engine="kustomize"} 36
```
> Cleanup kustomize manifests rendering action

- controllers/components/dashboard/dashboard_support.go
- pkg/controller/actions/security/actions.go
- pkg/controller/actions/security/actions_test.go
in modelmesh case, it need to pass in a bunch of SA
to extend the support for this case
> chore: support NewUpdatePodSecurityRoleBindingAction with multiple serviceaccounts

- config/manager/kustomization.yaml.in
- pkg/trustedcabundle/trustedcabundle.go
- pkg/upgrade/upgrade.go
cherry-pick ODH change from incubation 
- https://github.com/opendatahub-io/opendatahub-operator/pull/1339
- https://github.com/opendatahub-io/opendatahub-operator/pull/1341
- dummy change to verify auto-sync is working 
https://issues.redhat.com/browse/RHOAIENG-15328
> [sync]: change from incubation to rhoai + dummy change

- pkg/cluster/operator.go
- pkg/feature/servicemesh/conditions.go
- tests/integration/features/fixtures/cluster_test_fixtures.go
- tests/integration/features/servicemesh_feature_test.go
mainly delay smcp creation till smcp CRD is in place and smcp validation service is created => by those two condtiion, we can ensure ossm operator is installed and to-be-created smcp CR wont need another conversion.
https://issues.redhat.com/browse/RHOAIENG-15227
to mimic auto DSCI creation, update subscriptoin and to apply by gitop
>oc apply gitops.yaml
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
name: servicemeshoperator
namespace: openshift-operators
spec:
channel: stable
installPlanApproval: Automatic
name: servicemeshoperator
source: redhat-operators
sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
name: gitopsway
namespace: openshift-marketplace
spec:
displayName: gitopsway
image: …
```
> fix: add extra check on servicemesh CRD and svc before proceeding create SMCP CR

- controllers/components/dashboard/dashboard_controller.go
- controllers/components/kueue/kueue_controller.go
- controllers/components/modelregistry/modelregistry_controller.go
- controllers/components/modelregistry/modelregistry_controller_actions.go
- controllers/components/modelregistry/modelregistry_support.go
- controllers/components/modelregistry/resources/servicemesh-member.tmpl.yaml
- controllers/components/ray/ray_controller.go
- controllers/components/trainingoperator/trainingoperator_controller.go
- controllers/components/trustyai/trustyai_controller.go
- pkg/controller/actions/render/kustomize/action_render_manifests_test.go
- pkg/controller/actions/render/render_support.go
- pkg/controller/actions/render/template/action_render_templates.go
- pkg/controller/actions/render/template/action_render_templates_test.go
- pkg/controller/actions/render/template/resources/smm-data.tmpl.yaml
- pkg/controller/actions/render/template/resources/smm.tmpl.yaml
- pkg/controller/predicates/resources/resources.go
- pkg/controller/reconciler/component_reconciler.go
- pkg/controller/reconciler/component_reconciler_support.go
- pkg/controller/types/types.go
- pkg/resources/resources.go
This PR introduces a new rendering engine that is based on the go text/template package.
The template is rendered to the actual objects taking a subset of the `ReconciliationRequest` struct: `Instance` and `DSCI` so as an example, the `ServiceMeshMember` template that is part of the model registry component would looks like:
```yaml
apiVersion: maistra.io/v1
kind: ServiceMeshMember
metadata:
name: default
namespace: {{.Instance.Spec.RegistriesNamespace}}
spec:
controlPlaneRef:
namespace: {{ .DSCI.Spec.ServiceMesh.ControlPlane.Namespace }}
name: {{ .DSCI.Spec.ServiceMesh.ControlPlane.Name }}
```
https://issues.redhat.com/browse/RHOAIENG-15534
1. Enable the model registry component in DSC
2. Check for the presence of a  `ServiceMeshMember` instance in the model registries namespace named …
> Implement template rendering action

- README.md
- pkg/logger/logger.go
Add possibility to set loglevel with the environment. The name is used used already.
Command line switch has priority over environment.
[1] https://github.com/opendatahub-io/data-science-pipelines-operator/blob/main/config/base/params.env#L13
> logger: set loglevel from ZAP_LOG_LEVEL environment variable

- pkg/feature/conditions.go
Tracking issue: RHOAIENG-15614
I experienced a problem in a cluster, in namespace `opendatahub-auth-provider` there was a pod in `Evicted` state and another one Ready and working correctly.
When DSCi tried to reconcile on `CapabilityServiceMeshAuthorization` it failed with the following error:
```
{"level":"info","ts":"2024-10-31T15:23:27Z","logger":"features","msg":"waiting for pods to become ready","feature":"mesh-control-plane-external-authz","namespace":"istio-system","duration (s)":300}
{"level":"info","ts":"2024-10-31T15:23:29Z","logger":"features","msg":"done waiting for pods to become ready","feature":"mesh-control-plane-external-authz","namespace":"istio-system"}
{"level":"info","ts":"2024-10-31T15:23:29Z","logger":"features","msg":"waiting for pods to become …
```
> fix: added a filter to evicted pods when checking for ready status

- pkg/upgrade/upgrade.go
Version 2.16 will include the GA version of NVIDIA NIM integration. Cleaning up the TP version's resources introduced in 2.15 is required.
https://issues.redhat.com/browse/NVPE-32
```shell
go fmt
make lint
make test
go mod tidy
```
> Task/NVPE-32: Cleanup NIM integration tech preview resources

- pkg/upgrade/upgrade.go
sync https://github.com/opendatahub-io/opendatahub-operator/pull/1369
cc @TomerFi
https://issues.redhat.com/browse/NVPE-32
> [sync]: Cleanup NIM integration tech preview resources 

- pkg/cluster/operator.go
- pkg/feature/servicemesh/conditions.go
- tests/integration/features/fixtures/cluster_test_fixtures.go
- tests/integration/features/servicemesh_feature_test.go
* fix: add extra check on servicemesh CRD and service before proceeding create SMCP CR
- when we install operator we might have a race condition:
- ossm is not ready to server
- dsci already created smcp CR
- since we do not know the version of smcp to use
- ossm webhook can run into conversion problem since no version specify in smcp CR
-  test: add more negative test
- when CRD does not exist
- when service does not exist
---------
(cherry picked from commit e25487a7deef512762a672cad1066c23baf125ba)
https://issues.redhat.com/browse/RHOAIENG-15227
> [sync] fix: add extra check on servicemesh CRD and svc before proceeding create SMCP CR (#1359)

- Dockerfiles/Dockerfile
- Makefile
The commit
a107703442c6 ("feat(fips): enable GO_ENABLED in build (#1001)")
enabled CGO which makes problems for builders on non-x86 platforms.
Make it as an in the Dockerfile keeping default the same (enabled),
but make it possible to override with either environment
(`export CGO_ENABLED=0`) or make (`make CGO_ENABLED=0 image-build`)
> Dockerfile, Makefile: make CGO_ENABLED configurable

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
- main.go
to fix error:
```
E1118 18:36:29.170234       1 reflector.go:147] go/pkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.PrometheusRule: unknown (get prometheusrules.monitoring.coreos.com)
E1118 18:36:32.323559       1 reflector.go:147] go/pkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.PrometheusRule: unknown (get prometheusrules.monitoring.coreos.com)
E1118 18:36:35.841907       1 reflector.go:147] go/pkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.PrometheusRule: unknown (get prometheusrules.monitoring.coreos.com)
E1118 18:36:47.923199       1 reflector.go:147] go/pkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.PrometheusRule: unknown (get …
```
> fix: missing watch on prometheusrules and verb watch

- Makefile
- README.md
Get USE_LOCAL image build flag from makefile variable to make it overridable with `make USE_LOCAL=true image`
Do not allow to get its value for environment be default due to pretty generic name.
This is shorter than the old recommendation of overriding  IMAGE_BUILD_FLAGS. And since now CGO_ENABLED is also a flag, does not mess up with it.
* USE_LOCAL=true uses existing manifests from opt/manifests for the produced image without downloading them with get_all_manifests.sh making it possible to both save time and make local amendments.
> Makefile: make USE_LOCAL overridable

- Dockerfiles/Dockerfile
We can combine two build stages into one, as there is no need to always build both images (not done by podman) to only then decide from which one we want to copy manifests to the target image. Instead manifests stage will either copy local manifests or fetches using the script based on USE_LOCAL argument.
Move USE_LOCAL and OVERWIRTE_MANIFESTS args under FROM since args have scope of the FROM they are declared in.
It requires opt/manifests directory to exist, but since it's a part of git repo, it's fine.
Original patch from: Bartosz Majsak <bartosz.majsak@gmail.com> [1]
[1] https://github.com/opendatahub-io/opendatahub-operator/pull/773
> Dockerfile: merges manifests builder stages to one

- .golangci.yml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/components/dashboard/dashboard.go
- controllers/components/dashboard/dashboard_controller.go
- controllers/components/datasciencepipelines/datasciencepipelines.go
- controllers/components/datasciencepipelines/datasciencepipelines_controller.go
- controllers/components/kueue/kueue.go
- controllers/components/kueue/kueue_controller.go
- controllers/components/modelregistry/modelregistry.go
- controllers/components/modelregistry/modelregistry_controller.go
- controllers/components/ray/ray.go
- controllers/components/ray/ray_controller.go
- controllers/components/trainingoperator/trainingoperator.go
- controllers/components/trainingoperator/trainingoperator_controller.go
- controllers/components/trustyai/trustyai.go
- controllers/components/trustyai/trustyai_controller.go
- controllers/datasciencecluster/kubebuilder_rbac.go
- pkg/cluster/gvk/gvk.go
- pkg/controller/handlers/handlers.go
- pkg/controller/predicates/resources/resources.go
- pkg/controller/reconciler/component_reconciler.go
- pkg/controller/reconciler/component_reconciler_actions.go
- pkg/controller/reconciler/component_reconciler_metrics.go
- pkg/controller/reconciler/component_reconciler_support.go
- pkg/resources/resources.go
- tests/e2e/controller_test.go
- tests/e2e/dashboard_test.go
- tests/e2e/modelregistry_test.go
Signed-off-by: Luca Burgazzoli <lburgazzoli@gmail.com>
https://issues.redhat.com/browse/RHOAIENG-15170
> Support to watch/own object not known when the operator starts, but only after a component has been enabled.

- pkg/services/gc/gc.go
If the GC service is not authorixed to list some particular types, it
emits a message "cannot list resource" that may be misleading as it does
not impact the behavior of the GC service. This commit set the log
verbosity to 3 so it is not shown by default, but can be enabled
eventually for troubleshooting
> Reduce log verbosity for the gc service

- config/monitoring/prometheus/apps/prometheus-configs.yaml
- tests/prometheus_unit_tests/codeflare-alerting.unit-tests.yaml
- tests/prometheus_unit_tests/data-science-pipelines-operator-alerting.unit-tests.yaml
- tests/prometheus_unit_tests/kserve-alerting.unit-tests.yaml
- tests/prometheus_unit_tests/model-mesh-alerting.unit-tests.yaml
- tests/prometheus_unit_tests/odh-model-controller-alerting.unit-tests.yaml
- tests/prometheus_unit_tests/rhods-dashboard-alerting.unit-tests.yaml
- tests/prometheus_unit_tests/trustyai-alerting.unit-tests.yaml
- tests/prometheus_unit_tests/workbenches-alerting.unit-tests.yaml
Give unique names to alerts to give more info about what is firing
`make test-alerts`
> Unique alert names

- components/kueue/kueue.go
- components/ray/ray.go
- components/workbenches/workbenches.go
I noticed a typo from messages shown in the DSC, i.e.,:
```
- lastHeartbeatTime: '2024-11-29T16:22:36Z'
lastTransitionTime: '2024-11-29T16:22:36Z'
message: 'Component reconciliation failed: failed to apply manifetss /opt/manifests/kueue/rhoai: no matches for kind "ValidatingAdmissionPolicy" in version "admissionregistration.k8s.io/v1alpha1"'
reason: ReconcileFailed
status: 'False'
```
> Typo fixes "manifests"

- pkg/controller/reconciler/component_reconciler_actions.go
- pkg/controller/reconciler/component_reconciler_actions_test.go
- pkg/controller/reconciler/component_reconciler_support.go
In some case, a dynamic watcher should be conditionally registered, as
an example, when a component depends on a specific operator to be
installed, then it should be possible to register a dynamic watcher with
a predicate, so the actual watch is registered only if the predicate
succeed.
> Make it possible to define predicates along with a dynamic watcher

- pkg/controller/actions/deploy/action_deploy.go
- pkg/controller/actions/deploy/action_deploy_test.go
For `ClusterRole`, if `AggregationRule` is set, then the Rules are controller managed and direct changes to Rules will be stomped by the controller. This also happen if the rules are set to an empty slice or nil. This commit add a special handling for the `ClusterRole` resource so that the `rules` filed is removed in case aggregation is configured.
1. Enable `KServe`
2. Watch for a `ClusterRole` named `kserve-admin`
3. if a reconcile kicks in i.e. because `KServe` pods are deleted, then the `ClusterRole` named `kserve-admin` should not receive updates
> Add special handling for Aggregatin ClusterRole

- Dockerfiles/Dockerfile
- Makefile
- OWNERS_ALIASES
- README.md
https://github.com/opendatahub-io/opendatahub-operator/pull/1376
https://github.com/opendatahub-io/opendatahub-operator/pull/1382
https://github.com/opendatahub-io/opendatahub-operator/pull/1384
https://github.com/opendatahub-io/opendatahub-operator/pull/1381
+ a fix
> [Sync]: incubation to  rhoai

- pkg/controller/actions/deploy/action_deploy.go
- pkg/controller/actions/deploy/action_deploy_cache.go
- pkg/controller/actions/deploy/action_deploy_cache_test.go
> Add an option to set the deployment action cache TTL

- config/monitoring/prometheus/apps/prometheus-configs.yaml
**JIRA:** [RHOAIENG-16229](https://issues.redhat.com/browse/RHOAIENG-16229)
This is a fix for #1397 
That PR missed alert renaming for Model Registry Operator.
/cc @StevenTobin @grdryn @jackdelahunt 
Using PR checks, no testing needed as model registry doesn't have alert tests yet.
Not applicable.
@cc
> fix: RHOAIENG-16229 - Renaming Alerts

- .github/workflows/check-file-updates.yaml
- .github/workflows/comment-on-pr.yaml
Using pull_request_target event trigger results in security vulnerabilities explained here: https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
According to the suggestion:
Create 2 separate actions, one for executing the required `make`commands and one for commenting on the pr.
The comment-on-pr workflow will run only if changes are seen in the manifests or docs.
Since data propagation does not happen between workflows, it is advised to use the artifacts of GHA.
The artifacts created by the workflows for each pr will be cleared daily by GHA itself.
JIRA: https://issues.redhat.com/browse/RHOAIENG-15377
Tested in my fork
result: https://github.com/AjayJagan/opendatahub-operator/pull/593#issuecomment-2513748819
> (fix): Avoid using pull_request_target event trigger.

- .github/workflows/linter.yaml
- Makefile
- controllers/dscinitialization/suite_test.go
- controllers/webhook/webhook_suite_test.go
- Fixes some linters findings 
- Use `make lint` target also for github action to ensure that we use the same linter version
- Add a dedicated `make lint-fix` target to automatically fix some of the lint findings and removing automatic fix from the `make lint` target
> Fix linters

- controllers/dscinitialization/suite_test.go
- controllers/webhook/webhook_suite_test.go
- pkg/controller/reconciler/reconciler.go
When the common reconciler detect that a resource is amrked for
deletion, it shoudl not try to lookup the DSCI as it should be possible
to remove a resource even if the DSCI is not present to avoid deadlocks.
To make the code more clear, the Reconcile method has been split in:
- delete, which triggers the execution of the finalizer actions
- apply, which triggers the execution od the reconcile actions
Notes:
- requires https://github.com/opendatahub-io/opendatahub-operator/pull/1432
> A reconciler should not require the DSCI to perform cleanup action to avoid deadlock

- apis/components/v1alpha1/modelcontroller_types.go
- bundle/manifests/components.platform.opendatahub.io_modelcontrollers.yaml
- config/crd/bases/components.platform.opendatahub.io_modelcontrollers.yaml
- controllers/components/modelcontroller/modelcontroller_actions.go
- docs/api-overview.md
- pkg/resources/resources.go
- remove the need to lookup DSC
- remove .status.uri to avoid cluttering the API and add debug log
statement to trace down the selected DevFlags
> Refactor modelcontroller DevFlags handling

- go.mod
-------
JIRA: https://issues.redhat.com/browse/RHOAIENG-16819
It seems like on some platforms, when the local installation
installation of Go decides that it needs to download a different
toolchain, that it may fail unless we either specify a full x.y.z
version in the `go` directive, or explicitly specify the `toolchain`
directive.
I believe for our uses, using a fully specified x.y.z `go` directive
value is preferable, to prevent any issues with explicitly defining a
toolchain where we might have a newer version in a container image
build that has a default of `GOTOOLCHAIN='local'` (I'm not 100% sure
if that would cause any issues, but I'm 100% sure that the way
proposed in this commit shouldn't).
- builds fine
- runs fine
> Specify full x.y.z version of Go in go.mod

- apis/common/types.go
- pkg/controller/actions/render/kustomize/action_render_manifests.go
- pkg/controller/actions/render/template/action_render_templates.go
> Remove WithDevFlags interface from PlatformObject since not every entity supports dev flags

- Makefile
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/datasciencecluster/kubebuilder_rbac.go
- controllers/setupcontroller/setup_controller.go
- main.go
- pkg/upgrade/uninstallation.go
JIRA: [RHOAIENG-16674](https://issues.redhat.com/browse/RHOAIENG-16674)
Created a new setup-controller and moved the below functionalities to uninstallation.go if `HasDeleteConfigMap` exists 
- Deletion of the DataScienceCluster instance
- Operator uninstall 
- Existing workflow 
Testing process : 
- install cluster 
- create dsc and dsci
- create `delete-configmap` with 
```
labels:
api.openshift.com/addon-managed-odh-delete: 'true'
```
- check dsc and dsci deletion and logs for deletion of other resources
> Migration uninstall configmap from DSC to setup controller

- controllers/components/modelregistry/modelregistry.go
Starting with version v2.22.0, the `DEFAULT_CERT` value in the `params.env` file for the model registry operator is not updated with the value from
```go
extraParamsMap = map[string]string{
"DEFAULT_CERT": DefaultModelRegistryCert,
}
```
The problem seems to be that the extraParamsMap was merged with imageParams when it was passed to the `odhdeploy.ApplyParams` function, here the second argument went through
```go
// 1. Update images with env variables
// e.g "odh-kuberay-operator-controller-image": "RELATED_IMAGE_ODH_KUBERAY_OPERATOR_CONTROLLER_IMAGE",
for i := range paramsEnvMap {
relatedImageValue := os.Getenv(imageParamsMap[i])
if relatedImageValue != "" {
updated |= updateMap(&paramsEnvMap, i, relatedImageValue)
}
}
```
instead of 
```go
// 2. Update other fileds with extraParamsMap …
```
> fix: bug not filling params.env with default cert value in model registry operator

- .github/workflows/pre-release.yaml
Change the GH actions for release process to target main branch.
> (fix): change gha to target main

- tests/e2e/codeflare_test.go
- tests/e2e/datasciencepipelines_test.go
- tests/e2e/helper_test.go
- tests/e2e/kueue_test.go
- tests/e2e/ray_test.go
- tests/e2e/trainingoperator_test.go
- tests/e2e/trustyai_test.go
- tests/e2e/workbenches_test.go
The tests to validate the correctness of the operator when components
are disabled have been refactored to:
1. take into account all the component's deployments, not only the first
one to avoid swallowing misbehavior
2. remove useless waiting time before checking the presence of
component's deployments because within the introduction of the
internal APIs, the object hierarchy now allow for a proper cleanup as
all the object have a proper owner reference. The operator deletes
the component API using foreground deletion policy hence once the top
level component CR is removed, the all the owned objects should have
been deleted too.
> Remove useless e2e sleep time

- pkg/deploy/deploy.go
This PR fixes an issue in the `DownloadManifests` function where the parameters `componentName` and `contextDir` were passed in the wrong order to the `resolveTargetPath` function.
The incorrect order caused downloaded component manifests to be ignored, preventing them from overwriting existing local manifest files as intended.
Fixing https://issues.redhat.com/browse/RHOAIENG-17146
> Fix parameter order in resolveTargetPath to ensure manifest overwrite

- pkg/upgrade/upgrade.go
This PR replaces https://github.com/opendatahub-io/opendatahub-operator/pull/1458.
Following the merge of https://github.com/opendatahub-io/odh-dashboard/pull/3535, we can use a naming convention to create the resources owned by NIM runtimes instead of static names. This means that if upgrading from 2.14-2.16, we need to look for and delete the static-named resources. Deleting them will trigger a reconciliation that will create them with the correct names.
For the resources created with the new naming conventions, see https://github.com/opendatahub-io/odh-model-controller/pull/340.
Jira: [NVPE-29](https://issues.redhat.com/browse/NVPE-29)
Slack: [thread](https://redhat-internal.slack.com/archives/C07CZDA6DE1/p1734382422391069)
```shell
make unit-test
make build
```
> chore: cleanup static-named nim resources for switching to naming convention

- pkg/upgrade/upgrade.go
Reverts opendatahub-io/opendatahub-operator#1454
Original change is inteneded for "main" branch but was accidently merged into "incubation"
since we only need "incubation" for future's critical backport, thus have this PR reverted
> Revert "chore: fixed typo in the logs"

- get_all_manifests.sh
There is no point to set target folder explicitly if it can be the same as the component name.
The patch is a step to unification of component names.
In the error message for overriding with an option also `branch-name` replaced to `ref-name`. Leftover.
For odh-notebook-controller subcomponents directory is a part of the key.
> get_all_manifests.sh: use key (component name) as the target folder

- apis/components/v1alpha1/kserve_types.go
- bundle/manifests/components.platform.opendatahub.io_kserves.yaml
- bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/crd/bases/components.platform.opendatahub.io_kserves.yaml
- config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- controllers/components/kserve/config.go
- controllers/components/kserve/kserve_controller.go
- controllers/components/kserve/kserve_controller_actions.go
- controllers/components/kserve/kserve_support.go
- docs/api-overview.md
- tests/e2e/helper_test.go
- tests/e2e/kserve_test.go
JIRA: https://issues.redhat.com/browse/RHOAIENG-16240
The dashboard would like to be able to read this value, and should
only read it from the status.
The value for the status is always read from the KServe ConfigMap,
rather than ever assuming that what is set in the DSC, or what the
operator defaults to, is correct: this is because that ConfigMap can
be annotated to be unmanaged by the operator, in which case a user may
have changed the value to something else, and the status should
reflect this reality.
- Manually during development
- including setting the ConfigMap to not be managed, and changing the value from what the operator would have set, and seeing that reflected in the Kserve and DSC CRs
- e2e test has been updated to check for the field
> Show KServe defaultDeploymentMode in DSC status

- .golangci.yml
-------
Before (see warnings):
```
➜ make lint
test -s /var/home/gryan/src/github.com/opendatahub-io/opendatahub-operator/bin/golangci-lint || { curl -sSfL 'https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh' | bash -s v1.61.0; }
/var/home/gryan/src/github.com/opendatahub-io/opendatahub-operator/bin/golangci-lint run --timeout=5m0s --sort-results
WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar. 
WARN The linter 'execinquery' is deprecated (since v1.58.0) due to: The repository of the linter has been archived by the owner.  
```
After (no warnings):
```
➜ make lint
test -s /var/home/gryan/src/github.com/opendatahub-io/opendatahub-operator/bin/golangci-lint || { …
```
> chore: disable deprecated linters

- .github/workflows/unit-tests.yaml
- codecov.yml
Updating the codecov-actions version for the unit tests Github actions workflow to the latest 5.1.2 version + adding codecov config yaml file at repo level to define main branch as default
> update codecov-actions version and add codecov config file to repo

- controllers/components/kserve/kserve_support.go
- controllers/components/kserve/resources/servicemesh/kserve-inferencegraph-authorizationpolicy.tmpl.yaml
- controllers/components/kserve/resources/servicemesh/kserve-inferencegraph-envoyfilter.tmpl.yaml
This adds resources required to support auth for KServe InferenceGraphs.
https://issues.redhat.com/browse/RHOAIENG-13449
Other related PRs:
* opendatahub-io/kserve#463
* opendatahub-io/odh-model-controller#345
1. Deploy operator
2. Install KServe
3. Check that the new resources are present
> feat: KServe InferenceGraph auth configurations [main]

- codecov.yml
This configuration will make codecov informational and will not block to merge on Pull Requests as first step defined on:
https://about.codecov.io/blog/the-5-levels-of-code-coverage-how-to-build-a-testing-culture-in-your-organization/
> codecov config to show code coverage numbers on every PR as informational and not blocking

- tests/e2e/creation_test.go
- tests/e2e/helper_test.go
Reverts opendatahub-io/opendatahub-operator#1434
> Revert "tests: e2e test for trusted-ca-bundle"

- apis/dscinitialization/v1/dscinitialization_types.go
- bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
- config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
- docs/api-overview.md
- we do not use this for devFlag in DSCI any more
- it was used when we still have odh-manifests repo
- if use would set devFlags, it should be done in DSC on component base
- keep logic still in code but only set warning on API
> docs(api): set manifestUri as deprecated

- README.md
Adding a codecov badge to see the overall code coverage status of the repo
> chore: add codecoverage badge to Readme

- config/monitoring/prometheus/apps/prometheus-configs.yaml
With the deprecation of kube-rbac-proxy  , we have changed the /metrics  port to 8443 . And so the prometheus.yml file contained redhat-ods-monitoring/prometheus must be updated also to reflect that change.
> RHOAIENG-18095: Deprecation of kube-rbac-proxy

- tests/e2e/authcontroller_test.go
- tests/e2e/controller_test.go
(cherry picked from commit 3b18522c319810b82d8af86a6faf63daf26d9528)
> Update Auth controller tests for RHOAI

- docs/COMPONENT_INTEGRATION.md
Added an initial proposal for the updated guide that describes new component integration/onboarding. This guide reflects the changes brought by the ODH operator reconciliation refactor.
JIRA ref: [RHOAIENG-13482](https://issues.redhat.com/browse/RHOAIENG-13482)
> docs: Add updated component integration guide

- controllers/datasciencecluster/datasciencecluster_controller.go
- pkg/componentsregistry/componentsregistry.go
To make it possible to mock registry in DSC reconcileComponents for testing, implement registry as a structure. Make package level wrappers on Add and ForEach methods which operate on the default statically created registry.
This allows keep working with the default registry in a real system without extra arguments like before. It's in init()s and in main(). But code under test can accept testing version when needed.
> componentsregistry: use structure to store handlers

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/components/kueue/kueue.go
- controllers/components/kueue/kueue_controller.go
- controllers/components/kueue/kueue_controller_actions.go
- controllers/components/kueue/kueue_support.go
- controllers/datasciencecluster/kubebuilder_rbac.go
- pkg/cluster/cluster_config.go
- pkg/cluster/const.go
- pkg/cluster/gvk/gvk.go
- tests/e2e/components_test.go
- tests/e2e/kueue_test.go
- only add VAP specific manifests into list if latest OCP version in history is over 16 in min version
- add check OCP function to get OCP version during main startup, and value can be access by components also show in the dsc status
https://issues.redhat.com/browse/RHOAIENG-16133
manual test on quay.io/wenzhou/opendatahub-operator-catalog:v2.17.1613315
spin up two clusters
- 4.17.9:  
create DSCI, DSC only enable kueue
kueue CR ready, 2 new resource VAP and VAPB created
change VAPB action from Deny to Warn, it keeps new value
disable kueue
kueue CR removed, VAP removed, VAPB remains
- 4.15.6 then upgrade to 4.16.27: cretae DSCI, DSC only enable kueue
kueue CR ready, no API registered in cluster for VAP/VAPB CRD, operator pod not throw error
> feat: add support for kueue to work with VAP on OCP 4.16+

- tests/e2e/cfmap_deletion_test.go
- tests/e2e/controller_test.go
- tests/e2e/creation_test.go
When the e2e test suite starts, it may take a while for some of the
owned namespace to become available and in such case the related test
would fail, since it does not retry. This commit replace the current
synchronous test with an asynchronous one.
> e2e: improve testOwnedNamespacesAllExist by leveragin gomega's async assertions

- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/dscinitialization_test.go
- controllers/dscinitialization/utils.go
- main.go
- pkg/metadata/labels/types.go
cherry-pick https://github.com/opendatahub-io/opendatahub-operator/pull/1370 + more kinds
Add more information for this PR:
we keep managed cluster as is, we do not change logic for it
user can set to use their own application namespace, but this namespace must follow pre-req:
1. pre-created before ODH operator gets installed
2. this namespace must have "opendatahub.io/application-namespace: true" label
3. only one namespace in the cluster can have this "opendatahub.io/application-namespace: true" label, or operator crash during startup. till user remove labels from other namespace. then crashloop will stop.
4. if this namespace exist, operator use it for cache and ignore opendatahub/redhat-ods-applications in ODH or self-managed case.
operator does not care if application namespace …
> feat: use label selector to pick namespace

- Dockerfiles/Dockerfile
- config/osd-configs/dedicated-admins-mgmt-role.yaml
- config/osd-configs/dedicated-admins-mgmt-rolebinding.yaml
- config/osd-configs/kustomization.yaml
- config/partners/anaconda/base/anaconda-ce-validator-cron.yaml
- config/partners/anaconda/base/kustomization.yaml
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/monitoring.go
- controllers/services/monitoring/monitoring.go
- controllers/services/monitoring/monitoring_controller.go
- controllers/services/monitoring/monitoring_controller_actions.go
- main.go
- pkg/cluster/gvk/gvk.go
- pkg/controller/handlers/handlers.go
- pkg/controller/predicates/component/component.go
- pkg/controller/predicates/resources/resources.go
- tests/e2e/controller_test.go
- tests/e2e/monitoring_test.go
- tests/e2e/odh_manager_test.go
- tests/prometheus_unit_tests/codeflare-alerting.rules.yaml
- tests/prometheus_unit_tests/data-science-pipelines-operator-alerting.rules.yaml
- tests/prometheus_unit_tests/kserve-alerting.rules.yaml
- tests/prometheus_unit_tests/kueue-alerting.rules.yaml
- tests/prometheus_unit_tests/model-mesh-alerting.rules.yaml
- tests/prometheus_unit_tests/odh-model-controller-alerting.rules.yaml
- tests/prometheus_unit_tests/ray-alerting.rules.yaml
- tests/prometheus_unit_tests/rhods-dashboard-alerting.rules.yaml
- tests/prometheus_unit_tests/trainingoperator-alerting.rules.yaml
- tests/prometheus_unit_tests/trustyai-alerting.rules.yaml
- tests/prometheus_unit_tests/workbenches-alerting.rules.yaml
The scope of this PR is reduced to only watch and update prometheus configmap for components.
1. Deploy Managed Instance:
- Create dummy secrets - (Refer olm install script in gitlab)
- Deploy Managed Catalogsource: quay.io/vhire/opendatahub-operator-catalog:v2.17.0-rc4
2. Expect alerts only for components that are in Managed state
> Update Component rules in Prometheus

- tests/e2e/helper_test.go
- tests/e2e/kserve_test.go
> e2e: add cleanup logic to kserve tests to ensure no KnativeServing is present in the cluster

- tests/e2e/kserve_test.go
> e2e: add cleanup logic to kserve tests to ensure no KnativeServing instances are present in the cluster

- controllers/dscinitialization/dscinitialization_controller.go
- controllers/dscinitialization/dscinitialization_test.go
- controllers/dscinitialization/utils.go
- main.go
- pkg/metadata/labels/types.go
* feat: use label selector to pick namespace
- for clean installation:
- if user keep using default pre-defined namespace: same as before
- if user want to use a different namespace: they will need to create project themselves, and add label "opendatahub.io/application-namespace": "true" then install ODH operator and create DSCI by fill in this namespace or install RHOAI and delete auto created DSCI and create DSCI by fill in this namespace
- add more resource kinds into cache due to change use component CR with owns and watches
- add check when start up if we get multiple customized application ns then exit
- add check in DSCI controller: for customized app ns: check if it exists and has label, if not exit as error (do not handle managed case for now since we do not support that yet) …
> [sync] : use label selector to pick namespace (#1427)

- main.go
- rhoai both self and managed need networkpolicy on redhat-ods-operator namespace
(cherry picked from commit c2c38e244ed2470a041c8220f7f7e7a459de49c2)
this  commit is done during testing rhoai build and found networkpolicy for monitoring is missing in the cache for operator namespace. on the same side to add it for all case even ODH
> [backport] fix: networkpolicy

- tests/e2e/helper_test.go
Reverts opendatahub-io/opendatahub-operator#1517
> Revert "e2e: add cleanup logic to kserve tests to ensure no KnativeServing is present in the cluster"

- pkg/controller/actions/render/template/action_render_templates.go
- pkg/controller/actions/render/template/action_render_templates_test.go
- pkg/controller/actions/render/template/resources/smm-data.tmpl.yaml
When creating a template rendering action, is is now possible to compute dynamic data based on the current `ReconciliationRequest`:
```go
action := template.NewAction(
template.WithData(map[string]any{
"ID": id,
"SMM": map[string]any{
"Name": name,
},
"Foo": "bar",
}),
template.WithDataFn(func(_ context.Context, rr *types.ReconciliationRequest) (map[string]any, error) {
return map[string]any{
"Foo": "bar",
"UID": rr.Instance.GetUID(),
}, nil
}),
)
```
> Add support for dynamic template data computation in template rendering action

- pkg/controller/reconciler/reconciler.go
- pkg/controller/reconciler/reconciler_support.go
- pkg/controller/types/types.go
- remove generics from Reconciler struct as it is not needed
- set PlatformObject as the base obnject that the Reconciler handles to
ensure the reconciler can access to common objects fields
> chore: remove generics from Reconcier and use PlatformObject as base object type

- controllers/dscinitialization/dscinitialization_test.go
- controllers/dscinitialization/utils.go
- pkg/upgrade/upgrade.go
This PR ensures proper cleanup of the default RoleBinding that assigned the default ServiceAccount to the anyuid SCC.
It follows the previous [PR](https://github.com/opendatahub-io/opendatahub-operator/pull/1460) that removed ServiceAccounts like Notebook, ModelMesh, ModelController, and Dashboard from similar RoleBindings.
> Cleanup of deprecated RoleBinding

- controllers/dscinitialization/utils.go
- monitoring should be only for rhoai and we only support fixed name for now
- but in upstream odh, we just set all namespace to the same one, 
- in old code, it was a "err = r.Patch(ctx, foundMonitoringNamespace, client.RawPatch(types.MergePatchType, []byte(labelPatch)))" call
but for some reason this is not 100% reproduciable
i have it passed in clean new cluster
i have it failed with error 
`{"level":"error","ts":"2025-01-21T15:42:30Z","msg":"error patch monitoring namespace for managed cluster","controller":"dscinitialization","controllerGroup":"dscinitialization.opendatahub.io","controllerKind":"DSCInitialization","DSCInitialization":{"name":"e2e-test-dsci"},"namespace":"","name":"e2e-test-dsci","reconcileID":"105251cf-09d0-4ae6-a552-4333d540a581","error":"namespaces \"opendatahub\" …
> fix: when app ns and monitoring ns are the same, createorupdate wont work

- controllers/services/monitoring/monitoring_controller_actions.go
This reduce the direct dependency from Monitoring to DSCI
> fix: use Monitoring.Spec.Namespace instead of the DSCI one

- controllers/services/monitoring/monitoring_controller_actions.go
The Monitoring controller is initialized only when the platform is
managed, hence there's no need to conditionally add manifests
> chore: cleanup Monitoring's initialize action

- controllers/components/kserve/kserve_controller.go
- controllers/components/modelmeshserving/modelmeshserving_controller.go
The KServe and ModelMesh are shipping the same CRDs as part of
their manifests but with different versions, this cause the
respective component reconcilers to keep trying to install
their respective version, ending in a infinite loop.
This commit does not solve the underlying problem of having two
components shipping the same CRDs with different versions, but
avoids the infinite reconcile loop. The CRDs that is actually
installed on the cluster is undefined, the latest one that is
applied wins
(cherry picked from commit 36b829caf9258be3dfdef0eb9d16d0cbc032666c)
https://issues.redhat.com/browse/RHOAIENG-18518
> [rhoai] Avoid modelmesh and Kserve loop on updating shared CRDs

- controllers/components/kserve/kserve_controller.go
- controllers/components/modelmeshserving/modelmeshserving_controller.go
The KServe and ModelMesh are shipping the same CRDs as part of
their manifests but with different versions, this cause the
respective component reconcilers to keep trying to install
their respective version, ending in a infinite loop.
This commit does not solve the underlying problem of having two
components shipping the same CRDs with different versions, but
avoids the infinite reconcile loop. The CRDs that is actually
installed on the cluster is undefined, the latest one that is
applied wins
https://issues.redhat.com/browse/RHOAIENG-18518
- enable the KServe and ModelMesh component
- observe the CRDs chaing version version, which should change a few tie but should stabilize 
`kubectl get crd servingruntimes.serving.kserve.io -o yaml -w | grep kubebuilder`
`kubectl get crd …
> Avoid modelmesh and Kserve loop on updating shared CRDs

- controllers/dscinitialization/monitoring.go
- main.go
- pkg/cluster/const.go
- blackbox require this
[RHOAIENG-14787](https://issues.redhat.com/browse/RHOAIENG-14787)
> fix: add missing namespace for console in managed cluster

- controllers/dscinitialization/monitoring.go
- main.go
- pkg/cluster/const.go
- blackbox require this
- move into const in cluster pkg
(cherry picked from commit 28d0fa1a42d70defeafd9d1055a83617aba7d22c)
[RHOAIENG-14787](https://issues.redhat.com/browse/RHOAIENG-14787)
> [sync]: fix: add missing namespace for console in managed cluster (#1552)

- config/monitoring/networkpolicy/operator/operator.yaml
- controllers/dscinitialization/utils.go
- main.go
- fix missing RHOAI monitoring namespace for self-managed from  https://github.com/opendatahub-io/opendatahub-operator/pull/1511
- fix wrong namespace name in  manifests from https://github.com/opendatahub-io/opendatahub-operator/pull/1511
- update hardcode label name
- fix misleading log message
> update: various fix backport from RHOAI

- get_all_manifests.sh
This PR updates the get_all_manifests.sh script to align with the Kubeflow main branch by ensuring it pulls manifests from the correct sources.
> Align get_all_manifests.sh with Kubeflow main branch

- main.go
- remove subs from client cache. as follow up from https://github.com/opendatahub-io/opendatahub-operator/pull/1555
- add smcp into disable cache, as we see in some cases SCMP is missing? 
https://issues.redhat.com/browse/RHOAIENG-18425
> update: change previous workaround for subscription and add smcp in disable list

- README.md
- controllers/dscinitialization/utils.go
- docs/troubleshooting.md2
- update README and troubleshooting
https://issues.redhat.com/browse/RHOAIENG-18607?focusedId=26467211&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-26467211
> fix: add matchlabel on NWP for customized appliation

- controllers/dscinitialization/dscinitialization_controller.go
- main.go
- pkg/deploy/deploy.go
- pkg/upgrade/upgrade.go
- remove reference we explicilty check on odhdashboardconfig and kserve, these are not used after refactor which does not call createResource on previous DSC "owned" ones
- remove customized config on controller QPS
- remove passing dscApplicationsNamespace in main to createdefaultDSCI, since we have default value set in the api, we do not need that value which is another default from --dsc-applications-namespace from flag
- remove flag --operator-name which is not used anywhere
> update: clean up old code before refactor

- controllers/components/kserve/kserve_controller.go
- pkg/controller/predicates/resources/resources.go
- pkg/feature/servicemesh/conditions.go
The `Kserve` component requires certain resources to be available and ready, which may not always be the case, especially when the the operator starts on a fresh installation. To handle this, a wait condition was implemented; however, it did not properly check for errors. As a result, the wait loop was prematurely stopped, and no retry attempts were made until the next reconcile loop. Additionally, the Kserve component was not monitoring the `DSCI`, leading to further delays as any transition phases of the `DSCI` were ignored
https://issues.redhat.com/browse/RHOAIENG-18425
1. create DSCI and DSC as part of the same yaml file (with serverless enabled and kserve enabled as well)
2. apply the file
3. watch the Kserve component progressing
DSCI created at **2025-01-24T16:05:19Z**
```yaml …
```
> It takes more than 10 minutes for kserve-controller to be created during 2.17 installation

- tests/e2e/helper_test.go
- we do not enable monitoring in ODH logic
- we should keep it enable for rhoai branch
> test: disable monitoring config in DSCI for ODH e2e test

- controllers/components/kserve/kserve_controller.go
- pkg/controller/predicates/resources/resources.go
- pkg/feature/servicemesh/conditions.go
* It takes more than 10 minutes for kserve-controller to be created during 2.17 installation
* cleanup
(cherry picked from commit 48341ffdc20606a517f65502662d39515716737e)
https://issues.redhat.com/browse/RHOAIENG-18425
> [sync]It takes more than 10 minutes for kserve-controller to be created during 2.17 installation (#1564)

- controllers/services/auth/resources/admingroup-role.tmpl.yaml
Adding admin permission for hardware profiles
JIRA: [RHOAIENG-17839](https://issues.redhat.com/browse/RHOAIENG-17839)
> Setup admin permissions for hardware profiles

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/components/kserve/kserve_controller.go
- controllers/components/kserve/kserve_controller_actions.go
- controllers/components/kserve/kserve_support.go
- controllers/datasciencecluster/kubebuilder_rbac.go
- controllers/dscinitialization/kubebuilder_rbac.go
- pkg/cluster/gvk/gvk.go
- pkg/cluster/meta.go
- pkg/controller/actions/deploy/action_deploy.go
- pkg/controller/actions/deploy/action_deploy_support.go
- pkg/controller/actions/deploy/action_deploy_support_test.go
- pkg/controller/reconciler/reconciler.go
- pkg/feature/builder.go
- pkg/feature/feature.go
- pkg/feature/feature_tracker_handler.go
- pkg/feature/handler.go
- pkg/resources/resources.go
- pkg/resources/resources_test.go
- tests/e2e/kserve_test.go
- Make it possible to set FT's OwnerReference as Controller reference so
the kubernetes garbage collector can block owner deletion till the FT
has been deleted
- Make it possible to set FT's generated resources OwnerReference as 
Controller reference so the kubernetes garbage collector can block
FT deletion till the resources have been deleted
- Add an Kserver reconciler action to remove legacy ownership on
DSCI/DSC is any and related e2e tests
Relates to https://issues.redhat.com/browse/RHOAIENG-18590
> Improve Kserve's FeatureTraker handing

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/datasciencecluster/kubebuilder_rbac.go
- cleanup duplicated one
`{"level":"error","ts":"2025-01-29T13:54:17Z","msg":"Failed to execute action","controller":"dashboard","controllerGroup":"components.platform.opendatahub.io","controllerKind":"Dashboard","Dashboard":{"name":"default-dashboard"},"namespace":"","name":"default-dashboard","reconcileID":"7a6f42d0-9e03-4b2a-9172-0fe72aa97084","action":"github.com/opendatahub-io/opendatahub-operator/v2/pkg/controller/actions/deploy.(*Action).run-fm","error":"failed to remove owner references from object /rhodslink with gvk console.openshift.io/v1, Kind=ConsoleLink: consolelinks.console.openshift.io \"rhodslink\" is forbidden: User \"system:serviceaccount:redhat-ods-operator:redhat-ods-operator-controller-manager\" cannot update resource \"consolelinks\" in API group …
> fix: more permission need for dashboard for consolelink

- apis/dscinitialization/v1/dscinitialization_types.go
- config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
Jira: https://issues.redhat.com/browse/RHOAIENG-18931
Api sets default value to opendatahub, but without "omitempty" in
case of operator automatically creates DSCI (upgrade.go:CreateDefaultDSCI), the resulting object contains applicationsNamespace: "" and it's not defaulted by the api server causing then problems like
```
Namespace "" is invalid: metadata.name: Required value: name or generateName is required
```
The problem was triggered by removing default value for command line switch in the cleanup.
Fixes: b0a0f87897e2 ("update: clean up old code before refactor (#1494)")
> apis: DSCInitialization: annotate ApplicationsNamespace with omitempty

- pkg/upgrade/upgrade.go
When upgrading from version 2.16 to 2.17, the odh-model-controller
fails to be provisioned due to the immutability of the deployment's
label selectors. In RHOAI ≤ 2.16, the model controller was deployed
independently by both kserve and modelmesh, leading to variations
in label assignments depending on the deployment order. During a
redeployment or upgrade, this error was ignored, and the model
controller would eventually be reconciled by the appropriate component.
However, in version 2.17, the model controller is now a defined
dependency with its own fixed labels and selectors. This change
causes issues during upgrades, as existing deployments cannot be
modified accordingly.
https://issues.redhat.com/browse/RHOAIENG-18937
- Install RHOAI 2.16
- Enable the ModelMesh or Kserve component
- …
> Remove legacy ModelController deployment on upgrade

- Makefile
Components tests after refactoring is performed sequentially and due to dependencies it's tricky to run them in parallel.
Workaround: increase timeout to unblock CI queue.
> tests: e2e: increase timeout to 40m

- controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
- controllers/datasciencecluster/datasciencecluster_controller.go
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/services/monitoring/monitoring_controller_actions.go
- pkg/cluster/resources.go
- pkg/cluster/resources_test.go
- pkg/controller/reconciler/reconciler.go
- pkg/upgrade/upgrade.go
- pkg/utils/test/fakeclient/fakeclient.go
There are a number of places where we have to lookup singleton objects,
such as the DSC or DSCI and, with the introduction of per component and
service APIs, potentially for each component/service ad we relies on the
list retrieval and validation. This commit introduces some helper
function to avoid repating the same logic over and over again, in
particular for commonly accessed singletons:
- cluster.GetSingleton
- cluster.GetDSCI
- cluster.GetDSC
Example code to retrieve an instance of the dashbaord component:
```go
obj := &componentv1.Dashboard{}
err := cluster.GetSingleton(ctx, cli, obj)
switch {
case k8serr.IsNotFound(err):
// do something
case err != nil:
return err
}
```
> Add helper functions to retrieve object singletons

- pkg/upgrade/upgrade.go
we do not ,by default, set new component to Managed when we first add it into ODH 2.24.0
let me know unless this policy has been chanaged.
> fix: do not set feast default to managed till GA

- controllers/services/monitoring/monitoring_controller_actions.go
> [Sync] changes from main

- tests/e2e/trustyai_test.go
The TrustyAI component requires some CRDs shipped as part of the kserve
component to be present in the cluster befoire starting the controller.
> e2e: enable kserve before running TrustyAI tests

- controllers/components/modelcontroller/modelcontroller_actions.go
- kserve-state and modelmeshserving-state with managed or removed in params.env
ref https://issues.redhat.com/browse/RHOAIENG-18974
enable modelmesh and kserve then check
> update: add new key-value into odh-model-controller

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- controllers/components/kueue/kueue_controller.go
- controllers/components/kueue/kueue_controller_actions.go
- controllers/status/status.go
- pkg/cluster/gvk/gvk.go
- pkg/cluster/operator.go
- tests/e2e/components_test.go
- tests/e2e/helper_test.go
- tests/e2e/kueue_test.go
- DSC condition on kueueReady: 
reason: MultiKueueCRDV1Alpah1Exist 
message: MultiKueue CRDs MultiKueueConfig v1alpha1 and MultiKueueCluster v1alpah1 exist, please remove them before proceed
- reconcile gets triggered by user's deletion on these 2 CRD
ref: https://issues.redhat.com/browse/RHOAIENG-18251
local build: quay.io/wenzhou/opendatahub-operator-catalog:v2.23.205
> feat: add check on 2 MultiKueue CRD if v1alpha1 version in the cluster and not in termination, error out

- CONTRIBUTING.md
- docs/sync_code.md
* docs: update workflow and how we use two branchs for ODH and downstream
- add new doc for how workflow, label on PR, sync process
- update branch away from incubatin in github action and reference
* Update docs/sync_code.md
Co-authored-by: Gerard Ryan <git@grdryn.xyz>
* revert: branch related test config
* fix: typo
---------
Co-authored-by: Gerard Ryan <git@grdryn.xyz>
(cherry picked from commit da75d42091f2ba76745bf9682927d2bd1b84fece)
https://issues.redhat.com/browse/RHOAIENG-498
> [sync] docs: update workflow and how we use two branchs for ODH and downsteam (#1582)

- tests/e2e/controller_test.go
Run a combination of  `--test-service` flags, i.e. when enabling only `auth` service test. he output looks like:
```
=== RUN   TestOdhOperator/services
controller_test.go:199: Skipping tests for services monitoring
=== RUN   TestOdhOperator/services/auth
=== RUN   TestOdhOperator/services/auth/e2e-test-dsc
=== RUN   TestOdhOperator/services/auth/e2e-test-dsc/Auto_creation_of_Auth_CR
=== RUN   TestOdhOperator/services/auth/e2e-test-dsc/Test_Auth_CR_content
=== RUN   TestOdhOperator/services/auth/e2e-test-dsc/Test_role_creation
=== RUN   TestOdhOperator/services/auth/e2e-test-dsc/Test_rolebinding_creation
=== RUN   TestOdhOperator/services/auth/e2e-test-dsc/Test_rolebinding_is_added_when_group_is_added
=== RUN   TestOdhOperator/services/auth/e2e-test-dsc/Test_clusterrole_is_added_when_group_ …
```
> Fix e2e services tests flags

- controllers/components/trustyai/trustyai_controller.go
- controllers/components/trustyai/trustyai_controller_actions.go
- controllers/status/status.go
- pkg/cluster/gvk/gvk.go
- tests/e2e/trustyai_test.go
if Trustyai is enabled but cluster does not have ISVC (new cluster, cluster never had serving enabled)
DSC.status.components.trustyai
- InferenceServiceCRDMissing"
- InferenceServices CRD does not exist, please enable serving component first
Due of the ongoing changes in TrustyAI, SR wont be a problem any more, the only dependency is ISVC
this requires https://github.com/trustyai-explainability/trustyai-service-operator/pull/400 and its sync to ODH done first
https://issues.redhat.com/browse/RHOAIENG-19261
> feat: add gate in TrustyAI if ISVC CRD is not in the cluster

- tests/e2e/cfmap_deletion_test.go
- tests/e2e/controller_test.go
- tests/e2e/creation_test.go
- tests/e2e/helper_test.go
This feature is to improve the configurability of the e2e test suite,
which is particularly useful when running the test suite locally.
There are two new flags to globally enabled/disable some test grouops
such as components and services:
* --test-components=true|false
* --test-services=true|false
It is also possible to disable a particular test by preceding its name
with an exlamation mark (!), i.e. to run only the test for the dashbaord
component and skip the tests for the auth service:
```shell
make e2e-test E2E_TEST_FLAGS='--test-component=dashboard --test-service=!auth'
```
When running the tests with:
```shell
make e2e-test E2E_TEST_FLAGS='-timeout 25m --test-operator-controller=false --test-webhook=false --test-component=dashboard --test-service=!auth'
```
The output is:
```
=== …
```
> Improve e2e test configurability

- pkg/controller/actions/gc/action_gc.go
- pkg/controller/actions/gc/action_gc_support.go
- pkg/controller/actions/gc/action_gc_test.go
- pkg/services/gc/gc.go
- pkg/services/gc/gc_support.go
Extracted from https://github.com/opendatahub-io/opendatahub-operator/pull/1605
> Improve gc service/action

- tests/e2e/controller_test.go
- tests/e2e/feastoperator_test.go
Feast stored image on docker.io which tends to report RateLimit error.
It was agreed that images will be moved, but until then disable it.
> tests: e2e: disable FeastOperator

- tests/e2e/controller_test.go
It is now possible to set the list of components/services to test as a comma separated value:
```shell
make e2e-test E2E_TEST_FLAGS='--test-component=dashboard,modelregistry --test-component=ray'
```
> e2e: add compoennt/services flags support for parsing comma-separated values

- controllers/dscinitialization/dscinitialization_controller.go
- controllers/services/monitoring/monitoring_controller_actions.go
- fix a reason field in the ready condition to make it compliant to the
expected validation (CamelCase, no spaces)
- use controllerutil.SetOwnerReference to set owner reference on the
Monitoring CR as it enforces all the required fields to be set
Relates to https://issues.redhat.com/browse/RHOAIENG-19943
> Fix monitoring controller condition and owner reference setup

- controllers/dscinitialization/auth.go
- controllers/dscinitialization/dscinitialization_controller.go
- controllers/services/auth/auth_controller.go
- controllers/services/auth/auth_controller_actions.go
- tests/e2e/authcontroller_test.go
Add functionality to the Auth controller and fix bugs. [RHOAIENG-19716](https://issues.redhat.com/browse/RHOAIENG-19716)
- Move copying of groups from dashboardConfig to create action in DSCI.
- Remove watch of dashboardConfig.
- If there are no groups in either list remove the rolebindings.
- Add validation on clusterRole to omit system:authenticated.
- Add e2e test for removing groups and validating the rolebinding are removed.
_Auth CR created with Defaults_
- Install operator.
- Create DSCI.
- Validate the Auth CR is created with the defaults.
_Auth CR reads defaults from dashboardConfig_
- Install operator.
- Create odhDashboardConfig with non-default groups, ie not system:authenticated as allowedGroup.
- Create DSCI.
- Validate Auth CR contents reflects the non-default content and …
> Move  dashboardConfig checking to Auth CR creation.

- controllers/dscinitialization/dscinitialization_controller.go
- controllers/services/monitoring/monitoring_controller_actions.go
- fix a reason field in the ready condition to make it compliant to the
expected validation (CamelCase, no spaces)
- use controllerutil.SetOwnerReference to set owner reference on the
Monitoring CR as it enforces all the required fields to be set
(cherry picked from commit 0fc449e391a48bd488a64f19a5eb706eb2234666)
> [rhoai] Fix monitoring controller condition and owner reference setup

- pkg/controller/reconciler/reconciler.go
- pkg/controller/reconciler/reconciler_finalizer_test.go
At the moment, custom clean-up/delete actions can be added via `WithFinalizer()` in the component reconciler builder. If present, such actions would be then executed during deletion in `Reconcile()` call. While no custom clean-up actions are being utilized as of now across the components, this PR extends the functionality to provide support for using finalizers in case such actions are desired in the future
JIRA reference: [RHOAIENG-15920](https://issues.redhat.com/browse/RHOAIENG-15920)
> feat: Add support for finalizers

- controllers/components/kserve/kserve_controller.go
- controllers/components/kserve/kserve_support.go
Before this change, these watches don't work properly, and modifying a
matching resource doesn't lead to a new reconciliation request being
enqueued.
To demonstrate this, once can annotate a matching resource and notice
that before this change Kserve reconciliation doesn't happen. With
this change, reconciliation occurs as expected.
Before this change, the following doesn't lead to reconciliation:
```
oc annotate knativeserving -n knative-serving knative-serving a=a
```
After this change, the following DOES lead to reconciliation:
```
oc annotate knativeserving -n knative-serving knative-serving b=b
```
> Add missing predicates for Kserve dynamic watches

- controllers/components/modelregistry/modelregistry_controller.go
- controllers/components/modelregistry/modelregistry_controller_actions.go
- pkg/cluster/gvk/gvk.go
This PR is aimed a removing the custom handling of some specific MR's `ClusterRoles`:
- modelregistry-editor-role 
- modelregistry-viewer-role 
Which does not make much sense to keep them, since we are removing all the other `ClusterRoles`
1. Enable MR on DSC
2. Check for the presence of the mentioned `ClusterRoles`
3. Disable MR on DSC
4. the mentioned `ClusterRoles` should have gone
> model-registry: remove custom handdling of the modelregistry-editor-role and modelregistry-viewer-role cluster roles

- Dockerfiles/Dockerfile
My machine runs on linux/arm64, but I want to be able to run container
images that I build during development on x86_64 clusters.
The main problem is that the default is to use the TARGETPLATFORM for
all stages in an image build, which means that, for example, the `go`
commands that are run in the `builder` stage will be using an x86_64
`go` binary, which essentially doesn't work on aarch64.
When this instead specifies to use BUILDPLATFORM for those stages
before the last one, it defaults to using the local platform (os/arch)
for those containers, so I get aarch64 builder stage container images,
containing aarch64 `go` binaries.
Since I specify `--platform=linux/amd64` when doing the `podman
build`, it will still build an aarch64 binary of the operator, and put
that into an aarch64 final …
> chore: Allow cross-compilation in Dockerfile

- tests/e2e/codeflare_test.go
- tests/e2e/datasciencepipelines_test.go
- tests/e2e/kueue_test.go
- tests/e2e/modelregistry_test.go
- tests/e2e/ray_test.go
- tests/e2e/trainingoperator_test.go
- tests/e2e/trustyai_test.go
> e2e(components): ensure components are turned off at the end of the related test suite

- controllers/dscinitialization/resources/authorino/deployment.injection.patch.tmpl.yaml
- controllers/dscinitialization/servicemesh_setup.go
- change annotations to labels when we do patch on authornio deployment
rewrite of https://github.com/opendatahub-io/opendatahub-operator/pull/1513
https://issues.redhat.com/browse/RHOAIENG-18238
local build quay.io/wenzhou/opendatahub-operator:2.26.18238
- install operator
- install authornio servicemesh operator
- create DSCI with servicemesh Managed
- check authorino-XXX pod in opendatahub-auth-provider ns has 2 contains, one is istio-proxy
> update: change ossm sidecar as labels on authornio deployment

- tests/e2e/authcontroller_test.go
e2e failures in https://github.com/opendatahub-io/opendatahub-operator/pull/1674 seem to be caused by the function for returning the adminGroup getting an empty platform and returning the wrong group. Fix this by setting the group in the test.
> fix auth tests for RHOAI

- cmd/component-codegen/go.mod
> chore(tools): use go 1.22 for component-codegen

- controllers/dscinitialization/utils.go
- main.go
- remove managed fields, as they are not used directly by the operator code
- add `Pods` to the list of uncached objects because as today, we don't set any filter, hence we are caching all the Pods in a cluster
- add `Group` to the list of uncached objects, since such objects are only created once
- replace `Group` GET+CREATE with just CREATE since the objects are not more in the cache
This is not a very accurate analysis, but running a controller with the small optimization introduced by the PR (blue line), seems to report a constant reduction of the memory consumption of ~ 10 MB on pretty much empty cluster
```shell
NAME                                                       CPU(cores)   MEMORY(bytes)   
opendatahub-operator-controller-manager-64c7594b46-9dccp   1m           173Mi …
```
> Improve controller-runtime cache configuration

- controllers/dscinitialization/dscinitialization_controller.go
removed creation of this CM in https://github.com/opendatahub-io/opendatahub-operator/pull/1511 but seems it is needed for SelfManaged cluster 
this is to put it back in the logic
- if DSCI monitoring is Managed
- if user has not disable tracking data usage in Dashboard
- if odhdashbaordconfig has disableTracking:false
then some track data will be sent to internal system.
ref https://issues.redhat.com/browse/RHOAIENG-18495
> fix: add back CM odh-segment-key-config for Self-Managed cluster

- controllers/dscinitialization/utils.go
- main.go
* feat: tune controller-runtime cache
- remove managed fields, as they are not used directly by the operator
code
- add Pods to the list of uncached objects as they may have an high
cardinality
- add Group to the list of uncached objects, since such objects are only
created once
* chore: replace Group GET+CREATE with just CREATE
(cherry picked from commit 6b2dcfcb13f6ffa1c254ec634db3e2c0dc600621)
> [rhoai] Improve controller-runtime cache configuration

- pkg/controller/actions/gc/action_gc.go
- pkg/controller/actions/gc/action_gc_support.go
- pkg/controller/actions/gc/action_gc_test.go
- pkg/resources/resources.go
- pkg/services/gc/gc.go
- **Improve GC action (#1679)**
- **Improve gc action to only collect owned resources by default (#1703)**
- **chore(gc): prevent redundant deletion of resources already marked for termination (#1725)**
> [rhoai] Improve gc service/action

- pkg/utils/test/scheme/scheme.go
(cherry picked from commit 7a4e1c78960e5c1a5933e4e8179d1bd65d5580b9)
> Add github.com/openshift/api/oauth/v1 to the default schema list

- controllers/datasciencecluster/datasciencecluster_controller.go
- pkg/componentsregistry/componentsregistry.go
To make it possible to mock registry in DSC reconcileComponents for
testing, implement registry as a structure. Make package level
wrappers on Add and ForEach methods which operate on the default
statically created registry.
This allows keep working with the default registry in a real system
without extra arguments like before. It's in init()s and in
main(). But code under test can accept testing version when needed.
Signed-off-by: Yauheni Kaliuta <ykaliuta@redhat.com>
(cherry picked from commit 86227539c2fd145649c79f460224bd96e210f7cb)
> [rhoai] componentsregistry: use structure to store handlers

- controllers/dscinitialization/resources/metrics-collection/envoy-metrics-collection.tmpl.yaml
- both ingress and egress is using this name
- explicility set to http as default one
ref https://issues.redhat.com/browse/RHOAIENG-20131
- install servicemesh and authorion
- install local build quay.io/wenzhou/opendatahub-operator-catalog:v2.19.20131 
- create DSCI
- no need DSC
- check console->observe->targets, PM on data-science-smcp-envoy-monitor should be Up
> fix: add missing port in the podmonitor

- controllers/dscinitialization/resources/metrics-collection/envoy-metrics-collection.tmpl.yaml
- both ingress and egress is using this name
- explicility set to http as default one
(cherry picked from commit 015c546da3569dd75d1dcf366e88684546170b82)
sync https://github.com/opendatahub-io/opendatahub-operator/pull/1743
ref https://issues.redhat.com/browse/RHOAIENG-20131
> [sync]fix: add missing port in the podmointor (#1743)

- controllers/datasciencecluster/datasciencecluster_controller_actions.go
- main.go
- pkg/controller/actions/actions_support.go
- pkg/controller/actions/gc/action_gc.go
- pkg/controller/actions/gc/action_gc_test.go
- pkg/controller/actions/gc/engine/gc_engine.go
- pkg/controller/actions/gc/engine/gc_engine_support.go
- pkg/controller/actions/gc/engine/gc_engine_test.go
- pkg/controller/actions/status/deployments/action_deployments_available.go
The original GC action/service was designed under the assumption that
all Kubernetes resource types the operator manages were known at
startup and remained unchanged over time. As a result, a single GC
service was shared across multiple GC actions.
However, with the removal of feature trackers and the need of dynamic
dependencies (e.g., Serverless, Service Mesh), this static resource
list assumption is no longer valid.
To address this, the shared GC service has been removed, and the GC
engine is now integrated directly within each GC action.
> Refactor the gc action/service

- controllers/components/modelregistry/modelregistry_controller.go
- controllers/components/modelregistry/modelregistry_controller_actions.go
Add REGISTRIES_NAMESPACE param for model registry in modelregistry_controller_actions.go initialize() function
This param is used by model registry operator in a validation webhook to ensure model registry instances cannot be created outside the configured namespace per RHOAIENG-20962
Fixes RHOAIENG-21660
https://issues.redhat.com/browse/RHOAIENG-21660
All existing tests should pass
> feat: add REGISTRIES_NAMESPACE param for model registry, fixes RHOAIENG-21660

- controllers/dscinitialization/dscinitialization_controller.go
https://issues.redhat.com/browse/RHOAIENG-21836
> ODH/RHOAI Operator does not retry when DSCI fails to create operator resources

- pkg/utils/test/testf/testf_assertions.go
- pkg/utils/test/testf/testf_witht.go
- pkg/utils/test/testf/testf_witht_test.go
The testf methods pass a context.Context instance to all
functions to ensure that those using the Kubernetes client
have access to the correct context, rather than creating
a temporary one.
However, Gomega ignores any default timeout when a context
is provided unless an explicit timeout is set.
This commit ensures that the testf correctly passes the
appropriate timeout to Gomega when executing matchers.
> Ensure testf methods respect the configured timeout/polling settings

- .golangci.yml
- Makefile
- pkg/utils/test/testf/testf.go
- pkg/utils/test/testf/testf_assertions.go
Fixes two warnings in the `lint` job:
```
WARN [lintersdb] The linter "exportloopref" is deprecated (step 2) and deactivated. It should be removed from the list of disabled linters. https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle 
WARN The linter 'tenv' is deprecated (since v1.64.0) due to: Duplicate feature in another linter. Replaced by usetesting. 
ChatGPT ha detto:
```
By running `lint` check:
```
golangci-lint run
```
> chore: Remove/replace deprecated linters

- OWNERS_ALIASES
> Add kahowell to platform team in OWNERS_ALIASES

- pkg/controller/actions/render/template/action_render_templates.go
- pkg/controller/actions/render/template/action_render_templates_test.go
- pkg/controller/actions/render/template/resources/g/sm-01.yaml
- pkg/controller/actions/render/template/resources/g/sm-02.yaml
- pkg/controller/types/types.go
This commit enhances template rendering by introducing support
for glob patterns, allowing more flexible template selection.
Additionally, it adds the ability to set labels and annotations:
- Labels and Annotations can now be defined at the action level.
- Specific template sets can also have their own Labels and Annotations.
> feat(actions): support globs in template rendering; add labels and annotations

- cmd/main.go
The CatalogSource type is only used to determine the platform type at
startup, hence it is not required to keep this in the cache, nor to set
up aninformer/watcher
> chore: add CatalogSource to the list of non cached object

- Makefile
- README.md
- internal/webhook/webhook_suite_test.go
While preparing the migration to the kubebuilder `go/v4` layout for the `rhoai` branch (#1789), I noticed that I incorrectly updated the Makefile on the `main` branch (#1746) so that it would skip the `Webhook Suite` unit tests . This PR fixes that so the `Webhook Suite` unit tests are run properly again. This PR also makes a small update to the `README` to reflect the `operator-sdk` version bump to `v1.33.0` in #1746.
This was missed in #1746 but I noticed it in time for #1789 so the changes from this PR do **not** needed to synced with the `rhoai` branch because they are already included in #1789.
Ran unit tests locally and confirmed that the `Webhook Suite` ran and passed.
> chore: fix webhook unit tests

- internal/controller/components/dashboard/dashboard_controller_actions.go
- internal/controller/components/dashboard/dashboard_support.go
- internal/controller/components/datasciencepipelines/datasciencepipelines_support.go
- internal/controller/components/trustyai/trustyai_support.go
- pkg/cluster/cluster_config.go
- pkg/cluster/const.go
- tests/e2e/authcontroller_test.go
This PR removes the Unknown platform constant (Unknown common.Platform = "") and modifies the dependent code. The use of this constant was either removed, or replaced by OpenDataHub constant as the default option
JIRA ref: [RHOAIENG-21371](https://issues.redhat.com/browse/RHOAIENG-21371)
As of this moment, standard e2e test suite was ran locally before the PR
> update: remove Unknown constant from platform detection logic

- pkg/controller/actions/gc/action_gc.go
- pkg/controller/actions/gc/action_gc_test.go
- pkg/controller/actions/gc/engine/gc_engine.go
- pkg/controller/actions/gc/engine/gc_engine_test.go
- pkg/utils/test/scheme/scheme.go
With the GC engine now fully integrated into the GC action, some
previously split logic can be consolidated:
- The redundant "unremovable" setup, previously done in both the engine
and the action, is now handled solely in the action.
- The selector is now passed to the GC engine via an option function,
aligning with other optional parameters.
- The engine now collects only objects matching the object predicate,
preventing unintended deletions by default.
> chore: cleanup gc action/engine leftover

- internal/controller/dscinitialization/utils.go
- internal/controller/dscinitialization/utils_test.go
https://issues.redhat.com/browse/RHOAIENG-23409
> Cluster-monitoring label missing from redhat-ods-monitoring namespace

- internal/controller/dscinitialization/utils.go
- internal/controller/dscinitialization/utils_test.go
(cherry picked from commit 782709a4d0dd04b112f0989ae93e54d75996c0fc)
> [rhoai] Cluster-monitoring label missing from redhat-ods-monitoring namespace

- docs/COMPONENT_INTEGRATION.md
This PR updates component-codegen template and component integration docs `Init()` headers to contain `common.Platform` instead of `cluster.Platform`, to reflect that this type definition was previously moved
First found and discussed in #1761
> fix/chore: replace outdated cluster.Platform references

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/samples/datasciencecluster_v1_datasciencecluster.yaml
Reverts opendatahub-io/opendatahub-operator#1609
this part should had been reverted in https://github.com/opendatahub-io/opendatahub-operator/pull/1652
> Revert "fix: add missing new pipeline flag into default sample"

- internal/controller/dscinitialization/dscinitialization_test.go
- internal/controller/dscinitialization/utils.go
Remove unused odh-common-config and the relevant tests
* https://issues.redhat.com/browse/RHOAIENG-21276
Tested using Jenkins Smoke and Operator tests
* https://quay.io/repository/rh-ee-froman/opendatahub-operator
* https://quay.io/repository/rh-ee-froman/opendatahub-operator-bundle
* https://quay.io/repository/rh-ee-froman/opendatahub-operator-catalog
> fix:RHOAIENG-21276 delete unused odh-common-config in DSCInitialization controller

- pkg/utils/test/matchers/jq/jq_matcher_test.go
This PR implements the optimizations suggested in https://github.com/opendatahub-io/opendatahub-operator/pull/1615#pullrequestreview-2596041004. It simplifies the test structure for kustomize's sortOptions configuration by improving the readability and clarity of the matcher usage. The changes make the tests more straightforward without altering their functionality.
The changes have been tested by running all the unit tests in `jq_matcher_test.go`.
> chore: optimize kustomize sortOptions tests for readability

- internal/controller/components/kserve/kserve_controller_actions_test.go
- internal/controller/dscinitialization/utils_test.go
- pkg/cluster/resources_test.go
- pkg/controller/actions/deleteresource/action_delete_resources_test.go
- pkg/controller/actions/deploy/action_deploy_test.go
- pkg/controller/actions/status/deployments/action_deployments_available_test.go
- pkg/upgrade/upgrade_test.go
- pkg/utils/test/fakeclient/fakeclient.go
- pkg/utils/test/scheme/scheme.go
- pkg/utils/test/testf/testf_witht_test.go
- Make it possible to set interceptors
- Make it possible to set the Scheme to use
- Add additional types to the Namespaced vs Clustered mapping
- Removed redundant TypeMeta configuration for typed objects
(cherry picked from commit a0834ac640029f6b5b39fddcafcdd47557911603)
> [sync] Improve fake client helper

- internal/controller/components/kserve/kserve.go
- internal/controller/components/kserve/kserve_support.go
- internal/controller/components/trustyai/trustyai_support.go
- trustyai: add new variable to overwrite default image
- kserve: add replace in operator startup phase
after https://github.com/opendatahub-io/opendatahub-operator/pull/1967, seems we have more components are using oauth-proxy image.
ref https://issues.redhat.com/browse/RHOAIENG-25691
> feat: add support to pass Oauth proxy image for downstream

- api/infrastructure/v1alpha1/hardwareprofile_types.go
- bundle/manifests/infrastructure.opendatahub.io_hardwareprofiles.yaml
- config/crd/bases/infrastructure.opendatahub.io_hardwareprofiles.yaml
- docs/api-overview.md
JIRA: [RHOAIENG-26729](https://issues.redhat.com/browse/RHOAIENG-26729)
This PR add an optional `PriorityClass` string field to the `KueueSchedulingSpec` block in the `HardwareProfile` CRD. This field is added so a user can reference a Kueue [WorkloadPriorityClass](https://kueue.sigs.k8s.io/docs/concepts/workload_priority_class/).
These changes were tested by building operator, bundle, and catalog images, then verifying that the DSC and DSCI CRs successfully reconcile. It was also verified that the new `PriorityClass` field is present in the `HardwareProfile` CRD as expected.
The following images were used for testing and can be used for verification:
```
quay.io/ckyrillo/opendatahub-operator:v2.29.0
quay.io/ckyrillo/opendatahub-operator-bundle:v2.29.0 …
```
> feat: add priorityClass field to HardwareProfile CRD

- api/infrastructure/v1alpha1/hardwareprofile_types.go
- bundle/manifests/infrastructure.opendatahub.io_hardwareprofiles.yaml
- config/crd/bases/infrastructure.opendatahub.io_hardwareprofiles.yaml
- docs/api-overview.md
JIRA: [RHOAIENG-26717](https://issues.redhat.com/browse/RHOAIENG-26717)
This PR removes the `DisplayName`, `Description`, and `Enabled` fields from the `HardwareProfile` CRD. These fields are mainly for UI purposes and aren't as useful in an API-centric context.
Rather than setting these fields in the CR `.spec`, they will now be exposed as annotations. The user can set the following annotations which the odh-dashboard will look for when displaying the HardwareProfiles in the UI:
```yaml
'opendatahub.io/description': string
'opendatahub.io/display-name': string
'opendatahub.io/disabled': bool
```
These changes were tested by building operator, bundle, and catalog images, then verifying that the DSC and DSCI CRs successfully reconcile. It was also verified that the new `DisplayName`, …
> fix: removed unneeded fields from HardwareProfile

- bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/webhook/manifests.yaml
- internal/webhook/auth/integration_test.go
- internal/webhook/auth/register.go
- internal/webhook/auth/validating.go
- internal/webhook/auth/validating_test.go
- internal/webhook/envtestutil/envtestutil.go
- internal/webhook/webhook.go
- pkg/utils/test/scheme/scheme.go
- tests/e2e/authcontroller_test.go
- tests/e2e/resource_options_test.go
- tests/e2e/test_context_test.go
This is a manual cherry-pick of https://github.com/opendatahub-io/opendatahub-operator/pull/2085 and https://github.com/opendatahub-io/opendatahub-operator/pull/2079.
> Cherry-pick: Auth validating webhook, PodAntiAffinity, and NodeAffinity support

- Dockerfiles/Dockerfile
- config/kueue-configs/batch-user-rolebinding.yaml
- config/kueue-configs/kustomization.yaml
- tests/e2e/kueue_test.go
This PR migrates critical Dockerfile changes and kueue-configs from the main branch to the rhoai branch to fix symlink problems in Docker image generation and add RHOAI-specific Kueue configuration.
**Dockerfile Updates:**
- Added symlink removal fixes for `/opt/manifests/monitoring` before copying
- Added symlink removal fixes for `/opt/manifests/osd-configs` before copying  
- Added symlink removal fixes for `/opt/manifests/kueue-configs` before copying
- Added kueue-configs copy section to Dockerfile
**kueue-configs Directory:**
- Added `config/kueue-configs/kustomization.yaml` - RHOAI configuration for Kueue
- Added `config/kueue-configs/batch-user-rolebinding.yaml` - ClusterRoleBinding for batch users
Based on changes from [PR …
> Migrate Dockerfile symlink fixes and kueue-configs from main

- .github/workflows/check-e2e-update-requirement.yaml
- .github/workflows/comment-on-e2e-check.yaml
- docs/e2e-update-requirement-guidelines.md
follow-up to #2426
- explicitly limits this action to be triggered only on PRs targeted to `main`
- various improvements to documentation and error outputs related to this GH action
> fix: limit e2e update requirement check GH action only to the main branch and improve docs/error outputs

- tests/e2e/components_test.go
- tests/e2e/debug_utils_test.go
- tests/e2e/monitoring_test.go
- tests/e2e/test_context_test.go
Experienced some e2e runs where the problem is the presence in the cluster of deleted resources:
- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/opendatahub-io_opendatahub-operator/2468/pull-ci-opendatahub-io-opendatahub-operator-main-opendatahub-operator-e2e/1968953856947654656
- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/opendatahub-io_opendatahub-operator/2483/pull-ci-opendatahub-io-opendatahub-operator-main-opendatahub-operator-e2e/1968953948857438208
- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/opendatahub-io_opendatahub-operator/2471/pull-ci-opendatahub-io-opendatahub-operator-main-opendatahub-operator-e2e/1969022431163060224
Furthermore, fixes e2e dcs and dsci debug logs and typo.
> test: increase resource timeout and fix dsc debug

- internal/controller/components/dashboard/dashboard.go
- internal/controller/components/dashboard/dashboard_support.go
(cherry picked from commit 1ba404337b2e369db7922d5f32015dd144de37a3)
ref  https://issues.redhat.com/browse/RHOAIENG-31263 
4. Submit/save these changes to the PR description. This will automatically trigger …
> [sync] feat: enable modelreg bff image (#2233)

- internal/webhook/inferenceservice/mutating.go
- internal/webhook/inferenceservice/mutating_test.go
- pkg/metadata/annotations/annotations.go
- pkg/webhook/utils.go
- tests/e2e/kserve_test.go
sync #2532 
4. Submit/save these changes to the PR description. This will automatically trigger the check.
> [rhoai] feat: switch isvc connection annotation from type to protocol

- .golangci.yml
- Makefile
- internal/controller/components/dashboard/dashboard_controller_actions.go
- internal/webhook/envtestutil/envtestutil.go
- internal/webhook/notebook/mutating_test.go
- pkg/cluster/cluster_config_test.go
- pkg/controller/actions/cacher/cacher_test.go
- pkg/controller/actions/gc/action_gc_test.go
- pkg/controller/actions/resourcecacher/resourcecacher.go
- pkg/controller/actions/resourcecacher/resourcecacher_test.go
- pkg/controller/predicates/dependent/dependent.go
- pkg/controller/predicates/partial/partial.go
- pkg/utils/test/envt/envt.go
- pkg/utils/test/testf/testf_witht.go
- tests/e2e/authcontroller_test.go
- tests/e2e/cfmap_deletion_test.go
- tests/e2e/components_test.go
- **Update golangci-lint to v2.5.0 (#2582)**
- **Fix lint finding**
4. Submit/save these changes to the PR description. This will automatically trigger the check.
Linter changes, no need for additional e2e
> Update golangci-lint to v2.5.0

- internal/controller/services/monitoring/monitoring_controller.go
- internal/controller/services/monitoring/monitoring_controller_actions.go
- pkg/utils/test/testf/testf_witht.go
- pkg/utils/test/testf/testf_witht_test.go
- tests/e2e/authcontroller_test.go
- tests/e2e/cfmap_deletion_test.go
- tests/e2e/components_test.go
- tests/e2e/controller_test.go
- tests/e2e/creation_test.go
- tests/e2e/dashboard_test.go
- tests/e2e/datasciencepipelines_test.go
- tests/e2e/helper_test.go
- tests/e2e/kserve_test.go
- tests/e2e/kueue_test.go
- tests/e2e/modelcontroller_test.go
- tests/e2e/monitoring_test.go
- tests/e2e/resilience_test.go
- tests/e2e/resource_fetcher_test.go
- tests/e2e/resource_options_test.go
- tests/e2e/test_context_test.go
- tests/e2e/trustyai_test.go
- tests/e2e/v2tov3upgrade_test.go
This is a manual cherry-pick of https://github.com/opendatahub-io/opendatahub-operator/pull/2550.
4. Submit/save these changes to the PR description. This will automatically trigger the check.
> [sync] feat(e2e): improve test framework resilience and fix monitoring controller cleanup
